using System.Collections.Generic;

namespace ET.Client
{
    public static class ErrorViewData
    {
        [StaticField]
        public static Dictionary<int, string> ErrorHints = new()
        {
            { ErrorCode.ERR_NetWorkError, "网络错误!" },
            { ErrorCode.ERR_AccountAlreadyRegister, "账号已注册!" },
            { ErrorCode.ERR_AccountInBlackListError, "账号异常!" },
            { ErrorCode.ERR_LoginInfoIsNull, "未找到账号数据，请确认账号是否已经注册。" },
            { ErrorCode.ERR_AccountOrPasswordError, "密码错误，请检查重新输入。" },
            { ErrorCode.ERR_OtherAccountLogin, "账号异地登录" },
            { ErrorCode.ERR_RequestRepeatedly, "请求重复" },
            { ErrorCode.ERR_EnterQueue, "服务器已满，进入排队系统。" },
            { ErrorCode.ERR_RequestExitFuben, "请先退出副本" },
            { ErrorCode.ERR_StopServer, "停服维护" },
            { ErrorCode.ERR_BingPhoneError_1, "手机号已经注册过账号" },
            { ErrorCode.ERR_BingPhoneError_2, "手机号只能绑定一个账号" },
            { ErrorCode.ERR_VersionNoMatch, "版本不一致，请重开客户端。" },
            { ErrorCode.ERR_EnterGameError, "角色登录异常，请尝试再次重新登录账号!" },
            { ErrorCode.ERR_OtherNotExist, "该玩家不在主城!" },
            { ErrorCode.ERR_NonePlayerError, "玩家不存在!" },
            { ErrorCode.ERR_GoldNotEnoughError, "金币不足!" },
            { ErrorCode.ERR_DiamondNotEnoughError, "钻石不足!" },
            { ErrorCode.ERR_HouBiNotEnough, "货币不足!" },
            { ErrorCode.ERR_ItemBing, "此道具为绑定道具!" },
            { ErrorCode.ERR_EquipChuanChengFail, "装备传承失败!" },
            { ErrorCode.ERR_AlreadyLearn, "已经学习了该技能!" },
            { ErrorCode.ERR_UseSkillInCD1, "技能冷却中..." },
            { ErrorCode.ERR_UseSkillInCD2, "技能公共冷却中!" },
            { ErrorCode.ERR_UseSkillInCD3, "主动技能冷却中!" },
            { ErrorCode.ERR_UseSkillInCD4, "被动技能冷却中!" },
            { ErrorCode.ERR_UseSkillInCD5, "技能冷却中!" },
            { ErrorCode.ERR_UseSkillInCD6, "公共技能冷却中!" },
            { ErrorCode.ERR_CanNotUseSkill_1, "当前状态无法释放技能!" },
            { ErrorCode.ERR_CanNotUseSkill_Rigidity, "僵直状态无法释放技能!" },
            { ErrorCode.ERR_CanNotUseSkill, "当前状态无法释放技能!" },
            { ErrorCode.ERR_CanNotUseSkill_NetWait, "消息未返回无法释放技能!" },
            { ErrorCode.ERR_CanNotUseSkill_Dizziness, "眩晕状态无法释放技能!" },
            { ErrorCode.ERR_CanNotUseSkill_JiTui, "击退状态无法释放技能!" },
            { ErrorCode.ERR_CanNotUseSkill_Silence, "沉默状态无法释放技能!" },
            { ErrorCode.ERR_CanNotUseSkill_Sleep, "沉睡状态无法释放技能!" },
            { ErrorCode.ERR_CanNotUseSkill_Hung, "悬浮状态无法释放技能!" },
            { ErrorCode.ERR_CanNotUseSkill_MP, "魔法值不足!" },
            { ErrorCode.ERR_SkillMoveTime, "当前为技能释放状态!" },
            { ErrorCode.ERR_CanNotSkillDead, "死亡状态无法释放技能!" },
            { ErrorCode.ERR_UseSkillError, "没有目标!" },
            { ErrorCode.ERR_NoUseItemSkill, "该场景不能使用药剂道具技能!" },
            { ErrorCode.ERR_CanNotMove_1, "当前状态无法移动!" },
            { ErrorCode.ERR_CanNotMove_Dead, "死亡状态无法移动!" },
            { ErrorCode.ERR_CanNotMove_Rigidity, "僵直状态无法移动!" },
            { ErrorCode.ERR_CanNotMove_NetWait, "消息未返回无法移动!" },
            { ErrorCode.ERR_CanNotMove_Dizziness, "眩晕状态无法移动!" },
            { ErrorCode.ERR_CanNotMove_JiTui, "击退状态无法移动!" },
            { ErrorCode.ERR_CanNotMove_Shackle, "禁锢状态无法移动!" },
            { ErrorCode.ERR_CanNotMove_Sleep, "沉睡状态无法移动!" },
            { ErrorCode.ERR_CanNotMove_Fear, "恐惧状态无法移动!" },
            { ErrorCode.ERR_CanNotMove_Speed, "速度异常无法移动!" },
            { ErrorCode.ERR_UnionXiuLianMax, "已达修炼上限!" },
            { ErrorCode.ERR_Union_Not_Exist, "没找到公会!" },
            { ErrorCode.ERR_UnSafeSqlString, "非法字符串!" },
            { ErrorCode.ERR_EquipLvLimit, "角色等级不足!" },
            { ErrorCode.ERR_BagIsFull, "背包已满!" },
            { ErrorCode.ERR_ItemNotEnoughError, "道具不足!" },
            { ErrorCode.Error_AngleNotEnough, "怒气不足!" },
            { ErrorCode.Error_PickWaitSelect, "拾取等待中!" },
            { ErrorCode.ERR_ItemDropProtect, "掉落保护中!" },
            { ErrorCode.ERR_ItemBelongOther, "该道具归属其他玩家!" },
            { ErrorCode.ERR_NoPayValueError, "赞助额度不足!" },
            { ErrorCode.ERR_ItemNoUseTime, "道具今天不能再使用!" },
            { ErrorCode.ERR_EquipAppraisal_Item, "鉴定失败!所需鉴定道具不足..." },
            { ErrorCode.ERR_Occ_Hint_1, "转职失败!请先将角色等级提升至18级" },
            { ErrorCode.ERR_Occ_Hint_2, "请不要重复进行转职噢" },
            { ErrorCode.ERR_NotRealName, "请先实名认证" },
            { ErrorCode.ERR_RealNameFail, "实名认证失败!" },
            { ErrorCode.ERR_TeamDungeonTimesMax, "副本参与次数已经最大" },
            { ErrorCode.ERR_WordChat, "世界频道发消息 1分钟1次" },
            { ErrorCode.ERR_InMakeCD, "制作冷却中!" },
            { ErrorCode.ERR_MakeTypeError, "制作类型不符!" },
            { ErrorCode.ERR_ZhuaBuFail, "抓捕失败!" },
            { ErrorCode.ERR_UnionChatLimit, "发消息太频繁 5秒1次" },
            { ErrorCode.ERR_EquipRepeat, "已经有相同类型的装备" },
            { ErrorCode.ERR_WarehouseIsFull, "仓库已满" },
            { ErrorCode.ERR_CreateRoleName, "角色名非法!" },
            { ErrorCode.ERR_RoleNameRepeat, "角色名重复!" },
            { ErrorCode.ERR_ShuLianDuNotEnough, "当前制造需求技巧值不足!" },
            { ErrorCode.ERR_EquipType, "装备穿戴类型不符!" },
            { ErrorCode.ERR_GemNoError, "宝石一旦镶嵌无法卸载!" },
            { ErrorCode.ERR_GemShiShiNumFull, "史诗宝石最多可镶嵌4个!" },
            { ErrorCode.ERR_TeamIsFull, "队伍已满" },
            { ErrorCode.ERR_LevelIsNot, "等级不足" },
            { ErrorCode.ERR_IsHaveTeam, "已经有组队了" },
            { ErrorCode.ERR_TimesIsNot, "次数不足" },
            { ErrorCode.ERR_IsNotLeader, "队长才能创建副本" },
            { ErrorCode.ERR_PlayerIsNot, "人数不足" },
            { ErrorCode.ERR_TeamerLevelIsNot, "队员等级不足" },
            { ErrorCode.Err_OnLineTimeNot, "在线时间不足30分钟领取奖励" },
            { ErrorCode.Err_OnLineTimeNotFenXiang, "在线时间不足30分钟无法分享" },
            { ErrorCode.ERR_LevelIsNotFenXiang, "领取分享奖励需要等级达到10级且在线时间达到30分钟" },
            {
                ErrorCode.ERR_FangChengMi_Tip1,
                "您目前为未成年人账号，已被纳入防沉迷系统。根据国家新闻出版署《关于进一步严格管理切实防止未成年人沉迷网络游戏的通知》，仅每周五、周六、周日和法定节假日每日20时至21时提供1小时网络游戏服务。您今日游戏剩余时间{0}分钟。"
            },
            { ErrorCode.ERR_FangChengMi_Tip2, "您目前为未成年人账号，已被纳入防沉迷系统。根据国家新闻出版署《关于防止未成年人沉迷网络游戏的通知》，您已超出支付上限，无法继续充值。" },
            { ErrorCode.ERR_FangChengMi_Tip3, "您目前为未成年人账号，已被纳入防沉迷系统。根据国家新闻出版署《关于防止未成年人沉迷网络游戏的通知》，本游戏不为未满8周岁的用户提供游戏充值服务。" },
            {
                ErrorCode.ERR_FangChengMi_Tip4,
                "您目前为未成年人账号，已被纳入防沉迷系统。根据国家新闻出版署《关于防止未成年人沉迷网络游戏的通知》，游戏中8周岁以上未满16周岁的用户，单次充值金额不得超过50元人民币，每月充值金额不得超过200元人民币。"
            },
            {
                ErrorCode.ERR_FangChengMi_Tip5,
                "您目前为未成年人账号，已被纳入防沉迷系统。根据国家新闻出版署《关于防止未成年人沉迷网络游戏的通知》，游戏中16周岁以上未满18周岁的用户，单次充值金额不得超过100元人民币，每月充值金额不得超过400元人民币。"
            },
            { ErrorCode.ERR_FangChengMi_Tip6, "您目前为未成年人账号，已被纳入防沉迷系统。根据适龄提示，此时段本游戏将无法为不满12周岁未成年人用户提供任何形式的游戏服务。" },
            {
                ErrorCode.ERR_FangChengMi_Tip7,
                "您目前为未成年人账号，已被纳入防沉迷系统。根据国家新闻出版署《关于进一步严格管理切实防止未成年人沉迷网络游戏的通知》，仅每周五、周六、周日和法定节假日每日20时至21时提供1小时网络游戏服务。"
            },
            { ErrorCode.ERR_TaskCommited, "当前任务奖励已领取" },
            { ErrorCode.ERR_NotFindLevel, "未找到对应关卡" },
            { ErrorCode.ERR_TiLiNoEnough, "体力不足" },
            { ErrorCode.ERR_LevelNotOpen, "请先通关前置关卡" },
            { ErrorCode.ERR_ExpNoEnough, "经验不足" },
            { ErrorCode.ERR_LevelNoEnough, "等级不足" },
            { ErrorCode.ERR_LevelNormalNoPass, "普通关卡未通关" },
            { ErrorCode.ERR_LevelChallengeNoPass, "挑战关卡未通关" },
            { ErrorCode.ERR_NotFindNpc, "任务点不在此地图，请根据指示前往其他地图。" },
            { ErrorCode.ERR_TaskCanNotGet, "未达到领取条件" },
            { ErrorCode.ERR_TaskNoComplete, "请先完成此类任务" },
            { ErrorCode.ERR_TowerOfSealReachTop, "已通关" },
            { ErrorCode.ERR_Challenge_CD, "挑战冷却中" },
            { ErrorCode.ERR_ZhuaBuTimeLimit, "只能抓捕一次" },
            { ErrorCode.ERR_Pet_Hint_1, "宠物星级出错" },
            { ErrorCode.ERR_Pet_UpStar, "宠物星级失败" },
            { ErrorCode.ERR_Pet_UpStage, "宠物进化失败" },
            { ErrorCode.ERR_Pet_AddSkillSame, "具有相同技能，无法使用此道具。" },
            { ErrorCode.ERR_Pet_NoUseItem, "此道具无法应用于宠物身上" },
            { ErrorCode.ERR_PetIsFull, "当前携带的宠物数量已达上限" },
            { ErrorCode.ERR_Pet_Hint_2, "出战宠物不能被融合" },
            { ErrorCode.ERR_Pet_Hint_3, "出战宠物不能散步" },
            { ErrorCode.ERR_Pet_Hint_4, "出战宠物不能分解" },
            { ErrorCode.ERR_Pet_CanNotLock, "小于两技能宠物不能锁定技能" },
            { ErrorCode.ERR_Pet_Dead, "宠物已死亡" },
            { ErrorCode.ERR_ItemOnlyUseMiJing, "该道具只能在宝藏之地使用" },
            { ErrorCode.ERR_ItemOnlyUseOcc, "该道具只有{0}可以使用" },
            { ErrorCode.ERR_Union_Same_Name, "已经存在同名的公会" },
            { ErrorCode.ERR_Union_PeopleMax, "公会成员人数已达上限" },
            { ErrorCode.ERR_PlayerHaveUnion, "玩家已经有公会了" },
            { ErrorCode.ERR_Union_HavKeJi, "只能同时研究一个科技" },
            { ErrorCode.ERR_Union_NotKeJi, "当前没有正在研究的科技" },
            { ErrorCode.ERR_Already_Guess, "已经竞猜该数字" },
            { ErrorCode.ERR_RoleYueKaRepeat, "周卡重复开启" },
            { ErrorCode.ERR_AlreadyFinish, "活动已经结束" },
            { ErrorCode.ERR_MysteryItem_Max, "此道具每日购买次数已达上限" },
            { ErrorCode.ERR_HongBaoTime, "距离上次领取红包在线时间大于30分钟" },
            { ErrorCode.ERR_HongBaoLevel, "需要等级大于12级" },
            { ErrorCode.ERR_SoloNumMax, "竞技场今日挑战次数已达上限" },
            { ErrorCode.ERR_SoloExist, "已存在竞技场匹配列表中!" },
            { ErrorCode.ERR_MapLimit, "当前地图人数已达上限!" },
            { ErrorCode.ERR_TurtleSupport_1, "同账号只能支持一次!" },
            { ErrorCode.ERR_ShangJinNumFull, "今日领取赏金次数已满" },
            { ErrorCode.ERR_TaskLimited, "今日任务次数已满" },
            { ErrorCode.ERR_BattleJoined, "已经参与过战场活动" },
            { ErrorCode.Err_PaiMaiPriceLow, "拍卖行出售价格过低" },
            { ErrorCode.Err_StopPaiMai, "此道具无法在拍卖行中进行出售!" },
            { ErrorCode.Err_Auction_Low, "出价低于其他玩家!" },
            { ErrorCode.Err_Auction_Finish, "竞拍已结束!" },
            { ErrorCode.ERR_Parameter, "参数错误!" },
            { ErrorCode.ERR_HoreseNotFight, "请到主城坐骑训练师选择自己的骑乘坐骑吧" },
            { ErrorCode.ERR_HoreseNotActive, "坐骑未出战" },
            { ErrorCode.ERR_VitalityNotEnoughError, "活力不足" },
            { ErrorCode.Err_TeamDungeonXieZhu, "帮助副本只能创建比自己等级低10级以上的副本" },
            { ErrorCode.ERR_AlreadyReceived, "已经领取过奖励" },
            { ErrorCode.ERR_TitleNoActived, "称号未激活" },
            { ErrorCode.ERR_AlreadyPlant, "土地已经种植了" },
            { ErrorCode.ERR_JiaYuanLevel, "家园等级不足" },
            { ErrorCode.ERR_PeopleNumber, "人口已达上限" },
            { ErrorCode.ERR_JiaYuanSteal, "该作物已达偷取上限" },
            { ErrorCode.ERR_PeopleNoEnough, "购买后人口超过上限" },
            { ErrorCode.ERR_CanNotGather, "未成熟或者收获次数用完，请重登尝试。" },
            { ErrorCode.ERR_PopularizeThe, "相同账号的角色不能互相推广" },
            { ErrorCode.ERR_SerialNoExist, "序列号不存在" },
            { ErrorCode.ERR_PopularizeNot, "被推广人不存在" },
            { ErrorCode.ERR_PopularizeMax, "被推广次数已达上限" },
            { ErrorCode.ERR_ModifyData, "数据异常，请稍后再试。" },
            { ErrorCode.ERR_PackageFrequent, "消息异常，请稍后再试。" },
            { ErrorCode.ERR_PaiMaiBuyMaxPage, "拍卖道具页数已达底部" },
            { ErrorCode.ERR_FenXiangMaxNum, "今日分享次数已达上限，请明日再来。" },
            { ErrorCode.Pre_Condition_Error, "前置条件不足！" },
            { ErrorCode.ERR_TalentNotActivePreId, "未激活前置天赋" },
            { ErrorCode.ERR_TalentPointNot, "天赋点不足" },
            { ErrorCode.ERR_LvNoHigh, "等级不足" },
            { ErrorCode.ERR_SessionDisconnect, "网络已断开" },
            { ErrorCode.ERR_PetMelee_MoLiNoEnough, "魔力不足" },
            { ErrorCode.ERR_PetMelee_PetNumMax, "宠物数量达到上限" },
            { ErrorCode.ERR_PetMelee_MainPetNumMax, "主战宠物数量达到上限" },
            { ErrorCode.ERR_SingleHappy_Fresh, "当空位小于10个时 无法刷新当前掉落" },
            
        };
    }
}
