
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class StartZoneConfig : BeanBase
    {
        public StartZoneConfig()
        {
        }


        public StartZoneConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            DBConnection = _buf.ReadString();
            PhysicZone = _buf.ReadInt();
            DBName = _buf.ReadString();

            PostInit();
        }

        public static StartZoneConfig DeserializeStartZoneConfig(ByteBuf _buf)
        {
            return new StartZoneConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 数据库地址
        /// </summary>
        public string DBConnection;

        /// <summary>
        /// 物理区
        /// </summary>
        public int PhysicZone;

        /// <summary>
        /// 数据库名
        /// </summary>
        public string DBName;


        public const int __ID__ = -457316368;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "DBConnection:" + DBConnection + ","
            + "PhysicZone:" + PhysicZone + ","
            + "DBName:" + DBName + ","
            + "}";
        }

        partial void PostInit();
    }
}

