
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class CellDungeonConfigCategory : Singleton<CellDungeonConfigCategory>, IConfig
    {
        private readonly Dictionary<int, CellDungeonConfig> _dataMap;
        private readonly List<CellDungeonConfig> _dataList;

        public CellDungeonConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, CellDungeonConfig>();
            _dataList = new List<CellDungeonConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                CellDungeonConfig _v;
                _v = global::ET.CellDungeonConfig.DeserializeCellDungeonConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, CellDungeonConfig> DataMap => _dataMap;
        public List<CellDungeonConfig> DataList => _dataList;
        public Dictionary<int, CellDungeonConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public CellDungeonConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public CellDungeonConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

