
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class CellGenerateConfigCategory : Singleton<CellGenerateConfigCategory>, IConfig
    {
        private readonly Dictionary<int, CellGenerateConfig> _dataMap;
        private readonly List<CellGenerateConfig> _dataList;

        public CellGenerateConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, CellGenerateConfig>();
            _dataList = new List<CellGenerateConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                CellGenerateConfig _v;
                _v = global::ET.CellGenerateConfig.DeserializeCellGenerateConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, CellGenerateConfig> DataMap => _dataMap;
        public List<CellGenerateConfig> DataList => _dataList;
        public Dictionary<int, CellGenerateConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public CellGenerateConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public CellGenerateConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

