
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class CellChapterConfigCategory : Singleton<CellChapterConfigCategory>, IConfig
    {
        private readonly Dictionary<int, CellChapterConfig> _dataMap;
        private readonly List<CellChapterConfig> _dataList;

        public CellChapterConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, CellChapterConfig>();
            _dataList = new List<CellChapterConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                CellChapterConfig _v;
                _v = global::ET.CellChapterConfig.DeserializeCellChapterConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, CellChapterConfig> DataMap => _dataMap;
        public List<CellChapterConfig> DataList => _dataList;
        public Dictionary<int, CellChapterConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public CellChapterConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public CellChapterConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

