
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ChengJiuConfig : BeanBase
    {
        public ChengJiuConfig()
        {
        }


        public ChengJiuConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ChengjiuType = _buf.ReadInt();
            ChapterId = _buf.ReadInt();
            Name = _buf.ReadString();
            Icon = _buf.ReadInt();
            RewardNum = _buf.ReadInt();
            TargetType = _buf.ReadInt();
            TargetID = _buf.ReadInt();
            TargetValue = _buf.ReadInt();
            Des = _buf.ReadString();

            PostInit();
        }

        public static ChengJiuConfig DeserializeChengJiuConfig(ByteBuf _buf)
        {
            return new ChengJiuConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 成就类型
        /// </summary>
        public int ChengjiuType;

        /// <summary>
        /// 章节ID
        /// </summary>
        public int ChapterId;

        /// <summary>
        /// 成就名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 称号图片
        /// </summary>
        public int Icon;

        /// <summary>
        /// 奖励成就点数
        /// </summary>
        public int RewardNum;

        /// <summary>
        /// 目标要求类型
        /// </summary>
        public int TargetType;

        /// <summary>
        /// 目标要求值
        /// </summary>
        public int TargetID;

        /// <summary>
        /// 目标要求值
        /// </summary>
        public int TargetValue;

        /// <summary>
        /// 描述
        /// </summary>
        public string Des;


        public const int __ID__ = 1815018431;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ChengjiuType:" + ChengjiuType + ","
            + "ChapterId:" + ChapterId + ","
            + "Name:" + Name + ","
            + "Icon:" + Icon + ","
            + "RewardNum:" + RewardNum + ","
            + "TargetType:" + TargetType + ","
            + "TargetID:" + TargetID + ","
            + "TargetValue:" + TargetValue + ","
            + "Des:" + Des + ","
            + "}";
        }

        partial void PostInit();
    }
}

