
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class DropConfigCategory : Singleton<DropConfigCategory>, IConfig
    {
        private readonly Dictionary<int, DropConfig> _dataMap;
        private readonly List<DropConfig> _dataList;

        public DropConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, DropConfig>();
            _dataList = new List<DropConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                DropConfig _v;
                _v = global::ET.DropConfig.DeserializeDropConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, DropConfig> DataMap => _dataMap;
        public List<DropConfig> DataList => _dataList;
        public Dictionary<int, DropConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public DropConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public DropConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

