
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class DungeonTransferConfig : BeanBase
    {
        public DungeonTransferConfig()
        {
        }


        public DungeonTransferConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            MapID = _buf.ReadInt();
            EnterLv = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); BornPos = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); BornPos[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); Position = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Position[__index0] = __e0;}}

            PostInit();
        }

        public static DungeonTransferConfig DeserializeDungeonTransferConfig(ByteBuf _buf)
        {
            return new DungeonTransferConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名字
        /// </summary>
        public string Name;

        /// <summary>
        /// 地图ID
        /// </summary>
        public int MapID;

        /// <summary>
        /// 进入等级
        /// </summary>
        public int EnterLv;

        /// <summary>
        /// 位置【进入新场景出生点】
        /// </summary>
        public int[] BornPos;

        /// <summary>
        /// 位置[传送门]
        /// </summary>
        public int[] Position;


        public const int __ID__ = -201149369;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "MapID:" + MapID + ","
            + "EnterLv:" + EnterLv + ","
            + "BornPos:" + Luban.StringUtil.CollectionToString(BornPos) + ","
            + "Position:" + Luban.StringUtil.CollectionToString(Position) + ","
            + "}";
        }

        partial void PostInit();
    }
}

