
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class EquipSuitPropertyConfigCategory : Singleton<EquipSuitPropertyConfigCategory>, IConfig
    {
        private readonly Dictionary<int, EquipSuitPropertyConfig> _dataMap;
        private readonly List<EquipSuitPropertyConfig> _dataList;

        public EquipSuitPropertyConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, EquipSuitPropertyConfig>();
            _dataList = new List<EquipSuitPropertyConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                EquipSuitPropertyConfig _v;
                _v = global::ET.EquipSuitPropertyConfig.DeserializeEquipSuitPropertyConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, EquipSuitPropertyConfig> DataMap => _dataMap;
        public List<EquipSuitPropertyConfig> DataList => _dataList;
        public Dictionary<int, EquipSuitPropertyConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public EquipSuitPropertyConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public EquipSuitPropertyConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

