
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class EquipMakeConfig : BeanBase
    {
        public EquipMakeConfig()
        {
        }


        public EquipMakeConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ProficiencyType = _buf.ReadInt();
            MakeItemID = _buf.ReadInt();
            LearnType = _buf.ReadInt();
            LearnLv = _buf.ReadInt();
            LearnGoldValue = _buf.ReadInt();
            CostVitality = _buf.ReadInt();
            LearnNeedItems = _buf.ReadString();
            MakeEquipNum = _buf.ReadInt();
            MakeSuccesPro = _buf.ReadDouble();
            LearnPro = _buf.ReadDouble();
            MakeHintPro = _buf.ReadString();
            MakeLv = _buf.ReadInt();
            MakeLvMax = _buf.ReadInt();
            MakeStar = _buf.ReadInt();
            NeedProficiencyValue = _buf.ReadInt();
            ProficiencyMax = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); ProficiencyValue = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ProficiencyValue[__index0] = __e0;}}
            ProficiencyStartProValue = _buf.ReadDouble();
            ProficiencyProValue = _buf.ReadDouble();
            MakeTime = _buf.ReadInt();
            MakeNeedGold = _buf.ReadInt();
            NeedItems = _buf.ReadString();

            PostInit();
        }

        public static EquipMakeConfig DeserializeEquipMakeConfig(ByteBuf _buf)
        {
            return new EquipMakeConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 制造类型
        /// </summary>
        public int ProficiencyType;

        /// <summary>
        /// 制造装备
        /// </summary>
        public int MakeItemID;

        /// <summary>
        /// 学习类型
        /// </summary>
        public int LearnType;

        /// <summary>
        /// 学习等级
        /// </summary>
        public int LearnLv;

        /// <summary>
        /// 学习消耗金币
        /// </summary>
        public int LearnGoldValue;

        /// <summary>
        /// 消耗活力值
        /// </summary>
        public int CostVitality;

        /// <summary>
        /// 学习需要道具
        /// </summary>
        public string LearnNeedItems;

        /// <summary>
        /// 制造装备数量
        /// </summary>
        public int MakeEquipNum;

        /// <summary>
        /// 制作成功概率
        /// </summary>
        public double MakeSuccesPro;

        /// <summary>
        /// 领悟概率
        /// </summary>
        public double LearnPro;

        /// <summary>
        /// 触发隐藏属性概率
        /// </summary>
        public string MakeHintPro;

        /// <summary>
        /// 制造装备等级
        /// </summary>
        public int MakeLv;

        /// <summary>
        /// 制造装备最大等级
        /// </summary>
        public int MakeLvMax;

        /// <summary>
        /// 制造星级
        /// </summary>
        public int MakeStar;

        /// <summary>
        /// 需要熟练度
        /// </summary>
        public int NeedProficiencyValue;

        /// <summary>
        /// 增长熟练度上限
        /// </summary>
        public int ProficiencyMax;

        /// <summary>
        /// 增长熟练点数
        /// </summary>
        public int[] ProficiencyValue;

        /// <summary>
        /// 熟练度转换概率生效值
        /// </summary>
        public double ProficiencyStartProValue;

        /// <summary>
        /// 熟练点数转换概率
        /// </summary>
        public double ProficiencyProValue;

        /// <summary>
        /// 制造冷却时间
        /// </summary>
        public int MakeTime;

        /// <summary>
        /// 制造消耗金币
        /// </summary>
        public int MakeNeedGold;

        /// <summary>
        /// 需要道具
        /// </summary>
        public string NeedItems;


        public const int __ID__ = -1552725248;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ProficiencyType:" + ProficiencyType + ","
            + "MakeItemID:" + MakeItemID + ","
            + "LearnType:" + LearnType + ","
            + "LearnLv:" + LearnLv + ","
            + "LearnGoldValue:" + LearnGoldValue + ","
            + "CostVitality:" + CostVitality + ","
            + "LearnNeedItems:" + LearnNeedItems + ","
            + "MakeEquipNum:" + MakeEquipNum + ","
            + "MakeSuccesPro:" + MakeSuccesPro + ","
            + "LearnPro:" + LearnPro + ","
            + "MakeHintPro:" + MakeHintPro + ","
            + "MakeLv:" + MakeLv + ","
            + "MakeLvMax:" + MakeLvMax + ","
            + "MakeStar:" + MakeStar + ","
            + "NeedProficiencyValue:" + NeedProficiencyValue + ","
            + "ProficiencyMax:" + ProficiencyMax + ","
            + "ProficiencyValue:" + Luban.StringUtil.CollectionToString(ProficiencyValue) + ","
            + "ProficiencyStartProValue:" + ProficiencyStartProValue + ","
            + "ProficiencyProValue:" + ProficiencyProValue + ","
            + "MakeTime:" + MakeTime + ","
            + "MakeNeedGold:" + MakeNeedGold + ","
            + "NeedItems:" + NeedItems + ","
            + "}";
        }

        partial void PostInit();
    }
}

