
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class EquipQiangHuaConfigCategory : Singleton<EquipQiangHuaConfigCategory>, IConfig
    {
        private readonly Dictionary<int, EquipQiangHuaConfig> _dataMap;
        private readonly List<EquipQiangHuaConfig> _dataList;

        public EquipQiangHuaConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, EquipQiangHuaConfig>();
            _dataList = new List<EquipQiangHuaConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                EquipQiangHuaConfig _v;
                _v = global::ET.EquipQiangHuaConfig.DeserializeEquipQiangHuaConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, EquipQiangHuaConfig> DataMap => _dataMap;
        public List<EquipQiangHuaConfig> DataList => _dataList;
        public Dictionary<int, EquipQiangHuaConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public EquipQiangHuaConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public EquipQiangHuaConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

