
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class FirstWinConfigCategory : Singleton<FirstWinConfigCategory>, IConfig
    {
        private readonly Dictionary<int, FirstWinConfig> _dataMap;
        private readonly List<FirstWinConfig> _dataList;

        public FirstWinConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, FirstWinConfig>();
            _dataList = new List<FirstWinConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                FirstWinConfig _v;
                _v = global::ET.FirstWinConfig.DeserializeFirstWinConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, FirstWinConfig> DataMap => _dataMap;
        public List<FirstWinConfig> DataList => _dataList;
        public Dictionary<int, FirstWinConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public FirstWinConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public FirstWinConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

