
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class GlobalValueConfigCategory : Singleton<GlobalValueConfigCategory>, IConfig
    {
        private readonly Dictionary<int, GlobalValueConfig> _dataMap;
        private readonly List<GlobalValueConfig> _dataList;

        public GlobalValueConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, GlobalValueConfig>();
            _dataList = new List<GlobalValueConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                GlobalValueConfig _v;
                _v = global::ET.GlobalValueConfig.DeserializeGlobalValueConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, GlobalValueConfig> DataMap => _dataMap;
        public List<GlobalValueConfig> DataList => _dataList;
        public Dictionary<int, GlobalValueConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public GlobalValueConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public GlobalValueConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

