
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class GuideConfigCategory : Singleton<GuideConfigCategory>, IConfig
    {
        private readonly Dictionary<int, GuideConfig> _dataMap;
        private readonly List<GuideConfig> _dataList;

        public GuideConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, GuideConfig>();
            _dataList = new List<GuideConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                GuideConfig _v;
                _v = global::ET.GuideConfig.DeserializeGuideConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, GuideConfig> DataMap => _dataMap;
        public List<GuideConfig> DataList => _dataList;
        public Dictionary<int, GuideConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public GuideConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public GuideConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

