
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ItemConfig : BeanBase
    {
        public ItemConfig()
        {
        }


        public ItemConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ItemName = _buf.ReadString();
            Icon = _buf.ReadString();
            ItemModelID = _buf.ReadString();
            ItemQuality = _buf.ReadInt();
            UseLv = _buf.ReadInt();
            UseOcc = _buf.ReadInt();
            ItemType = _buf.ReadInt();
            ItemSubType = _buf.ReadInt();
            EquipType = _buf.ReadInt();
            ItemPileSum = _buf.ReadInt();
            SellMoneyType = _buf.ReadInt();
            SellMoneyValue = _buf.ReadInt();
            ItemEquipID = _buf.ReadInt();
            PetHeXinHeChengID = _buf.ReadInt();
            ItemUsePar = _buf.ReadString();
            SkillID = _buf.ReadString();
            SkillIDIfShow = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); XiLianStone = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); XiLianStone[__index0] = __e0;}}
            HuiShouGetItem = _buf.ReadString();
            ItemDes = _buf.ReadString();
            ItemBlackDes = _buf.ReadString();
            IfAutoUse = _buf.ReadInt();
            IfStopPaiMai = _buf.ReadInt();
            IfLock = _buf.ReadInt();
            DayUseNum = _buf.ReadInt();

            PostInit();
        }

        public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
        {
            return new ItemConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 道具名称
        /// </summary>
        public string ItemName;

        /// <summary>
        /// 道具Icon
        /// </summary>
        public string Icon;

        /// <summary>
        /// 道具模型ID
        /// </summary>
        public string ItemModelID;

        /// <summary>
        /// 道具品质
        /// </summary>
        public int ItemQuality;

        /// <summary>
        /// 使用等级
        /// </summary>
        public int UseLv;

        /// <summary>
        /// 使用职业
        /// </summary>
        public int UseOcc;

        /// <summary>
        /// 道具类型
        /// </summary>
        public int ItemType;

        /// <summary>
        /// 道具子类
        /// </summary>
        public int ItemSubType;

        /// <summary>
        /// 装备类型
        /// </summary>
        public int EquipType;

        /// <summary>
        /// 道具堆叠最大数量
        /// </summary>
        public int ItemPileSum;

        /// <summary>
        /// 出售货币类型
        /// </summary>
        public int SellMoneyType;

        /// <summary>
        /// 出售货币值
        /// </summary>
        public int SellMoneyValue;

        /// <summary>
        /// 装备ID
        /// </summary>
        public int ItemEquipID;

        /// <summary>
        /// 宠物之核合成新道具
        /// </summary>
        public int PetHeXinHeChengID;

        /// <summary>
        /// 道具使用参数 
        /// </summary>
        public string ItemUsePar;

        /// <summary>
        /// 道具技能
        /// </summary>
        public string SkillID;

        /// <summary>
        /// 道具Tips显示技能
        /// </summary>
        public int SkillIDIfShow;

        /// <summary>
        /// 洗练石数量
        /// </summary>
        public int[] XiLianStone;

        /// <summary>
        /// 回收获取物品
        /// </summary>
        public string HuiShouGetItem;

        /// <summary>
        /// 道具描述
        /// </summary>
        public string ItemDes;

        /// <summary>
        /// 道具背景描述
        /// </summary>
        public string ItemBlackDes;

        /// <summary>
        /// 是否自动使用
        /// </summary>
        public int IfAutoUse;

        /// <summary>
        /// 是否禁止拍卖行上架
        /// </summary>
        public int IfStopPaiMai;

        /// <summary>
        /// 获取是否绑定
        /// </summary>
        public int IfLock;

        /// <summary>
        /// 每天使用次数
        /// </summary>
        public int DayUseNum;


        public const int __ID__ = -764023723;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ItemName:" + ItemName + ","
            + "Icon:" + Icon + ","
            + "ItemModelID:" + ItemModelID + ","
            + "ItemQuality:" + ItemQuality + ","
            + "UseLv:" + UseLv + ","
            + "UseOcc:" + UseOcc + ","
            + "ItemType:" + ItemType + ","
            + "ItemSubType:" + ItemSubType + ","
            + "EquipType:" + EquipType + ","
            + "ItemPileSum:" + ItemPileSum + ","
            + "SellMoneyType:" + SellMoneyType + ","
            + "SellMoneyValue:" + SellMoneyValue + ","
            + "ItemEquipID:" + ItemEquipID + ","
            + "PetHeXinHeChengID:" + PetHeXinHeChengID + ","
            + "ItemUsePar:" + ItemUsePar + ","
            + "SkillID:" + SkillID + ","
            + "SkillIDIfShow:" + SkillIDIfShow + ","
            + "XiLianStone:" + Luban.StringUtil.CollectionToString(XiLianStone) + ","
            + "HuiShouGetItem:" + HuiShouGetItem + ","
            + "ItemDes:" + ItemDes + ","
            + "ItemBlackDes:" + ItemBlackDes + ","
            + "IfAutoUse:" + IfAutoUse + ","
            + "IfStopPaiMai:" + IfStopPaiMai + ","
            + "IfLock:" + IfLock + ","
            + "DayUseNum:" + DayUseNum + ","
            + "}";
        }

        partial void PostInit();
    }
}

