
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class LifeShieldConfig : BeanBase
    {
        public LifeShieldConfig()
        {
        }


        public LifeShieldConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ShieldType = _buf.ReadInt();
            ShieldName = _buf.ReadString();
            ShieldLevel = _buf.ReadInt();
            ShieldExp = _buf.ReadInt();
            AddProperty = _buf.ReadString();
            Des = _buf.ReadString();

            PostInit();
        }

        public static LifeShieldConfig DeserializeLifeShieldConfig(ByteBuf _buf)
        {
            return new LifeShieldConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 生命之盾类型
        /// </summary>
        public int ShieldType;

        /// <summary>
        /// 名字
        /// </summary>
        public string ShieldName;

        /// <summary>
        /// 等级
        /// </summary>
        public int ShieldLevel;

        /// <summary>
        /// 生命之盾经验
        /// </summary>
        public int ShieldExp;

        /// <summary>
        /// 额外属性
        /// </summary>
        public string AddProperty;

        /// <summary>
        /// 额外描述
        /// </summary>
        public string Des;


        public const int __ID__ = -1936766649;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ShieldType:" + ShieldType + ","
            + "ShieldName:" + ShieldName + ","
            + "ShieldLevel:" + ShieldLevel + ","
            + "ShieldExp:" + ShieldExp + ","
            + "AddProperty:" + AddProperty + ","
            + "Des:" + Des + ","
            + "}";
        }

        partial void PostInit();
    }
}

