
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MapObjectConfig : BeanBase
    {
        public MapObjectConfig()
        {
        }


        public MapObjectConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            MapConfig = _buf.ReadString();

            PostInit();
        }

        public static MapObjectConfig DeserializeMapObjectConfig(ByteBuf _buf)
        {
            return new MapObjectConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 场景配置
        /// </summary>
        public string MapConfig;


        public const int __ID__ = -1758597443;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MapConfig:" + MapConfig + ","
            + "}";
        }

        partial void PostInit();
    }
}

