
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class MineBattleConfigCategory : Singleton<MineBattleConfigCategory>, IConfig
    {
        private readonly Dictionary<int, MineBattleConfig> _dataMap;
        private readonly List<MineBattleConfig> _dataList;

        public MineBattleConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MineBattleConfig>();
            _dataList = new List<MineBattleConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                MineBattleConfig _v;
                _v = global::ET.MineBattleConfig.DeserializeMineBattleConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, MineBattleConfig> DataMap => _dataMap;
        public List<MineBattleConfig> DataList => _dataList;
        public Dictionary<int, MineBattleConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public MineBattleConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public MineBattleConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

