
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MonsterGroupConfig : BeanBase
    {
        public MonsterGroupConfig()
        {
        }


        public MonsterGroupConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            CreateMonster = _buf.ReadString();

            PostInit();
        }

        public static MonsterGroupConfig DeserializeMonsterGroupConfig(ByteBuf _buf)
        {
            return new MonsterGroupConfig(_buf);
        }

        /// <summary>
        /// id
        /// </summary>
        public int Id;

        /// <summary>
        /// 野怪
        /// </summary>
        public string CreateMonster;


        public const int __ID__ = -1205282169;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "CreateMonster:" + CreateMonster + ","
            + "}";
        }

        partial void PostInit();
    }
}

