
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MonsterConfig : BeanBase
    {
        public MonsterConfig()
        {
        }


        public MonsterConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            MonsterName = _buf.ReadString();
            MonsterType = _buf.ReadInt();
            MonsterSonType = _buf.ReadInt();
            MonsterCamp = _buf.ReadInt();
            MonsterRace = _buf.ReadInt();
            MonsterHeadIcon = _buf.ReadString();
            MonsterModelID = _buf.ReadInt();
            SpiritPro = _buf.ReadDouble();
            SpiritID = _buf.ReadInt();
            Lv = _buf.ReadInt();
            MoveSpeed = _buf.ReadDouble();
            ActDistance = _buf.ReadDouble();
            WalkSpeed = _buf.ReadInt();
            Hp = _buf.ReadInt();
            Act = _buf.ReadInt();
            MageAct = _buf.ReadInt();
            Def = _buf.ReadInt();
            Adf = _buf.ReadInt();
            Cri = _buf.ReadDouble();
            Res = _buf.ReadDouble();
            Hit = _buf.ReadDouble();
            Dodge = _buf.ReadDouble();
            DefAdd = _buf.ReadDouble();
            AdfAdd = _buf.ReadDouble();
            DamgeAdd = _buf.ReadDouble();
            ReviveTime = _buf.ReadDouble();
            PatrolRange = _buf.ReadDouble();
            ChaseRange = _buf.ReadDouble();
            ActRange = _buf.ReadDouble();
            ActInterValTime = _buf.ReadDouble();
            Exp = _buf.ReadInt();
            IfBoss = _buf.ReadInt();
            SelectSize = _buf.ReadDouble();
            DropType = _buf.ReadInt();
            IfDamgeDrop = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); DropID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); DropID[__index0] = __e0;}}
            LvDropID = _buf.ReadString();
            HideDropPro = _buf.ReadDouble();
            MonsterShowPro = _buf.ReadDouble();
            ActSkillID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); SkillID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SkillID[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); Parameter = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Parameter[__index0] = __e0;}}
            AI = _buf.ReadInt();
            AIParameter = _buf.ReadString();
            AIDelay = _buf.ReadInt();
            DeathTime = _buf.ReadInt();
            DeathSkillId = _buf.ReadInt();
            OpenDayMonster = _buf.ReadString();
            ActBasePosiY = _buf.ReadDouble();
            IfHide = _buf.ReadInt();
            RemoveBuff = _buf.ReadInt();
            ModelShowPosi = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); QiYuPetId = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); QiYuPetId[__index0] = __e0;}}

            PostInit();
        }

        public static MonsterConfig DeserializeMonsterConfig(ByteBuf _buf)
        {
            return new MonsterConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 怪物名称
        /// </summary>
        public string MonsterName;

        /// <summary>
        /// 怪物类型
        /// </summary>
        public int MonsterType;

        /// <summary>
        /// 怪物子类
        /// </summary>
        public int MonsterSonType;

        /// <summary>
        /// 阵营
        /// </summary>
        public int MonsterCamp;

        /// <summary>
        /// 怪物种族
        /// </summary>
        public int MonsterRace;

        /// <summary>
        /// 怪物头像
        /// </summary>
        public string MonsterHeadIcon;

        /// <summary>
        /// 怪物模型ID
        /// </summary>
        public int MonsterModelID;

        /// <summary>
        /// 触发精灵概率
        /// </summary>
        public double SpiritPro;

        /// <summary>
        /// 触发精灵ID
        /// </summary>
        public int SpiritID;

        /// <summary>
        /// 怪物等级
        /// </summary>
        public int Lv;

        /// <summary>
        /// 移动速度
        /// </summary>
        public double MoveSpeed;

        /// <summary>
        /// 攻击距离
        /// </summary>
        public double ActDistance;

        /// <summary>
        /// 巡逻速度
        /// </summary>
        public int WalkSpeed;

        /// <summary>
        /// 怪物生命
        /// </summary>
        public int Hp;

        /// <summary>
        /// 攻击
        /// </summary>
        public int Act;

        /// <summary>
        /// 魔法攻击
        /// </summary>
        public int MageAct;

        /// <summary>
        /// 物理防御
        /// </summary>
        public int Def;

        /// <summary>
        /// 魔法防御
        /// </summary>
        public int Adf;

        /// <summary>
        /// 暴击概率
        /// </summary>
        public double Cri;

        /// <summary>
        /// 抗暴概率
        /// </summary>
        public double Res;

        /// <summary>
        /// 附加命中概率
        /// </summary>
        public double Hit;

        /// <summary>
        /// 附加闪避概率
        /// </summary>
        public double Dodge;

        /// <summary>
        /// 怪物物理免伤
        /// </summary>
        public double DefAdd;

        /// <summary>
        /// 怪物魔法免伤
        /// </summary>
        public double AdfAdd;

        /// <summary>
        /// 怪物免伤
        /// </summary>
        public double DamgeAdd;

        /// <summary>
        /// 怪物复活时间
        /// </summary>
        public double ReviveTime;

        /// <summary>
        /// 巡逻范围
        /// </summary>
        public double PatrolRange;

        /// <summary>
        /// 追击范围
        /// </summary>
        public double ChaseRange;

        /// <summary>
        /// 攻击范围
        /// </summary>
        public double ActRange;

        /// <summary>
        /// 攻击间隔时间
        /// </summary>
        public double ActInterValTime;

        /// <summary>
        /// 怪物经验
        /// </summary>
        public int Exp;

        /// <summary>
        /// 是否显示大血条
        /// </summary>
        public int IfBoss;

        /// <summary>
        /// 选中条大小
        /// </summary>
        public double SelectSize;

        /// <summary>
        /// 掉落类型
        /// </summary>
        public int DropType;

        /// <summary>
        /// 造成伤害才有掉落
        /// </summary>
        public int IfDamgeDrop;

        /// <summary>
        /// 掉落ID
        /// </summary>
        public int[] DropID;

        /// <summary>
        /// 分级掉落
        /// </summary>
        public string LvDropID;

        /// <summary>
        /// 极品掉落概率
        /// </summary>
        public double HideDropPro;

        /// <summary>
        /// 怪物出现概率
        /// </summary>
        public double MonsterShowPro;

        /// <summary>
        /// 普通攻击ID
        /// </summary>
        public int ActSkillID;

        /// <summary>
        /// 技能ID
        /// </summary>
        public int[] SkillID;

        /// <summary>
        /// 怪物参数
        /// </summary>
        public int[] Parameter;

        /// <summary>
        /// AI
        /// </summary>
        public int AI;

        /// <summary>
        /// AI相关参数
        /// </summary>
        public string AIParameter;

        /// <summary>
        /// AI延迟时间
        /// </summary>
        public int AIDelay;

        /// <summary>
        /// 怪物出生自动死亡时间
        /// </summary>
        public int DeathTime;

        /// <summary>
        /// 怪物死亡触发技能
        /// </summary>
        public int DeathSkillId;

        /// <summary>
        /// 开服天数刷怪变化
        /// </summary>
        public string OpenDayMonster;

        /// <summary>
        /// 攻击初始位置
        /// </summary>
        public double ActBasePosiY;

        /// <summary>
        /// 是否对敌人隐身
        /// </summary>
        public int IfHide;

        /// <summary>
        /// 是否带走buff
        /// </summary>
        public int RemoveBuff;

        /// <summary>
        /// 怪物显示的位置
        /// </summary>
        public string ModelShowPosi;

        /// <summary>
        /// 奇遇宠物id
        /// </summary>
        public int[] QiYuPetId;


        public const int __ID__ = -55174244;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MonsterName:" + MonsterName + ","
            + "MonsterType:" + MonsterType + ","
            + "MonsterSonType:" + MonsterSonType + ","
            + "MonsterCamp:" + MonsterCamp + ","
            + "MonsterRace:" + MonsterRace + ","
            + "MonsterHeadIcon:" + MonsterHeadIcon + ","
            + "MonsterModelID:" + MonsterModelID + ","
            + "SpiritPro:" + SpiritPro + ","
            + "SpiritID:" + SpiritID + ","
            + "Lv:" + Lv + ","
            + "MoveSpeed:" + MoveSpeed + ","
            + "ActDistance:" + ActDistance + ","
            + "WalkSpeed:" + WalkSpeed + ","
            + "Hp:" + Hp + ","
            + "Act:" + Act + ","
            + "MageAct:" + MageAct + ","
            + "Def:" + Def + ","
            + "Adf:" + Adf + ","
            + "Cri:" + Cri + ","
            + "Res:" + Res + ","
            + "Hit:" + Hit + ","
            + "Dodge:" + Dodge + ","
            + "DefAdd:" + DefAdd + ","
            + "AdfAdd:" + AdfAdd + ","
            + "DamgeAdd:" + DamgeAdd + ","
            + "ReviveTime:" + ReviveTime + ","
            + "PatrolRange:" + PatrolRange + ","
            + "ChaseRange:" + ChaseRange + ","
            + "ActRange:" + ActRange + ","
            + "ActInterValTime:" + ActInterValTime + ","
            + "Exp:" + Exp + ","
            + "IfBoss:" + IfBoss + ","
            + "SelectSize:" + SelectSize + ","
            + "DropType:" + DropType + ","
            + "IfDamgeDrop:" + IfDamgeDrop + ","
            + "DropID:" + Luban.StringUtil.CollectionToString(DropID) + ","
            + "LvDropID:" + LvDropID + ","
            + "HideDropPro:" + HideDropPro + ","
            + "MonsterShowPro:" + MonsterShowPro + ","
            + "ActSkillID:" + ActSkillID + ","
            + "SkillID:" + Luban.StringUtil.CollectionToString(SkillID) + ","
            + "Parameter:" + Luban.StringUtil.CollectionToString(Parameter) + ","
            + "AI:" + AI + ","
            + "AIParameter:" + AIParameter + ","
            + "AIDelay:" + AIDelay + ","
            + "DeathTime:" + DeathTime + ","
            + "DeathSkillId:" + DeathSkillId + ","
            + "OpenDayMonster:" + OpenDayMonster + ","
            + "ActBasePosiY:" + ActBasePosiY + ","
            + "IfHide:" + IfHide + ","
            + "RemoveBuff:" + RemoveBuff + ","
            + "ModelShowPosi:" + ModelShowPosi + ","
            + "QiYuPetId:" + Luban.StringUtil.CollectionToString(QiYuPetId) + ","
            + "}";
        }

        partial void PostInit();
    }
}

