
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class MysteryConfigCategory : Singleton<MysteryConfigCategory>, IConfig
    {
        private readonly Dictionary<int, MysteryConfig> _dataMap;
        private readonly List<MysteryConfig> _dataList;

        public MysteryConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MysteryConfig>();
            _dataList = new List<MysteryConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                MysteryConfig _v;
                _v = global::ET.MysteryConfig.DeserializeMysteryConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, MysteryConfig> DataMap => _dataMap;
        public List<MysteryConfig> DataList => _dataList;
        public Dictionary<int, MysteryConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public MysteryConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public MysteryConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

