
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class NpcConfigCategory : Singleton<NpcConfigCategory>, IConfig
    {
        private readonly Dictionary<int, NpcConfig> _dataMap;
        private readonly List<NpcConfig> _dataList;

        public NpcConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, NpcConfig>();
            _dataList = new List<NpcConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                NpcConfig _v;
                _v = global::ET.NpcConfig.DeserializeNpcConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, NpcConfig> DataMap => _dataMap;
        public List<NpcConfig> DataList => _dataList;
        public Dictionary<int, NpcConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public NpcConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public NpcConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

