
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class OccupationJueXingConfigCategory : Singleton<OccupationJueXingConfigCategory>, IConfig
    {
        private readonly Dictionary<int, OccupationJueXingConfig> _dataMap;
        private readonly List<OccupationJueXingConfig> _dataList;

        public OccupationJueXingConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, OccupationJueXingConfig>();
            _dataList = new List<OccupationJueXingConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                OccupationJueXingConfig _v;
                _v = global::ET.OccupationJueXingConfig.DeserializeOccupationJueXingConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, OccupationJueXingConfig> DataMap => _dataMap;
        public List<OccupationJueXingConfig> DataList => _dataList;
        public Dictionary<int, OccupationJueXingConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public OccupationJueXingConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public OccupationJueXingConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

