
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class OccupationJueXingConfig : BeanBase
    {
        public OccupationJueXingConfig()
        {
        }


        public OccupationJueXingConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            costExp = _buf.ReadInt();
            costGold = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); Pre_Condition = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Pre_Condition[__index0] = __e0;}}
            costItem = _buf.ReadString();

            PostInit();
        }

        public static OccupationJueXingConfig DeserializeOccupationJueXingConfig(ByteBuf _buf)
        {
            return new OccupationJueXingConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 觉醒经验
        /// </summary>
        public int costExp;

        /// <summary>
        /// 觉醒金币
        /// </summary>
        public int costGold;

        /// <summary>
        /// 前置技能
        /// </summary>
        public int[] Pre_Condition;

        /// <summary>
        /// 消耗道具
        /// </summary>
        public string costItem;


        public const int __ID__ = -1814817605;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "costExp:" + costExp + ","
            + "costGold:" + costGold + ","
            + "Pre_Condition:" + Luban.StringUtil.CollectionToString(Pre_Condition) + ","
            + "costItem:" + costItem + ","
            + "}";
        }

        partial void PostInit();
    }
}

