
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PetSkinConfig : BeanBase
    {
        public PetSkinConfig()
        {
        }


        public PetSkinConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            IconID = _buf.ReadInt();
            SkinID = _buf.ReadInt();
            PripertySet = _buf.ReadString();
            PripertyShow = _buf.ReadString();

            PostInit();
        }

        public static PetSkinConfig DeserializePetSkinConfig(ByteBuf _buf)
        {
            return new PetSkinConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 图标图标
        /// </summary>
        public int IconID;

        /// <summary>
        /// 模型ID
        /// </summary>
        public int SkinID;

        /// <summary>
        /// 激活属性(暂时不用)
        /// </summary>
        public string PripertySet;

        /// <summary>
        /// 激活属性描述
        /// </summary>
        public string PripertyShow;


        public const int __ID__ = 83928446;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "IconID:" + IconID + ","
            + "SkinID:" + SkinID + ","
            + "PripertySet:" + PripertySet + ","
            + "PripertyShow:" + PripertyShow + ","
            + "}";
        }

        partial void PostInit();
    }
}

