
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class PetZhuangJiaConfigCategory : Singleton<PetZhuangJiaConfigCategory>, IConfig
    {
        private readonly Dictionary<int, PetZhuangJiaConfig> _dataMap;
        private readonly List<PetZhuangJiaConfig> _dataList;

        public PetZhuangJiaConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, PetZhuangJiaConfig>();
            _dataList = new List<PetZhuangJiaConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                PetZhuangJiaConfig _v;
                _v = global::ET.PetZhuangJiaConfig.DeserializePetZhuangJiaConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, PetZhuangJiaConfig> DataMap => _dataMap;
        public List<PetZhuangJiaConfig> DataList => _dataList;
        public Dictionary<int, PetZhuangJiaConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public PetZhuangJiaConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public PetZhuangJiaConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

