
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class RobotConfig : BeanBase
    {
        public RobotConfig()
        {
        }


        public RobotConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Level = _buf.ReadInt();
            Occ = _buf.ReadInt();
            OccTwo = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); EquipList = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); EquipList[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); PointList = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); PointList[__index0] = __e0;}}
            Behaviour = _buf.ReadInt();
            BehaviourID = _buf.ReadInt();
            AIParameter = _buf.ReadString();

            PostInit();
        }

        public static RobotConfig DeserializeRobotConfig(ByteBuf _buf)
        {
            return new RobotConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 等级
        /// </summary>
        public int Level;

        /// <summary>
        /// 第一职业
        /// </summary>
        public int Occ;

        /// <summary>
        /// 第二职业
        /// </summary>
        public int OccTwo;

        /// <summary>
        /// 装备
        /// </summary>
        public int[] EquipList;

        /// <summary>
        /// 属性点
        /// </summary>
        public int[] PointList;

        /// <summary>
        /// 行为
        /// </summary>
        public int Behaviour;

        /// <summary>
        /// 行为ID
        /// </summary>
        public int BehaviourID;

        /// <summary>
        /// 参数
        /// </summary>
        public string AIParameter;


        public const int __ID__ = -622491092;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Level:" + Level + ","
            + "Occ:" + Occ + ","
            + "OccTwo:" + OccTwo + ","
            + "EquipList:" + Luban.StringUtil.CollectionToString(EquipList) + ","
            + "PointList:" + Luban.StringUtil.CollectionToString(PointList) + ","
            + "Behaviour:" + Behaviour + ","
            + "BehaviourID:" + BehaviourID + ","
            + "AIParameter:" + AIParameter + ","
            + "}";
        }

        partial void PostInit();
    }
}

