
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class SceneConfigCategory : Singleton<SceneConfigCategory>, IConfig
    {
        private readonly Dictionary<int, SceneConfig> _dataMap;
        private readonly List<SceneConfig> _dataList;

        public SceneConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SceneConfig>();
            _dataList = new List<SceneConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SceneConfig _v;
                _v = global::ET.SceneConfig.DeserializeSceneConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SceneConfig> DataMap => _dataMap;
        public List<SceneConfig> DataList => _dataList;
        public Dictionary<int, SceneConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public SceneConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public SceneConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

