
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class SeasonJingHeConfigCategory : Singleton<SeasonJingHeConfigCategory>, IConfig
    {
        private readonly Dictionary<int, SeasonJingHeConfig> _dataMap;
        private readonly List<SeasonJingHeConfig> _dataList;

        public SeasonJingHeConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SeasonJingHeConfig>();
            _dataList = new List<SeasonJingHeConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SeasonJingHeConfig _v;
                _v = global::ET.SeasonJingHeConfig.DeserializeSeasonJingHeConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SeasonJingHeConfig> DataMap => _dataMap;
        public List<SeasonJingHeConfig> DataList => _dataList;
        public Dictionary<int, SeasonJingHeConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public SeasonJingHeConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public SeasonJingHeConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

