
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class SeasonLevelConfigCategory : Singleton<SeasonLevelConfigCategory>, IConfig
    {
        private readonly Dictionary<int, SeasonLevelConfig> _dataMap;
        private readonly List<SeasonLevelConfig> _dataList;

        public SeasonLevelConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SeasonLevelConfig>();
            _dataList = new List<SeasonLevelConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SeasonLevelConfig _v;
                _v = global::ET.SeasonLevelConfig.DeserializeSeasonLevelConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SeasonLevelConfig> DataMap => _dataMap;
        public List<SeasonLevelConfig> DataList => _dataList;
        public Dictionary<int, SeasonLevelConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public SeasonLevelConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public SeasonLevelConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

