
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ShouJiItemConfig : BeanBase
    {
        public ShouJiItemConfig()
        {
        }


        public ShouJiItemConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            NextID = _buf.ReadInt();
            ItemID = _buf.ReadInt();
            StartNum = _buf.ReadInt();
            Chap = _buf.ReadInt();
            StartType = _buf.ReadInt();
            AcitveNum = _buf.ReadInt();
            AddPropreListStr = _buf.ReadString();

            PostInit();
        }

        public static ShouJiItemConfig DeserializeShouJiItemConfig(ByteBuf _buf)
        {
            return new ShouJiItemConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 下一个道具ID
        /// </summary>
        public int NextID;

        /// <summary>
        /// 道具ID
        /// </summary>
        public int ItemID;

        /// <summary>
        /// 道具星数
        /// </summary>
        public int StartNum;

        /// <summary>
        /// 章节
        /// </summary>
        public int Chap;

        /// <summary>
        /// 收集类型
        /// </summary>
        public int StartType;

        /// <summary>
        /// 激活数量
        /// </summary>
        public int AcitveNum;

        /// <summary>
        /// 附加属性
        /// </summary>
        public string AddPropreListStr;


        public const int __ID__ = -1307080305;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "NextID:" + NextID + ","
            + "ItemID:" + ItemID + ","
            + "StartNum:" + StartNum + ","
            + "Chap:" + Chap + ","
            + "StartType:" + StartType + ","
            + "AcitveNum:" + AcitveNum + ","
            + "AddPropreListStr:" + AddPropreListStr + ","
            + "}";
        }

        partial void PostInit();
    }
}

