
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class SkillSocketConfigCategory : Singleton<SkillSocketConfigCategory>, IConfig
    {
        private readonly Dictionary<int, SkillSocketConfig> _dataMap;
        private readonly List<SkillSocketConfig> _dataList;

        public SkillSocketConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SkillSocketConfig>();
            _dataList = new List<SkillSocketConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SkillSocketConfig _v;
                _v = global::ET.SkillSocketConfig.DeserializeSkillSocketConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SkillSocketConfig> DataMap => _dataMap;
        public List<SkillSocketConfig> DataList => _dataList;
        public Dictionary<int, SkillSocketConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public SkillSocketConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public SkillSocketConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

