
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SkillWeaponConfig : BeanBase
    {
        public SkillWeaponConfig()
        {
        }


        public SkillWeaponConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            InitSkillID = _buf.ReadInt();
            InitSkillID_1 = _buf.ReadInt();
            InitSkillID_2 = _buf.ReadInt();
            InitSkillID_3 = _buf.ReadInt();
            InitSkillID_4 = _buf.ReadInt();
            InitSkillID_5 = _buf.ReadInt();

            PostInit();
        }

        public static SkillWeaponConfig DeserializeSkillWeaponConfig(ByteBuf _buf)
        {
            return new SkillWeaponConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 技能名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 默认技能ID
        /// </summary>
        public int InitSkillID;

        /// <summary>
        /// 剑武器技能
        /// </summary>
        public int InitSkillID_1;

        /// <summary>
        /// 刀武器技能
        /// </summary>
        public int InitSkillID_2;

        /// <summary>
        /// 法杖
        /// </summary>
        public int InitSkillID_3;

        /// <summary>
        /// 魔法书
        /// </summary>
        public int InitSkillID_4;

        /// <summary>
        /// 弓箭
        /// </summary>
        public int InitSkillID_5;


        public const int __ID__ = 980654415;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "InitSkillID:" + InitSkillID + ","
            + "InitSkillID_1:" + InitSkillID_1 + ","
            + "InitSkillID_2:" + InitSkillID_2 + ","
            + "InitSkillID_3:" + InitSkillID_3 + ","
            + "InitSkillID_4:" + InitSkillID_4 + ","
            + "InitSkillID_5:" + InitSkillID_5 + ","
            + "}";
        }

        partial void PostInit();
    }
}

