
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class SkillAugmentOptionsConfigCategory : Singleton<SkillAugmentOptionsConfigCategory>, IConfig
    {
        private readonly Dictionary<int, SkillAugmentOptionsConfig> _dataMap;
        private readonly List<SkillAugmentOptionsConfig> _dataList;

        public SkillAugmentOptionsConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SkillAugmentOptionsConfig>();
            _dataList = new List<SkillAugmentOptionsConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SkillAugmentOptionsConfig _v;
                _v = global::ET.SkillAugmentOptionsConfig.DeserializeSkillAugmentOptionsConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SkillAugmentOptionsConfig> DataMap => _dataMap;
        public List<SkillAugmentOptionsConfig> DataList => _dataList;
        public Dictionary<int, SkillAugmentOptionsConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public SkillAugmentOptionsConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public SkillAugmentOptionsConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

