
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SkillAugmentConfig : BeanBase
    {
        public SkillAugmentConfig()
        {
        }


        public SkillAugmentConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            AddPropreListStr = _buf.ReadString();

            PostInit();
        }

        public static SkillAugmentConfig DeserializeSkillAugmentConfig(ByteBuf _buf)
        {
            return new SkillAugmentConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 附加
        /// </summary>
        public string AddPropreListStr;


        public const int __ID__ = -1162302846;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "AddPropreListStr:" + AddPropreListStr + ","
            + "}";
        }

        partial void PostInit();
    }
}

