
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TowerConfig : BeanBase
    {
        public TowerConfig()
        {
        }


        public TowerConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            MapType = _buf.ReadInt();
            CengNum = _buf.ReadInt();
            MonsterSet = _buf.ReadString();
            NextTime = _buf.ReadInt();
            DropShow = _buf.ReadString();

            PostInit();
        }

        public static TowerConfig DeserializeTowerConfig(ByteBuf _buf)
        {
            return new TowerConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名字
        /// </summary>
        public string Name;

        /// <summary>
        /// 地图类型
        /// </summary>
        public int MapType;

        /// <summary>
        /// 层数
        /// </summary>
        public int CengNum;

        /// <summary>
        /// 出现怪物
        /// </summary>
        public string MonsterSet;

        /// <summary>
        /// 强制刷新下一波时间
        /// </summary>
        public int NextTime;

        /// <summary>
        /// 掉落展示
        /// </summary>
        public string DropShow;


        public const int __ID__ = -1246506101;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "MapType:" + MapType + ","
            + "CengNum:" + CengNum + ","
            + "MonsterSet:" + MonsterSet + ","
            + "NextTime:" + NextTime + ","
            + "DropShow:" + DropShow + ","
            + "}";
        }

        partial void PostInit();
    }
}

