
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class TowerConfigCategory : Singleton<TowerConfigCategory>, IConfig
    {
        private readonly Dictionary<int, TowerConfig> _dataMap;
        private readonly List<TowerConfig> _dataList;

        public TowerConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TowerConfig>();
            _dataList = new List<TowerConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TowerConfig _v;
                _v = global::ET.TowerConfig.DeserializeTowerConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TowerConfig> DataMap => _dataMap;
        public List<TowerConfig> DataList => _dataList;
        public Dictionary<int, TowerConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public TowerConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TowerConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

