
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ZuoQiShowConfigCategory : Singleton<ZuoQiShowConfigCategory>, IConfig
    {
        private readonly Dictionary<int, ZuoQiShowConfig> _dataMap;
        private readonly List<ZuoQiShowConfig> _dataList;

        public ZuoQiShowConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ZuoQiShowConfig>();
            _dataList = new List<ZuoQiShowConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ZuoQiShowConfig _v;
                _v = global::ET.ZuoQiShowConfig.DeserializeZuoQiShowConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ZuoQiShowConfig> DataMap => _dataMap;
        public List<ZuoQiShowConfig> DataList => _dataList;
        public Dictionary<int, ZuoQiShowConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public ZuoQiShowConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public ZuoQiShowConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

