
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ActivityConfigCategory : Singleton<ActivityConfigCategory>, IConfig
    {
        private readonly Dictionary<int, ActivityConfig> _dataMap;
        private readonly List<ActivityConfig> _dataList;

        public ActivityConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ActivityConfig>();
            _dataList = new List<ActivityConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ActivityConfig _v;
                _v = global::ET.ActivityConfig.DeserializeActivityConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ActivityConfig> DataMap => _dataMap;
        public List<ActivityConfig> DataList => _dataList;
        public Dictionary<int, ActivityConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public ActivityConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public ActivityConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

