
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BattleSummonConfig : BeanBase
    {
        public BattleSummonConfig()
        {
        }


        public BattleSummonConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ItemName = _buf.ReadString();
            SceneId = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); MonsterIds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); MonsterIds[__index0] = __e0;}}
            MonsterNumber = _buf.ReadInt();
            RenKouNumber = _buf.ReadInt();
            CostGold = _buf.ReadInt();
            FreeResetTime = _buf.ReadInt();

            PostInit();
        }

        public static BattleSummonConfig DeserializeBattleSummonConfig(ByteBuf _buf)
        {
            return new BattleSummonConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 士兵名字
        /// </summary>
        public string ItemName;

        /// <summary>
        /// 战场ID
        /// </summary>
        public int SceneId;

        /// <summary>
        /// 士兵Id
        /// </summary>
        public int[] MonsterIds;

        /// <summary>
        /// 士兵数量
        /// </summary>
        public int MonsterNumber;

        /// <summary>
        /// 人口数量
        /// </summary>
        public int RenKouNumber;

        /// <summary>
        /// 消耗金币
        /// </summary>
        public int CostGold;

        /// <summary>
        /// 免费重置时间(s)
        /// </summary>
        public int FreeResetTime;


        public const int __ID__ = 2088489083;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ItemName:" + ItemName + ","
            + "SceneId:" + SceneId + ","
            + "MonsterIds:" + Luban.StringUtil.CollectionToString(MonsterIds) + ","
            + "MonsterNumber:" + MonsterNumber + ","
            + "RenKouNumber:" + RenKouNumber + ","
            + "CostGold:" + CostGold + ","
            + "FreeResetTime:" + FreeResetTime + ","
            + "}";
        }

        partial void PostInit();
    }
}

