
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class CampFuLiConfigCategory : Singleton<CampFuLiConfigCategory>, IConfig
    {
        private readonly Dictionary<int, CampFuLiConfig> _dataMap;
        private readonly List<CampFuLiConfig> _dataList;

        public CampFuLiConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, CampFuLiConfig>();
            _dataList = new List<CampFuLiConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                CampFuLiConfig _v;
                _v = global::ET.CampFuLiConfig.DeserializeCampFuLiConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, CampFuLiConfig> DataMap => _dataMap;
        public List<CampFuLiConfig> DataList => _dataList;
        public Dictionary<int, CampFuLiConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public CampFuLiConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public CampFuLiConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

