
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CellDungeonConfig : BeanBase
    {
        public CellDungeonConfig()
        {
        }


        public CellDungeonConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Type = _buf.ReadInt();
            MapID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); NpcList = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); NpcList[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); BornPosLeft = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); BornPosLeft[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); BornPosUp = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); BornPosUp[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); BornPosDwon = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); BornPosDwon[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); BornPosRight = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); BornPosRight[__index0] = __e0;}}
            TransmitPosi = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); CreateMonster = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); CreateMonster[__index0] = __e0;}}
            CreateScenceMonsterPro = _buf.ReadString();
            CreateScenceMonster = _buf.ReadString();

            PostInit();
        }

        public static CellDungeonConfig DeserializeCellDungeonConfig(ByteBuf _buf)
        {
            return new CellDungeonConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 关卡名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 地块类型
        /// </summary>
        public int Type;

        /// <summary>
        /// 地图ID
        /// </summary>
        public int MapID;

        /// <summary>
        /// NPC
        /// </summary>
        public int[] NpcList;

        /// <summary>
        /// 出生点
        /// </summary>
        public int[] BornPosLeft;

        /// <summary>
        /// 出生点
        /// </summary>
        public int[] BornPosUp;

        /// <summary>
        /// 出生点
        /// </summary>
        public int[] BornPosDwon;

        /// <summary>
        /// 出生点
        /// </summary>
        public int[] BornPosRight;

        /// <summary>
        /// 传送门坐标
        /// </summary>
        public string TransmitPosi;

        /// <summary>
        /// 怪物生成坐标点
        /// </summary>
        public int[] CreateMonster;

        /// <summary>
        /// 特殊怪
        /// </summary>
        public string CreateScenceMonsterPro;

        /// <summary>
        /// 特殊怪
        /// </summary>
        public string CreateScenceMonster;


        public const int __ID__ = 757550138;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Type:" + Type + ","
            + "MapID:" + MapID + ","
            + "NpcList:" + Luban.StringUtil.CollectionToString(NpcList) + ","
            + "BornPosLeft:" + Luban.StringUtil.CollectionToString(BornPosLeft) + ","
            + "BornPosUp:" + Luban.StringUtil.CollectionToString(BornPosUp) + ","
            + "BornPosDwon:" + Luban.StringUtil.CollectionToString(BornPosDwon) + ","
            + "BornPosRight:" + Luban.StringUtil.CollectionToString(BornPosRight) + ","
            + "TransmitPosi:" + TransmitPosi + ","
            + "CreateMonster:" + Luban.StringUtil.CollectionToString(CreateMonster) + ","
            + "CreateScenceMonsterPro:" + CreateScenceMonsterPro + ","
            + "CreateScenceMonster:" + CreateScenceMonster + ","
            + "}";
        }

        partial void PostInit();
    }
}

