
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CellGenerateConfig : BeanBase
    {
        public CellGenerateConfig()
        {
        }


        public CellGenerateConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            MapType = _buf.ReadInt();
            ChapterName = _buf.ReadString();
            Music = _buf.ReadString();
            LoadingRes = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); InitSize = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); InitSize[__index0] = __e0;}}
            StartArea = _buf.ReadInt();
            EndArea = _buf.ReadInt();
            StopArea = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); SpecialRoomPro = new double[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { double __e0;__e0 = _buf.ReadDouble(); SpecialRoomPro[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); SpecialRoom = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SpecialRoom[__index0] = __e0;}}
            StopAreaNum = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); RandomArea = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); RandomArea[__index0] = __e0;}}
            EnterLv = _buf.ReadInt();
            BossIcon = _buf.ReadInt();
            ChapterDes = _buf.ReadString();
            RewardExp = _buf.ReadInt();
            RewardGold = _buf.ReadInt();
            BoxDropID = _buf.ReadInt();
            Icon = _buf.ReadString();
            BossId = _buf.ReadInt();
            RewardShow = _buf.ReadString();

            PostInit();
        }

        public static CellGenerateConfig DeserializeCellGenerateConfig(ByteBuf _buf)
        {
            return new CellGenerateConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 地图类型
        /// </summary>
        public int MapType;

        /// <summary>
        /// 章节名称
        /// </summary>
        public string ChapterName;

        /// <summary>
        /// 音乐
        /// </summary>
        public string Music;

        /// <summary>
        /// loading图
        /// </summary>
        public string LoadingRes;

        /// <summary>
        /// 生成范围
        /// </summary>
        public int[] InitSize;

        /// <summary>
        /// 起始地块
        /// </summary>
        public int StartArea;

        /// <summary>
        /// 终点地块
        /// </summary>
        public int EndArea;

        /// <summary>
        /// 禁止通行地块
        /// </summary>
        public int StopArea;

        /// <summary>
        /// 奇遇房间概率
        /// </summary>
        public double[] SpecialRoomPro;

        /// <summary>
        /// 奇遇房间
        /// </summary>
        public int[] SpecialRoom;

        /// <summary>
        /// 禁止通行地块
        /// </summary>
        public int StopAreaNum;

        /// <summary>
        /// 随机地块
        /// </summary>
        public int[] RandomArea;

        /// <summary>
        /// 进入等级限制
        /// </summary>
        public int EnterLv;

        /// <summary>
        /// 章节BossIcon
        /// </summary>
        public int BossIcon;

        /// <summary>
        /// 章节文本描述
        /// </summary>
        public string ChapterDes;

        /// <summary>
        ///  通关经验奖励
        /// </summary>
        public int RewardExp;

        /// <summary>
        /// 通关金币奖励
        /// </summary>
        public int RewardGold;

        /// <summary>
        /// 翻卡掉落ID
        /// </summary>
        public int BoxDropID;

        /// <summary>
        /// 翻卡掉落ID
        /// </summary>
        public string Icon;

        /// <summary>
        /// 章节BossId
        /// </summary>
        public int BossId;

        /// <summary>
        /// 奖励展示
        /// </summary>
        public string RewardShow;


        public const int __ID__ = -2110400711;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MapType:" + MapType + ","
            + "ChapterName:" + ChapterName + ","
            + "Music:" + Music + ","
            + "LoadingRes:" + LoadingRes + ","
            + "InitSize:" + Luban.StringUtil.CollectionToString(InitSize) + ","
            + "StartArea:" + StartArea + ","
            + "EndArea:" + EndArea + ","
            + "StopArea:" + StopArea + ","
            + "SpecialRoomPro:" + Luban.StringUtil.CollectionToString(SpecialRoomPro) + ","
            + "SpecialRoom:" + Luban.StringUtil.CollectionToString(SpecialRoom) + ","
            + "StopAreaNum:" + StopAreaNum + ","
            + "RandomArea:" + Luban.StringUtil.CollectionToString(RandomArea) + ","
            + "EnterLv:" + EnterLv + ","
            + "BossIcon:" + BossIcon + ","
            + "ChapterDes:" + ChapterDes + ","
            + "RewardExp:" + RewardExp + ","
            + "RewardGold:" + RewardGold + ","
            + "BoxDropID:" + BoxDropID + ","
            + "Icon:" + Icon + ","
            + "BossId:" + BossId + ","
            + "RewardShow:" + RewardShow + ","
            + "}";
        }

        partial void PostInit();
    }
}

