
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ChengJiuConfigCategory : Singleton<ChengJiuConfigCategory>, IConfig
    {
        private readonly Dictionary<int, ChengJiuConfig> _dataMap;
        private readonly List<ChengJiuConfig> _dataList;

        public ChengJiuConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ChengJiuConfig>();
            _dataList = new List<ChengJiuConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ChengJiuConfig _v;
                _v = global::ET.ChengJiuConfig.DeserializeChengJiuConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ChengJiuConfig> DataMap => _dataMap;
        public List<ChengJiuConfig> DataList => _dataList;
        public Dictionary<int, ChengJiuConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public ChengJiuConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public ChengJiuConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

