
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class DropConfig : BeanBase
    {
        public DropConfig()
        {
        }


        public DropConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            DropType = _buf.ReadInt();
            DropLimit = _buf.ReadInt();
            ifEnterBag = _buf.ReadInt();
            DropSonID = _buf.ReadInt();
            DropChance1 = _buf.ReadInt();
            DropItemID1 = _buf.ReadInt();
            DropItemMinNum1 = _buf.ReadInt();
            DropItemMaxNum1 = _buf.ReadInt();
            DropChance2 = _buf.ReadInt();
            DropItemID2 = _buf.ReadInt();
            DropItemMinNum2 = _buf.ReadInt();
            DropItemMaxNum2 = _buf.ReadInt();
            DropChance3 = _buf.ReadInt();
            DropItemID3 = _buf.ReadInt();
            DropItemMinNum3 = _buf.ReadInt();
            DropItemMaxNum3 = _buf.ReadInt();
            DropChance4 = _buf.ReadInt();
            DropItemID4 = _buf.ReadInt();
            DropItemMinNum4 = _buf.ReadInt();
            DropItemMaxNum4 = _buf.ReadInt();
            DropChance5 = _buf.ReadInt();
            DropItemID5 = _buf.ReadInt();
            DropItemMinNum5 = _buf.ReadInt();
            DropItemMaxNum5 = _buf.ReadInt();
            DropChance6 = _buf.ReadInt();
            DropItemID6 = _buf.ReadInt();
            DropItemMinNum6 = _buf.ReadInt();
            DropItemMaxNum6 = _buf.ReadInt();
            DropChance7 = _buf.ReadInt();
            DropItemID7 = _buf.ReadInt();
            DropItemMinNum7 = _buf.ReadInt();
            DropItemMaxNum7 = _buf.ReadInt();
            DropChance8 = _buf.ReadInt();
            DropItemID8 = _buf.ReadInt();
            DropItemMinNum8 = _buf.ReadInt();
            DropItemMaxNum8 = _buf.ReadInt();
            DropChance9 = _buf.ReadInt();
            DropItemID9 = _buf.ReadInt();
            DropItemMinNum9 = _buf.ReadInt();
            DropItemMaxNum9 = _buf.ReadInt();
            DropChance10 = _buf.ReadInt();
            DropItemID10 = _buf.ReadInt();
            DropItemMinNum10 = _buf.ReadInt();
            DropItemMaxNum10 = _buf.ReadInt();

            PostInit();
        }

        public static DropConfig DeserializeDropConfig(ByteBuf _buf)
        {
            return new DropConfig(_buf);
        }

        /// <summary>
        /// id
        /// </summary>
        public int Id;

        /// <summary>
        /// 掉落类型
        /// </summary>
        public int DropType;

        /// <summary>
        /// 掉落限制
        /// </summary>
        public int DropLimit;

        /// <summary>
        /// 是否直接进入背包
        /// </summary>
        public int ifEnterBag;

        /// <summary>
        /// 继承掉落ID
        /// </summary>
        public int DropSonID;

        /// <summary>
        /// 掉落道具1概率
        /// </summary>
        public int DropChance1;

        /// <summary>
        /// 掉落道具1ID
        /// </summary>
        public int DropItemID1;

        /// <summary>
        /// 掉落道具1最小数量
        /// </summary>
        public int DropItemMinNum1;

        /// <summary>
        /// 掉落道具1最大数量
        /// </summary>
        public int DropItemMaxNum1;

        /// <summary>
        /// 掉落道具2概率
        /// </summary>
        public int DropChance2;

        /// <summary>
        /// 掉落道具2ID
        /// </summary>
        public int DropItemID2;

        /// <summary>
        /// 掉落道具2最小数量
        /// </summary>
        public int DropItemMinNum2;

        /// <summary>
        /// 掉落道具2最大数量
        /// </summary>
        public int DropItemMaxNum2;

        /// <summary>
        /// 掉落道具3概率
        /// </summary>
        public int DropChance3;

        /// <summary>
        /// 掉落道具3ID
        /// </summary>
        public int DropItemID3;

        /// <summary>
        /// 掉落道具3最小数量
        /// </summary>
        public int DropItemMinNum3;

        /// <summary>
        /// 掉落道具3最大数量
        /// </summary>
        public int DropItemMaxNum3;

        /// <summary>
        /// 掉落道具4概率
        /// </summary>
        public int DropChance4;

        /// <summary>
        /// 掉落道4ID
        /// </summary>
        public int DropItemID4;

        /// <summary>
        /// 掉落道具4最小数量
        /// </summary>
        public int DropItemMinNum4;

        /// <summary>
        /// 掉落道具4最大数量
        /// </summary>
        public int DropItemMaxNum4;

        /// <summary>
        /// 掉落道具5概率
        /// </summary>
        public int DropChance5;

        /// <summary>
        /// 掉落道具5ID
        /// </summary>
        public int DropItemID5;

        /// <summary>
        /// 掉落道具5最小数量
        /// </summary>
        public int DropItemMinNum5;

        /// <summary>
        /// 掉落道具5最大数量
        /// </summary>
        public int DropItemMaxNum5;

        /// <summary>
        /// 掉落道具6概率
        /// </summary>
        public int DropChance6;

        /// <summary>
        /// 掉落道具6ID
        /// </summary>
        public int DropItemID6;

        /// <summary>
        /// 掉落道具6最小数量
        /// </summary>
        public int DropItemMinNum6;

        /// <summary>
        /// 掉落道具6最大数量
        /// </summary>
        public int DropItemMaxNum6;

        /// <summary>
        /// 掉落道具7概率
        /// </summary>
        public int DropChance7;

        /// <summary>
        /// 掉落道具7ID
        /// </summary>
        public int DropItemID7;

        /// <summary>
        /// 掉落道具7最小数量
        /// </summary>
        public int DropItemMinNum7;

        /// <summary>
        /// 掉落道具7最大数量
        /// </summary>
        public int DropItemMaxNum7;

        /// <summary>
        /// 掉落道具8概率
        /// </summary>
        public int DropChance8;

        /// <summary>
        /// 掉落道具8ID
        /// </summary>
        public int DropItemID8;

        /// <summary>
        /// 掉落道具8最小数量
        /// </summary>
        public int DropItemMinNum8;

        /// <summary>
        /// 掉落道具8最大数量
        /// </summary>
        public int DropItemMaxNum8;

        /// <summary>
        /// 掉落道具9概率
        /// </summary>
        public int DropChance9;

        /// <summary>
        /// 掉落道具9ID
        /// </summary>
        public int DropItemID9;

        /// <summary>
        /// 掉落道具9最小数量
        /// </summary>
        public int DropItemMinNum9;

        /// <summary>
        /// 掉落道具9最大数量
        /// </summary>
        public int DropItemMaxNum9;

        /// <summary>
        /// 掉落道具10概率
        /// </summary>
        public int DropChance10;

        /// <summary>
        /// 掉落道具10ID
        /// </summary>
        public int DropItemID10;

        /// <summary>
        /// 掉落道具10最小数量
        /// </summary>
        public int DropItemMinNum10;

        /// <summary>
        /// 掉落道具10最大数量
        /// </summary>
        public int DropItemMaxNum10;


        public const int __ID__ = -1845736655;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "DropType:" + DropType + ","
            + "DropLimit:" + DropLimit + ","
            + "ifEnterBag:" + ifEnterBag + ","
            + "DropSonID:" + DropSonID + ","
            + "DropChance1:" + DropChance1 + ","
            + "DropItemID1:" + DropItemID1 + ","
            + "DropItemMinNum1:" + DropItemMinNum1 + ","
            + "DropItemMaxNum1:" + DropItemMaxNum1 + ","
            + "DropChance2:" + DropChance2 + ","
            + "DropItemID2:" + DropItemID2 + ","
            + "DropItemMinNum2:" + DropItemMinNum2 + ","
            + "DropItemMaxNum2:" + DropItemMaxNum2 + ","
            + "DropChance3:" + DropChance3 + ","
            + "DropItemID3:" + DropItemID3 + ","
            + "DropItemMinNum3:" + DropItemMinNum3 + ","
            + "DropItemMaxNum3:" + DropItemMaxNum3 + ","
            + "DropChance4:" + DropChance4 + ","
            + "DropItemID4:" + DropItemID4 + ","
            + "DropItemMinNum4:" + DropItemMinNum4 + ","
            + "DropItemMaxNum4:" + DropItemMaxNum4 + ","
            + "DropChance5:" + DropChance5 + ","
            + "DropItemID5:" + DropItemID5 + ","
            + "DropItemMinNum5:" + DropItemMinNum5 + ","
            + "DropItemMaxNum5:" + DropItemMaxNum5 + ","
            + "DropChance6:" + DropChance6 + ","
            + "DropItemID6:" + DropItemID6 + ","
            + "DropItemMinNum6:" + DropItemMinNum6 + ","
            + "DropItemMaxNum6:" + DropItemMaxNum6 + ","
            + "DropChance7:" + DropChance7 + ","
            + "DropItemID7:" + DropItemID7 + ","
            + "DropItemMinNum7:" + DropItemMinNum7 + ","
            + "DropItemMaxNum7:" + DropItemMaxNum7 + ","
            + "DropChance8:" + DropChance8 + ","
            + "DropItemID8:" + DropItemID8 + ","
            + "DropItemMinNum8:" + DropItemMinNum8 + ","
            + "DropItemMaxNum8:" + DropItemMaxNum8 + ","
            + "DropChance9:" + DropChance9 + ","
            + "DropItemID9:" + DropItemID9 + ","
            + "DropItemMinNum9:" + DropItemMinNum9 + ","
            + "DropItemMaxNum9:" + DropItemMaxNum9 + ","
            + "DropChance10:" + DropChance10 + ","
            + "DropItemID10:" + DropItemID10 + ","
            + "DropItemMinNum10:" + DropItemMinNum10 + ","
            + "DropItemMaxNum10:" + DropItemMaxNum10 + ","
            + "}";
        }

        partial void PostInit();
    }
}

