
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class DungeonTransferConfigCategory : Singleton<DungeonTransferConfigCategory>, IConfig
    {
        private readonly Dictionary<int, DungeonTransferConfig> _dataMap;
        private readonly List<DungeonTransferConfig> _dataList;

        public DungeonTransferConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, DungeonTransferConfig>();
            _dataList = new List<DungeonTransferConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                DungeonTransferConfig _v;
                _v = global::ET.DungeonTransferConfig.DeserializeDungeonTransferConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, DungeonTransferConfig> DataMap => _dataMap;
        public List<DungeonTransferConfig> DataList => _dataList;
        public Dictionary<int, DungeonTransferConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public DungeonTransferConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public DungeonTransferConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

