
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class DungeonConfigCategory : Singleton<DungeonConfigCategory>, IConfig
    {
        private readonly Dictionary<int, DungeonConfig> _dataMap;
        private readonly List<DungeonConfig> _dataList;

        public DungeonConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, DungeonConfig>();
            _dataList = new List<DungeonConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                DungeonConfig _v;
                _v = global::ET.DungeonConfig.DeserializeDungeonConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, DungeonConfig> DataMap => _dataMap;
        public List<DungeonConfig> DataList => _dataList;
        public Dictionary<int, DungeonConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public DungeonConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public DungeonConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

