
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class EquipSuitConfig : BeanBase
    {
        public EquipSuitConfig()
        {
        }


        public EquipSuitConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); NeedEquipID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); NeedEquipID[__index0] = __e0;}}
            SuitPropertyID = _buf.ReadString();
            SuitType = _buf.ReadInt();
            Occ = _buf.ReadInt();

            PostInit();
        }

        public static EquipSuitConfig DeserializeEquipSuitConfig(ByteBuf _buf)
        {
            return new EquipSuitConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 套装名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 需要装备ID
        /// </summary>
        public int[] NeedEquipID;

        /// <summary>
        /// 套装属性
        /// </summary>
        public string SuitPropertyID;

        /// <summary>
        /// 套装类型
        /// </summary>
        public int SuitType;

        /// <summary>
        /// 职业
        /// </summary>
        public int Occ;


        public const int __ID__ = 1010810079;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "NeedEquipID:" + Luban.StringUtil.CollectionToString(NeedEquipID) + ","
            + "SuitPropertyID:" + SuitPropertyID + ","
            + "SuitType:" + SuitType + ","
            + "Occ:" + Occ + ","
            + "}";
        }

        partial void PostInit();
    }
}

