
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class EquipXiLianConfigCategory : Singleton<EquipXiLianConfigCategory>, IConfig
    {
        private readonly Dictionary<int, EquipXiLianConfig> _dataMap;
        private readonly List<EquipXiLianConfig> _dataList;

        public EquipXiLianConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, EquipXiLianConfig>();
            _dataList = new List<EquipXiLianConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                EquipXiLianConfig _v;
                _v = global::ET.EquipXiLianConfig.DeserializeEquipXiLianConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, EquipXiLianConfig> DataMap => _dataMap;
        public List<EquipXiLianConfig> DataList => _dataList;
        public Dictionary<int, EquipXiLianConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public EquipXiLianConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public EquipXiLianConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

