
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class EquipSuitPropertyConfig : BeanBase
    {
        public EquipSuitPropertyConfig()
        {
        }


        public EquipSuitPropertyConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            EquipSuitName = _buf.ReadString();
            EquipSuitDes = _buf.ReadString();
            ifShowSuitNum = _buf.ReadInt();
            Equip_Hp = _buf.ReadInt();
            Equip_MinAct = _buf.ReadInt();
            Equip_MaxAct = _buf.ReadInt();
            Equip_MinMagAct = _buf.ReadInt();
            Equip_MaxMagAct = _buf.ReadInt();
            Equip_MinDef = _buf.ReadInt();
            Equip_MaxDef = _buf.ReadInt();
            Equip_MinAdf = _buf.ReadInt();
            Equip_MaxAdf = _buf.ReadInt();
            Equip_Cri = _buf.ReadDouble();
            Equip_Hit = _buf.ReadDouble();
            Equip_Dodge = _buf.ReadDouble();
            Equip_DamgeAdd = _buf.ReadDouble();
            Equip_DamgeSub = _buf.ReadDouble();
            Equip_Speed = _buf.ReadDouble();
            Equip_Lucky = _buf.ReadInt();
            EquipSuitSkillID = _buf.ReadInt();
            AddPropreListStr = _buf.ReadString();

            PostInit();
        }

        public static EquipSuitPropertyConfig DeserializeEquipSuitPropertyConfig(ByteBuf _buf)
        {
            return new EquipSuitPropertyConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 套装名称
        /// </summary>
        public string EquipSuitName;

        /// <summary>
        /// 套装名称2
        /// </summary>
        public string EquipSuitDes;

        /// <summary>
        /// 是否显示套装件数
        /// </summary>
        public int ifShowSuitNum;

        /// <summary>
        /// 血量
        /// </summary>
        public int Equip_Hp;

        /// <summary>
        /// 最低攻击
        /// </summary>
        public int Equip_MinAct;

        /// <summary>
        /// 最高攻击
        /// </summary>
        public int Equip_MaxAct;

        /// <summary>
        /// 最低攻击3
        /// </summary>
        public int Equip_MinMagAct;

        /// <summary>
        /// 最高攻击4
        /// </summary>
        public int Equip_MaxMagAct;

        /// <summary>
        /// 最低防御
        /// </summary>
        public int Equip_MinDef;

        /// <summary>
        /// 最高防御
        /// </summary>
        public int Equip_MaxDef;

        /// <summary>
        /// 最低防御5
        /// </summary>
        public int Equip_MinAdf;

        /// <summary>
        /// 最高防御6
        /// </summary>
        public int Equip_MaxAdf;

        /// <summary>
        /// 暴击
        /// </summary>
        public double Equip_Cri;

        /// <summary>
        /// 命中
        /// </summary>
        public double Equip_Hit;

        /// <summary>
        /// 闪避
        /// </summary>
        public double Equip_Dodge;

        /// <summary>
        /// 伤害加成
        /// </summary>
        public double Equip_DamgeAdd;

        /// <summary>
        /// 伤害减免
        /// </summary>
        public double Equip_DamgeSub;

        /// <summary>
        /// 速度
        /// </summary>
        public double Equip_Speed;

        /// <summary>
        /// 幸运值
        /// </summary>
        public int Equip_Lucky;

        /// <summary>
        /// 套装附加技能
        /// </summary>
        public int EquipSuitSkillID;

        /// <summary>
        /// 附加
        /// </summary>
        public string AddPropreListStr;


        public const int __ID__ = 739714580;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "EquipSuitName:" + EquipSuitName + ","
            + "EquipSuitDes:" + EquipSuitDes + ","
            + "ifShowSuitNum:" + ifShowSuitNum + ","
            + "Equip_Hp:" + Equip_Hp + ","
            + "Equip_MinAct:" + Equip_MinAct + ","
            + "Equip_MaxAct:" + Equip_MaxAct + ","
            + "Equip_MinMagAct:" + Equip_MinMagAct + ","
            + "Equip_MaxMagAct:" + Equip_MaxMagAct + ","
            + "Equip_MinDef:" + Equip_MinDef + ","
            + "Equip_MaxDef:" + Equip_MaxDef + ","
            + "Equip_MinAdf:" + Equip_MinAdf + ","
            + "Equip_MaxAdf:" + Equip_MaxAdf + ","
            + "Equip_Cri:" + Equip_Cri + ","
            + "Equip_Hit:" + Equip_Hit + ","
            + "Equip_Dodge:" + Equip_Dodge + ","
            + "Equip_DamgeAdd:" + Equip_DamgeAdd + ","
            + "Equip_DamgeSub:" + Equip_DamgeSub + ","
            + "Equip_Speed:" + Equip_Speed + ","
            + "Equip_Lucky:" + Equip_Lucky + ","
            + "EquipSuitSkillID:" + EquipSuitSkillID + ","
            + "AddPropreListStr:" + AddPropreListStr + ","
            + "}";
        }

        partial void PostInit();
    }
}

