
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class FashionConfig : BeanBase
    {
        public FashionConfig()
        {
        }


        public FashionConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); Occ = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Occ[__index0] = __e0;}}
            Position = _buf.ReadInt();
            SubType = _buf.ReadInt();
            Name = _buf.ReadString();
            Model = _buf.ReadString();
            ActiveCost = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); Camera = new double[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { double __e0;__e0 = _buf.ReadDouble(); Camera[__index0] = __e0;}}

            PostInit();
        }

        public static FashionConfig DeserializeFashionConfig(ByteBuf _buf)
        {
            return new FashionConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 职业
        /// </summary>
        public int[] Occ;

        /// <summary>
        /// 时装部位
        /// </summary>
        public int Position;

        /// <summary>
        /// 时装子类
        /// </summary>
        public int SubType;

        /// <summary>
        /// 时装名字
        /// </summary>
        public string Name;

        /// <summary>
        /// 时装模型
        /// </summary>
        public string Model;

        /// <summary>
        /// 激活条件
        /// </summary>
        public string ActiveCost;

        /// <summary>
        /// 摄像机参数
        /// </summary>
        public double[] Camera;


        public const int __ID__ = 1358664442;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Occ:" + Luban.StringUtil.CollectionToString(Occ) + ","
            + "Position:" + Position + ","
            + "SubType:" + SubType + ","
            + "Name:" + Name + ","
            + "Model:" + Model + ","
            + "ActiveCost:" + ActiveCost + ","
            + "Camera:" + Luban.StringUtil.CollectionToString(Camera) + ","
            + "}";
        }

        partial void PostInit();
    }
}

