
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class FirstWinConfig : BeanBase
    {
        public FirstWinConfig()
        {
        }


        public FirstWinConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ChatperId = _buf.ReadInt();
            BossID = _buf.ReadInt();
            RewardList_1 = _buf.ReadString();
            RewardList_2 = _buf.ReadString();
            RewardList_3 = _buf.ReadString();
            Self_RewardList_1 = _buf.ReadString();
            Self_RewardList_2 = _buf.ReadString();
            Self_RewardList_3 = _buf.ReadString();

            PostInit();
        }

        public static FirstWinConfig DeserializeFirstWinConfig(ByteBuf _buf)
        {
            return new FirstWinConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// ChatperId
        /// </summary>
        public int ChatperId;

        /// <summary>
        /// BossID
        /// </summary>
        public int BossID;

        /// <summary>
        /// 普通奖励
        /// </summary>
        public string RewardList_1;

        /// <summary>
        /// 挑战奖励
        /// </summary>
        public string RewardList_2;

        /// <summary>
        /// 地狱奖励
        /// </summary>
        public string RewardList_3;

        /// <summary>
        /// 个人普通奖励
        /// </summary>
        public string Self_RewardList_1;

        /// <summary>
        /// 个人挑战奖励
        /// </summary>
        public string Self_RewardList_2;

        /// <summary>
        /// 个人地狱奖励
        /// </summary>
        public string Self_RewardList_3;


        public const int __ID__ = -911145586;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ChatperId:" + ChatperId + ","
            + "BossID:" + BossID + ","
            + "RewardList_1:" + RewardList_1 + ","
            + "RewardList_2:" + RewardList_2 + ","
            + "RewardList_3:" + RewardList_3 + ","
            + "Self_RewardList_1:" + Self_RewardList_1 + ","
            + "Self_RewardList_2:" + Self_RewardList_2 + ","
            + "Self_RewardList_3:" + Self_RewardList_3 + ","
            + "}";
        }

        partial void PostInit();
    }
}

