
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class FuntionConfig : BeanBase
    {
        public FuntionConfig()
        {
        }


        public FuntionConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); ConditionType = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ConditionType[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); ConditionParam = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ConditionParam[__index0] = __e0;}}
            OpenTime = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); OpenDay = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); OpenDay[__index0] = __e0;}}
            IfOpen = _buf.ReadString();
            SceneId = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); CreateMonsterPosi = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); CreateMonsterPosi[__index0] = __e0;}}

            PostInit();
        }

        public static FuntionConfig DeserializeFuntionConfig(ByteBuf _buf)
        {
            return new FuntionConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// UI
        /// </summary>
        public string Name;

        /// <summary>
        /// 开启条件类型
        /// </summary>
        public int[] ConditionType;

        /// <summary>
        /// 开启条件参数
        /// </summary>
        public int[] ConditionParam;

        /// <summary>
        /// 开启时间
        /// </summary>
        public string OpenTime;

        /// <summary>
        /// 开始时间 周1-周7
        /// </summary>
        public int[] OpenDay;

        /// <summary>
        /// 是否开启
        /// </summary>
        public string IfOpen;

        /// <summary>
        /// 刷怪场景
        /// </summary>
        public int SceneId;

        /// <summary>
        /// 刷怪配置
        /// </summary>
        public int[] CreateMonsterPosi;


        public const int __ID__ = 1976978965;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "ConditionType:" + Luban.StringUtil.CollectionToString(ConditionType) + ","
            + "ConditionParam:" + Luban.StringUtil.CollectionToString(ConditionParam) + ","
            + "OpenTime:" + OpenTime + ","
            + "OpenDay:" + Luban.StringUtil.CollectionToString(OpenDay) + ","
            + "IfOpen:" + IfOpen + ","
            + "SceneId:" + SceneId + ","
            + "CreateMonsterPosi:" + Luban.StringUtil.CollectionToString(CreateMonsterPosi) + ","
            + "}";
        }

        partial void PostInit();
    }
}

