
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class GuideConfig : BeanBase
    {
        public GuideConfig()
        {
        }


        public GuideConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            GroupId = _buf.ReadInt();
            NextID = _buf.ReadInt();
            Save = _buf.ReadInt();
            TrigerType = _buf.ReadInt();
            TrigerParams = _buf.ReadString();
            ActionType = _buf.ReadInt();
            ActionTarget = _buf.ReadString();
            ActionParams = _buf.ReadString();
            Force = _buf.ReadInt();
            Text = _buf.ReadString();
            TextPosition = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); Offset = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Offset[__index0] = __e0;}}

            PostInit();
        }

        public static GuideConfig DeserializeGuideConfig(ByteBuf _buf)
        {
            return new GuideConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 组
        /// </summary>
        public int GroupId;

        /// <summary>
        /// 下一步
        /// </summary>
        public int NextID;

        /// <summary>
        /// 是否保存
        /// </summary>
        public int Save;

        /// <summary>
        /// 触发条件
        /// </summary>
        public int TrigerType;

        /// <summary>
        /// 触发目标
        /// </summary>
        public string TrigerParams;

        /// <summary>
        /// 行为类型
        /// </summary>
        public int ActionType;

        /// <summary>
        /// 行为对象
        /// </summary>
        public string ActionTarget;

        /// <summary>
        /// 行为参数
        /// </summary>
        public string ActionParams;

        /// <summary>
        /// 是否强引导
        /// </summary>
        public int Force;

        /// <summary>
        /// 引导文本
        /// </summary>
        public string Text;

        /// <summary>
        /// 文本位置[相对于按钮]
        /// </summary>
        public int TextPosition;

        /// <summary>
        /// 偏移
        /// </summary>
        public int[] Offset;


        public const int __ID__ = -1400953538;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "GroupId:" + GroupId + ","
            + "NextID:" + NextID + ","
            + "Save:" + Save + ","
            + "TrigerType:" + TrigerType + ","
            + "TrigerParams:" + TrigerParams + ","
            + "ActionType:" + ActionType + ","
            + "ActionTarget:" + ActionTarget + ","
            + "ActionParams:" + ActionParams + ","
            + "Force:" + Force + ","
            + "Text:" + Text + ","
            + "TextPosition:" + TextPosition + ","
            + "Offset:" + Luban.StringUtil.CollectionToString(Offset) + ","
            + "}";
        }

        partial void PostInit();
    }
}

