
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class HideProListConfig : BeanBase
    {
        public HideProListConfig()
        {
        }


        public HideProListConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            NtxtID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); EquipSpace = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); EquipSpace[__index0] = __e0;}}
            NeedXiLianLv = _buf.ReadInt();
            TriggerPro = _buf.ReadDouble();
            PropertyType = _buf.ReadInt();
            IfEquipLvUp = _buf.ReadInt();
            HideProValueType = _buf.ReadInt();
            PropertyValueMin = _buf.ReadString();
            PropertyValueMax = _buf.ReadString();
            AddFightValue = _buf.ReadInt();
            IfMove = _buf.ReadInt();
            NeedNumber = _buf.ReadInt();

            PostInit();
        }

        public static HideProListConfig DeserializeHideProListConfig(ByteBuf _buf)
        {
            return new HideProListConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 隐藏属性名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 下一ID
        /// </summary>
        public int NtxtID;

        /// <summary>
        /// 洗炼属性出现部位
        /// </summary>
        public int[] EquipSpace;

        /// <summary>
        /// 需要洗炼等级
        /// </summary>
        public int NeedXiLianLv;

        /// <summary>
        /// 随机概率
        /// </summary>
        public double TriggerPro;

        /// <summary>
        /// 隐藏属性类型
        /// </summary>
        public int PropertyType;

        /// <summary>
        /// 是否根据等级成长
        /// </summary>
        public int IfEquipLvUp;

        /// <summary>
        /// 隐藏属性类型
        /// </summary>
        public int HideProValueType;

        /// <summary>
        /// 隐藏属性最小值
        /// </summary>
        public string PropertyValueMin;

        /// <summary>
        /// 隐藏属性最大值
        /// </summary>
        public string PropertyValueMax;

        /// <summary>
        /// 附加战力
        /// </summary>
        public int AddFightValue;

        /// <summary>
        /// 转移是否继承
        /// </summary>
        public int IfMove;

        /// <summary>
        /// 激活条件
        /// </summary>
        public int NeedNumber;


        public const int __ID__ = 1627732427;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "NtxtID:" + NtxtID + ","
            + "EquipSpace:" + Luban.StringUtil.CollectionToString(EquipSpace) + ","
            + "NeedXiLianLv:" + NeedXiLianLv + ","
            + "TriggerPro:" + TriggerPro + ","
            + "PropertyType:" + PropertyType + ","
            + "IfEquipLvUp:" + IfEquipLvUp + ","
            + "HideProValueType:" + HideProValueType + ","
            + "PropertyValueMin:" + PropertyValueMin + ","
            + "PropertyValueMax:" + PropertyValueMax + ","
            + "AddFightValue:" + AddFightValue + ","
            + "IfMove:" + IfMove + ","
            + "NeedNumber:" + NeedNumber + ","
            + "}";
        }

        partial void PostInit();
    }
}

