
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class HideProListConfigCategory : Singleton<HideProListConfigCategory>, IConfig
    {
        private readonly Dictionary<int, HideProListConfig> _dataMap;
        private readonly List<HideProListConfig> _dataList;

        public HideProListConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, HideProListConfig>();
            _dataList = new List<HideProListConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                HideProListConfig _v;
                _v = global::ET.HideProListConfig.DeserializeHideProListConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, HideProListConfig> DataMap => _dataMap;
        public List<HideProListConfig> DataList => _dataList;
        public Dictionary<int, HideProListConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public HideProListConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public HideProListConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

