
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ItemConfigCategory : Singleton<ItemConfigCategory>, IConfig
    {
        private readonly Dictionary<int, ItemConfig> _dataMap;
        private readonly List<ItemConfig> _dataList;

        public ItemConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ItemConfig>();
            _dataList = new List<ItemConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ItemConfig _v;
                _v = global::ET.ItemConfig.DeserializeItemConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ItemConfig> DataMap => _dataMap;
        public List<ItemConfig> DataList => _dataList;
        public Dictionary<int, ItemConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public ItemConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public ItemConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

