
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class JiaYuanConfig : BeanBase
    {
        public JiaYuanConfig()
        {
        }


        public JiaYuanConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            NextID = _buf.ReadInt();
            Lv = _buf.ReadInt();
            Exp = _buf.ReadInt();
            PeopleNumMax = _buf.ReadInt();
            NeedRoseLv = _buf.ReadInt();
            FarmNumMax = _buf.ReadInt();
            JiaYuanDes = _buf.ReadString();
            ExchangeExpCostZiJin = _buf.ReadInt();
            ExchangeExp = _buf.ReadInt();
            ExchangeZiJinCostGold = _buf.ReadInt();
            ExchangeZiJin = _buf.ReadInt();
            JiaYuanAddExp = _buf.ReadInt();
            PetNum = _buf.ReadInt();
            ProMax = _buf.ReadString();

            PostInit();
        }

        public static JiaYuanConfig DeserializeJiaYuanConfig(ByteBuf _buf)
        {
            return new JiaYuanConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 下一级ID
        /// </summary>
        public int NextID;

        /// <summary>
        /// 等级
        /// </summary>
        public int Lv;

        /// <summary>
        /// 升级经验
        /// </summary>
        public int Exp;

        /// <summary>
        /// 人口上限
        /// </summary>
        public int PeopleNumMax;

        /// <summary>
        /// 需要玩家等级
        /// </summary>
        public int NeedRoseLv;

        /// <summary>
        /// 农场种植上限
        /// </summary>
        public int FarmNumMax;

        /// <summary>
        /// 农场描述
        /// </summary>
        public string JiaYuanDes;

        /// <summary>
        /// 兑换经验消耗资金
        /// </summary>
        public int ExchangeExpCostZiJin;

        /// <summary>
        /// 兑换获得经验
        /// </summary>
        public int ExchangeExp;

        /// <summary>
        /// 兑换获得资金消耗金币
        /// </summary>
        public int ExchangeZiJinCostGold;

        /// <summary>
        /// 兑换获得资金
        /// </summary>
        public int ExchangeZiJin;

        /// <summary>
        /// 家园每小时产出经验
        /// </summary>
        public int JiaYuanAddExp;

        /// <summary>
        /// 宠物栏位
        /// </summary>
        public int PetNum;

        /// <summary>
        /// 属性上限
        /// </summary>
        public string ProMax;


        public const int __ID__ = -988322451;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "NextID:" + NextID + ","
            + "Lv:" + Lv + ","
            + "Exp:" + Exp + ","
            + "PeopleNumMax:" + PeopleNumMax + ","
            + "NeedRoseLv:" + NeedRoseLv + ","
            + "FarmNumMax:" + FarmNumMax + ","
            + "JiaYuanDes:" + JiaYuanDes + ","
            + "ExchangeExpCostZiJin:" + ExchangeExpCostZiJin + ","
            + "ExchangeExp:" + ExchangeExp + ","
            + "ExchangeZiJinCostGold:" + ExchangeZiJinCostGold + ","
            + "ExchangeZiJin:" + ExchangeZiJin + ","
            + "JiaYuanAddExp:" + JiaYuanAddExp + ","
            + "PetNum:" + PetNum + ","
            + "ProMax:" + ProMax + ","
            + "}";
        }

        partial void PostInit();
    }
}

