
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class JiaYuanPastureConfig : BeanBase
    {
        public JiaYuanPastureConfig()
        {
        }


        public JiaYuanPastureConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Lv = _buf.ReadInt();
            Assets = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); UpTime = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); UpTime[__index0] = __e0;}}
            PeopleNum = _buf.ReadInt();
            BuyGold = _buf.ReadInt();
            SellGold = _buf.ReadInt();
            DropTime = _buf.ReadInt();
            GetPro = _buf.ReadDouble();
            GetItemID = _buf.ReadInt();
            Speak = _buf.ReadString();
            Des = _buf.ReadString();
            BuyJiaYuanLv = _buf.ReadInt();
            BuyJiaYuanPro = _buf.ReadInt();

            PostInit();
        }

        public static JiaYuanPastureConfig DeserializeJiaYuanPastureConfig(ByteBuf _buf)
        {
            return new JiaYuanPastureConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 等级
        /// </summary>
        public int Lv;

        /// <summary>
        /// 模型资源
        /// </summary>
        public string Assets;

        /// <summary>
        /// 成长时间
        /// </summary>
        public int[] UpTime;

        /// <summary>
        /// 人口数量
        /// </summary>
        public int PeopleNum;

        /// <summary>
        /// 购买价格
        /// </summary>
        public int BuyGold;

        /// <summary>
        /// 出售价格
        /// </summary>
        public int SellGold;

        /// <summary>
        /// 掉落间隔时间
        /// </summary>
        public int DropTime;

        /// <summary>
        /// 掉落概率
        /// </summary>
        public double GetPro;

        /// <summary>
        /// 收获道具ID
        /// </summary>
        public int GetItemID;

        /// <summary>
        /// 描述
        /// </summary>
        public string Speak;

        /// <summary>
        /// 描述
        /// </summary>
        public string Des;

        /// <summary>
        /// 购买家园限制
        /// </summary>
        public int BuyJiaYuanLv;

        /// <summary>
        /// 购买家园权重
        /// </summary>
        public int BuyJiaYuanPro;


        public const int __ID__ = 1801780845;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Lv:" + Lv + ","
            + "Assets:" + Assets + ","
            + "UpTime:" + Luban.StringUtil.CollectionToString(UpTime) + ","
            + "PeopleNum:" + PeopleNum + ","
            + "BuyGold:" + BuyGold + ","
            + "SellGold:" + SellGold + ","
            + "DropTime:" + DropTime + ","
            + "GetPro:" + GetPro + ","
            + "GetItemID:" + GetItemID + ","
            + "Speak:" + Speak + ","
            + "Des:" + Des + ","
            + "BuyJiaYuanLv:" + BuyJiaYuanLv + ","
            + "BuyJiaYuanPro:" + BuyJiaYuanPro + ","
            + "}";
        }

        partial void PostInit();
    }
}

