
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class JingLingConfigCategory : Singleton<JingLingConfigCategory>, IConfig
    {
        private readonly Dictionary<int, JingLingConfig> _dataMap;
        private readonly List<JingLingConfig> _dataList;

        public JingLingConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, JingLingConfig>();
            _dataList = new List<JingLingConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                JingLingConfig _v;
                _v = global::ET.JingLingConfig.DeserializeJingLingConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, JingLingConfig> DataMap => _dataMap;
        public List<JingLingConfig> DataList => _dataList;
        public Dictionary<int, JingLingConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public JingLingConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public JingLingConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

