
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class LingDiRewardConfigCategory : Singleton<LingDiRewardConfigCategory>, IConfig
    {
        private readonly Dictionary<int, LingDiRewardConfig> _dataMap;
        private readonly List<LingDiRewardConfig> _dataList;

        public LingDiRewardConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, LingDiRewardConfig>();
            _dataList = new List<LingDiRewardConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                LingDiRewardConfig _v;
                _v = global::ET.LingDiRewardConfig.DeserializeLingDiRewardConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, LingDiRewardConfig> DataMap => _dataMap;
        public List<LingDiRewardConfig> DataList => _dataList;
        public Dictionary<int, LingDiRewardConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public LingDiRewardConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public LingDiRewardConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

