
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class LingDiRewardConfig : BeanBase
    {
        public LingDiRewardConfig()
        {
        }


        public LingDiRewardConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            NextID = _buf.ReadInt();
            ItemID = _buf.ReadInt();
            BuyItemID = _buf.ReadInt();
            BuyPrice = _buf.ReadInt();
            RoseLvlimit = _buf.ReadInt();
            CountryLvlimit = _buf.ReadInt();

            PostInit();
        }

        public static LingDiRewardConfig DeserializeLingDiRewardConfig(ByteBuf _buf)
        {
            return new LingDiRewardConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 下一个兑换ID
        /// </summary>
        public int NextID;

        /// <summary>
        /// 兑换道具名称
        /// </summary>
        public int ItemID;

        /// <summary>
        /// 兑换道具ID
        /// </summary>
        public int BuyItemID;

        /// <summary>
        /// 兑换道具价格
        /// </summary>
        public int BuyPrice;

        /// <summary>
        /// 角色等级限制
        /// </summary>
        public int RoseLvlimit;

        /// <summary>
        /// 国家等级限制
        /// </summary>
        public int CountryLvlimit;


        public const int __ID__ = -1381748180;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "NextID:" + NextID + ","
            + "ItemID:" + ItemID + ","
            + "BuyItemID:" + BuyItemID + ","
            + "BuyPrice:" + BuyPrice + ","
            + "RoseLvlimit:" + RoseLvlimit + ","
            + "CountryLvlimit:" + CountryLvlimit + ","
            + "}";
        }

        partial void PostInit();
    }
}

