
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class LingDiConfig : BeanBase
    {
        public LingDiConfig()
        {
        }


        public LingDiConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            UpExp = _buf.ReadInt();
            GoldUp = _buf.ReadInt();
            AddExp = _buf.ReadInt();
            HoureExp = _buf.ReadInt();
            HoureHonor = _buf.ReadInt();

            PostInit();
        }

        public static LingDiConfig DeserializeLingDiConfig(ByteBuf _buf)
        {
            return new LingDiConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 领地名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 升级经验
        /// </summary>
        public int UpExp;

        /// <summary>
        /// 每次消耗金币
        /// </summary>
        public int GoldUp;

        /// <summary>
        /// 消耗增加经验
        /// </summary>
        public int AddExp;

        /// <summary>
        /// 每小时产出经验
        /// </summary>
        public int HoureExp;

        /// <summary>
        /// 每小时产出荣誉
        /// </summary>
        public int HoureHonor;


        public const int __ID__ = -1132177827;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "UpExp:" + UpExp + ","
            + "GoldUp:" + GoldUp + ","
            + "AddExp:" + AddExp + ","
            + "HoureExp:" + HoureExp + ","
            + "HoureHonor:" + HoureHonor + ","
            + "}";
        }

        partial void PostInit();
    }
}

