
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class MapObjectConfigCategory : Singleton<MapObjectConfigCategory>, IConfig
    {
        private readonly Dictionary<int, MapObjectConfig> _dataMap;
        private readonly List<MapObjectConfig> _dataList;

        public MapObjectConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MapObjectConfig>();
            _dataList = new List<MapObjectConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                MapObjectConfig _v;
                _v = global::ET.MapObjectConfig.DeserializeMapObjectConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, MapObjectConfig> DataMap => _dataMap;
        public List<MapObjectConfig> DataList => _dataList;
        public Dictionary<int, MapObjectConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public MapObjectConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public MapObjectConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

