
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class MonsterGroupConfigCategory : Singleton<MonsterGroupConfigCategory>, IConfig
    {
        private readonly Dictionary<int, MonsterGroupConfig> _dataMap;
        private readonly List<MonsterGroupConfig> _dataList;

        public MonsterGroupConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MonsterGroupConfig>();
            _dataList = new List<MonsterGroupConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                MonsterGroupConfig _v;
                _v = global::ET.MonsterGroupConfig.DeserializeMonsterGroupConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, MonsterGroupConfig> DataMap => _dataMap;
        public List<MonsterGroupConfig> DataList => _dataList;
        public Dictionary<int, MonsterGroupConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public MonsterGroupConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public MonsterGroupConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

