
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MonsterPositionConfig : BeanBase
    {
        public MonsterPositionConfig()
        {
        }


        public MonsterPositionConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            NextID = _buf.ReadInt();
            Type = _buf.ReadInt();
            Position = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); MonsterID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); MonsterID[__index0] = __e0;}}
            CreateRange = _buf.ReadDouble();
            {int __n0 = _buf.ReadSize(); CreateNum = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); CreateNum[__index0] = __e0;}}
            Create = _buf.ReadInt();
            Par = _buf.ReadString();

            PostInit();
        }

        public static MonsterPositionConfig DeserializeMonsterPositionConfig(ByteBuf _buf)
        {
            return new MonsterPositionConfig(_buf);
        }

        /// <summary>
        /// id
        /// </summary>
        public int Id;

        /// <summary>
        /// 下一个刷新ID
        /// </summary>
        public int NextID;

        /// <summary>
        /// 类型
        /// </summary>
        public int Type;

        /// <summary>
        /// 坐标点
        /// </summary>
        public string Position;

        /// <summary>
        /// 怪物ID
        /// </summary>
        public int[] MonsterID;

        /// <summary>
        /// 刷怪范围
        /// </summary>
        public double CreateRange;

        /// <summary>
        /// 刷怪数量
        /// </summary>
        public int[] CreateNum;

        /// <summary>
        /// 刷新朝向
        /// </summary>
        public int Create;

        /// <summary>
        /// 其他参数
        /// </summary>
        public string Par;


        public const int __ID__ = -1150458843;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "NextID:" + NextID + ","
            + "Type:" + Type + ","
            + "Position:" + Position + ","
            + "MonsterID:" + Luban.StringUtil.CollectionToString(MonsterID) + ","
            + "CreateRange:" + CreateRange + ","
            + "CreateNum:" + Luban.StringUtil.CollectionToString(CreateNum) + ","
            + "Create:" + Create + ","
            + "Par:" + Par + ","
            + "}";
        }

        partial void PostInit();
    }
}

