
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class MulLanguageConfigCategory : Singleton<MulLanguageConfigCategory>, IConfig
    {
        private readonly Dictionary<int, MulLanguageConfig> _dataMap;
        private readonly List<MulLanguageConfig> _dataList;

        public MulLanguageConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MulLanguageConfig>();
            _dataList = new List<MulLanguageConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                MulLanguageConfig _v;
                _v = global::ET.MulLanguageConfig.DeserializeMulLanguageConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, MulLanguageConfig> DataMap => _dataMap;
        public List<MulLanguageConfig> DataList => _dataList;
        public Dictionary<int, MulLanguageConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public MulLanguageConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public MulLanguageConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

