
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MulLanguageConfig : BeanBase
    {
        public MulLanguageConfig()
        {
        }


        public MulLanguageConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Chinese = _buf.ReadString();
            English = _buf.ReadString();

            PostInit();
        }

        public static MulLanguageConfig DeserializeMulLanguageConfig(ByteBuf _buf)
        {
            return new MulLanguageConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名字
        /// </summary>
        public string Chinese;

        /// <summary>
        /// 描述
        /// </summary>
        public string English;


        public const int __ID__ = -574952066;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Chinese:" + Chinese + ","
            + "English:" + English + ","
            + "}";
        }

        partial void PostInit();
    }
}

