
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MysteryConfig : BeanBase
    {
        public MysteryConfig()
        {
        }


        public MysteryConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            NextId = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); NumberLimit = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); NumberLimit[__index0] = __e0;}}
            SellItemID = _buf.ReadInt();
            SellType = _buf.ReadInt();
            SellValue = _buf.ReadInt();
            ShowPro = _buf.ReadInt();
            ShowServerDay = _buf.ReadInt();
            BuyNumMax = _buf.ReadInt();
            JiaYuanLv = _buf.ReadInt();

            PostInit();
        }

        public static MysteryConfig DeserializeMysteryConfig(ByteBuf _buf)
        {
            return new MysteryConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// NextId
        /// </summary>
        public int NextId;

        /// <summary>
        /// 随机数量
        /// </summary>
        public int[] NumberLimit;

        /// <summary>
        /// 出售道具
        /// </summary>
        public int SellItemID;

        /// <summary>
        /// 出售货币种类
        /// </summary>
        public int SellType;

        /// <summary>
        /// 出售价格
        /// </summary>
        public int SellValue;

        /// <summary>
        /// 出现权重
        /// </summary>
        public int ShowPro;

        /// <summary>
        /// 出现服务器时间(天)
        /// </summary>
        public int ShowServerDay;

        /// <summary>
        /// 限购数量
        /// </summary>
        public int BuyNumMax;

        /// <summary>
        /// 家园等级
        /// </summary>
        public int JiaYuanLv;


        public const int __ID__ = 790619457;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "NextId:" + NextId + ","
            + "NumberLimit:" + Luban.StringUtil.CollectionToString(NumberLimit) + ","
            + "SellItemID:" + SellItemID + ","
            + "SellType:" + SellType + ","
            + "SellValue:" + SellValue + ","
            + "ShowPro:" + ShowPro + ","
            + "ShowServerDay:" + ShowServerDay + ","
            + "BuyNumMax:" + BuyNumMax + ","
            + "JiaYuanLv:" + JiaYuanLv + ","
            + "}";
        }

        partial void PostInit();
    }
}

