
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class NpcConfig : BeanBase
    {
        public NpcConfig()
        {
        }


        public NpcConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            ShopValue = _buf.ReadInt();
            NpcType = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); TaskID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); TaskID[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); StorySpeakID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); StorySpeakID[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); NpcPar = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); NpcPar[__index0] = __e0;}}
            Desc = _buf.ReadString();
            Asset = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); Position = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Position[__index0] = __e0;}}
            Rotation = _buf.ReadInt();
            AI = _buf.ReadInt();
            MovePosition = _buf.ReadString();
            ifCameraLaJin = _buf.ReadInt();
            SpeakText = _buf.ReadString();
            NpcHeadSpeakText = _buf.ReadString();
            TaskHint = _buf.ReadString();
            SourceID = _buf.ReadInt();
            ShowRoseLv = _buf.ReadInt();
            ShowType = _buf.ReadInt();
            ShowValue = _buf.ReadInt();
            ShopType = _buf.ReadInt();

            PostInit();
        }

        public static NpcConfig DeserializeNpcConfig(ByteBuf _buf)
        {
            return new NpcConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名字
        /// </summary>
        public string Name;

        /// <summary>
        /// 商店值
        /// </summary>
        public int ShopValue;

        /// <summary>
        /// NPC类型
        /// </summary>
        public int NpcType;

        /// <summary>
        /// 任务ID
        /// </summary>
        public int[] TaskID;

        /// <summary>
        /// 剧情对话ID
        /// </summary>
        public int[] StorySpeakID;

        /// <summary>
        /// npc参数
        /// </summary>
        public int[] NpcPar;

        /// <summary>
        /// 描述
        /// </summary>
        public string Desc;

        /// <summary>
        /// 资源
        /// </summary>
        public string Asset;

        /// <summary>
        /// 位置
        /// </summary>
        public int[] Position;

        /// <summary>
        /// 方向
        /// </summary>
        public int Rotation;

        /// <summary>
        /// AI
        /// </summary>
        public int AI;

        /// <summary>
        /// 移动坐标
        /// </summary>
        public string MovePosition;

        /// <summary>
        /// 摄像头是否拉近
        /// </summary>
        public int ifCameraLaJin;

        /// <summary>
        /// 对话信息
        /// </summary>
        public string SpeakText;

        /// <summary>
        /// 头部说话
        /// </summary>
        public string NpcHeadSpeakText;

        /// <summary>
        /// 任务提示
        /// </summary>
        public string TaskHint;

        /// <summary>
        /// 播放音效ID
        /// </summary>
        public int SourceID;

        /// <summary>
        /// 展示等级
        /// </summary>
        public int ShowRoseLv;

        /// <summary>
        /// 出现类型
        /// </summary>
        public int ShowType;

        /// <summary>
        /// 出现值
        /// </summary>
        public int ShowValue;

        /// <summary>
        /// 商店类型
        /// </summary>
        public int ShopType;


        public const int __ID__ = -1928671901;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "ShopValue:" + ShopValue + ","
            + "NpcType:" + NpcType + ","
            + "TaskID:" + Luban.StringUtil.CollectionToString(TaskID) + ","
            + "StorySpeakID:" + Luban.StringUtil.CollectionToString(StorySpeakID) + ","
            + "NpcPar:" + Luban.StringUtil.CollectionToString(NpcPar) + ","
            + "Desc:" + Desc + ","
            + "Asset:" + Asset + ","
            + "Position:" + Luban.StringUtil.CollectionToString(Position) + ","
            + "Rotation:" + Rotation + ","
            + "AI:" + AI + ","
            + "MovePosition:" + MovePosition + ","
            + "ifCameraLaJin:" + ifCameraLaJin + ","
            + "SpeakText:" + SpeakText + ","
            + "NpcHeadSpeakText:" + NpcHeadSpeakText + ","
            + "TaskHint:" + TaskHint + ","
            + "SourceID:" + SourceID + ","
            + "ShowRoseLv:" + ShowRoseLv + ","
            + "ShowType:" + ShowType + ","
            + "ShowValue:" + ShowValue + ","
            + "ShopType:" + ShopType + ","
            + "}";
        }

        partial void PostInit();
    }
}

