
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class OccupationTwoConfigCategory : Singleton<OccupationTwoConfigCategory>, IConfig
    {
        private readonly Dictionary<int, OccupationTwoConfig> _dataMap;
        private readonly List<OccupationTwoConfig> _dataList;

        public OccupationTwoConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, OccupationTwoConfig>();
            _dataList = new List<OccupationTwoConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                OccupationTwoConfig _v;
                _v = global::ET.OccupationTwoConfig.DeserializeOccupationTwoConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, OccupationTwoConfig> DataMap => _dataMap;
        public List<OccupationTwoConfig> DataList => _dataList;
        public Dictionary<int, OccupationTwoConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public OccupationTwoConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public OccupationTwoConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

