
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class OccupationConfig : BeanBase
    {
        public OccupationConfig()
        {
        }


        public OccupationConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            OccupationName = _buf.ReadString();
            ModelAsset = _buf.ReadString();
            ChangeEquip = _buf.ReadInt();
            BaseHp = _buf.ReadLong();
            BaseMinAct = _buf.ReadLong();
            BaseMaxAct = _buf.ReadLong();
            BaseMinDef = _buf.ReadLong();
            BaseMaxDef = _buf.ReadLong();
            BaseMinAdf = _buf.ReadLong();
            BaseMaxAdf = _buf.ReadLong();
            BaseMoveSpeed = _buf.ReadDouble();
            BaseCri = _buf.ReadDouble();
            BaseHit = _buf.ReadDouble();
            BaseDodge = _buf.ReadDouble();
            BaseDefAdd = _buf.ReadDouble();
            BaseAdfAdd = _buf.ReadDouble();
            DamgeAdd = _buf.ReadDouble();
            LvUpHp = _buf.ReadLong();
            LvUpMinAct = _buf.ReadLong();
            LvUpMaxAct = _buf.ReadLong();
            LvUpMinMagAct = _buf.ReadLong();
            LvUpMaxMagAct = _buf.ReadLong();
            LvUpMinDef = _buf.ReadLong();
            LvUpMaxDef = _buf.ReadLong();
            LvUpMinAdf = _buf.ReadLong();
            LvUpMaxAdf = _buf.ReadLong();
            InitActSkillID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); InitSkillID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); InitSkillID[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); OccTwoID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); OccTwoID[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); FashionBase = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); FashionBase[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); BaseSkill = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); BaseSkill[__index0] = __e0;}}

            PostInit();
        }

        public static OccupationConfig DeserializeOccupationConfig(ByteBuf _buf)
        {
            return new OccupationConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 职业名称
        /// </summary>
        public string OccupationName;

        /// <summary>
        /// 模型
        /// </summary>
        public string ModelAsset;

        /// <summary>
        /// 支持换装
        /// </summary>
        public int ChangeEquip;

        /// <summary>
        /// 初始血量
        /// </summary>
        public long BaseHp;

        /// <summary>
        /// 初始攻击最小值
        /// </summary>
        public long BaseMinAct;

        /// <summary>
        /// 初始攻击最大值
        /// </summary>
        public long BaseMaxAct;

        /// <summary>
        /// 初始物防最小值
        /// </summary>
        public long BaseMinDef;

        /// <summary>
        /// 初始物防最大值
        /// </summary>
        public long BaseMaxDef;

        /// <summary>
        /// 初始魔防最小值
        /// </summary>
        public long BaseMinAdf;

        /// <summary>
        /// 初始魔防最大值
        /// </summary>
        public long BaseMaxAdf;

        /// <summary>
        /// 初始移动速度
        /// </summary>
        public double BaseMoveSpeed;

        /// <summary>
        /// 初始暴击值
        /// </summary>
        public double BaseCri;

        /// <summary>
        /// 初始命中值
        /// </summary>
        public double BaseHit;

        /// <summary>
        /// 初始闪避值
        /// </summary>
        public double BaseDodge;

        /// <summary>
        /// 初始物理免伤
        /// </summary>
        public double BaseDefAdd;

        /// <summary>
        /// 初始魔法免伤
        /// </summary>
        public double BaseAdfAdd;

        /// <summary>
        /// 初始免伤
        /// </summary>
        public double DamgeAdd;

        /// <summary>
        /// 每级血量成长
        /// </summary>
        public long LvUpHp;

        /// <summary>
        /// 每级攻击最小级成长
        /// </summary>
        public long LvUpMinAct;

        /// <summary>
        /// 每级攻击最大值成长
        /// </summary>
        public long LvUpMaxAct;

        /// <summary>
        /// 每级攻击最小级成长
        /// </summary>
        public long LvUpMinMagAct;

        /// <summary>
        /// 每级攻击最大值成长
        /// </summary>
        public long LvUpMaxMagAct;

        /// <summary>
        /// 初始物防最小值
        /// </summary>
        public long LvUpMinDef;

        /// <summary>
        /// 初始物防最大值
        /// </summary>
        public long LvUpMaxDef;

        /// <summary>
        /// 初始魔防最小值
        /// </summary>
        public long LvUpMinAdf;

        /// <summary>
        /// 初始魔防最大值
        /// </summary>
        public long LvUpMaxAdf;

        /// <summary>
        /// 初始化普通攻击
        /// </summary>
        public int InitActSkillID;

        /// <summary>
        /// 初始化技能ID
        /// </summary>
        public int[] InitSkillID;

        /// <summary>
        /// 转职ID
        /// </summary>
        public int[] OccTwoID;

        /// <summary>
        /// 时装部件
        /// </summary>
        public int[] FashionBase;

        /// <summary>
        /// 基础技能
        /// </summary>
        public int[] BaseSkill;


        public const int __ID__ = 1047640205;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "OccupationName:" + OccupationName + ","
            + "ModelAsset:" + ModelAsset + ","
            + "ChangeEquip:" + ChangeEquip + ","
            + "BaseHp:" + BaseHp + ","
            + "BaseMinAct:" + BaseMinAct + ","
            + "BaseMaxAct:" + BaseMaxAct + ","
            + "BaseMinDef:" + BaseMinDef + ","
            + "BaseMaxDef:" + BaseMaxDef + ","
            + "BaseMinAdf:" + BaseMinAdf + ","
            + "BaseMaxAdf:" + BaseMaxAdf + ","
            + "BaseMoveSpeed:" + BaseMoveSpeed + ","
            + "BaseCri:" + BaseCri + ","
            + "BaseHit:" + BaseHit + ","
            + "BaseDodge:" + BaseDodge + ","
            + "BaseDefAdd:" + BaseDefAdd + ","
            + "BaseAdfAdd:" + BaseAdfAdd + ","
            + "DamgeAdd:" + DamgeAdd + ","
            + "LvUpHp:" + LvUpHp + ","
            + "LvUpMinAct:" + LvUpMinAct + ","
            + "LvUpMaxAct:" + LvUpMaxAct + ","
            + "LvUpMinMagAct:" + LvUpMinMagAct + ","
            + "LvUpMaxMagAct:" + LvUpMaxMagAct + ","
            + "LvUpMinDef:" + LvUpMinDef + ","
            + "LvUpMaxDef:" + LvUpMaxDef + ","
            + "LvUpMinAdf:" + LvUpMinAdf + ","
            + "LvUpMaxAdf:" + LvUpMaxAdf + ","
            + "InitActSkillID:" + InitActSkillID + ","
            + "InitSkillID:" + Luban.StringUtil.CollectionToString(InitSkillID) + ","
            + "OccTwoID:" + Luban.StringUtil.CollectionToString(OccTwoID) + ","
            + "FashionBase:" + Luban.StringUtil.CollectionToString(FashionBase) + ","
            + "BaseSkill:" + Luban.StringUtil.CollectionToString(BaseSkill) + ","
            + "}";
        }

        partial void PostInit();
    }
}

