
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PaiMaiSellConfig : BeanBase
    {
        public PaiMaiSellConfig()
        {
        }


        public PaiMaiSellConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            PaiMaiType = _buf.ReadInt();
            ChapterId = _buf.ReadInt();
            BuyLv = _buf.ReadInt();
            ItemID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); Price = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Price[__index0] = __e0;}}
            PriceMax = _buf.ReadInt();
            PriceMin = _buf.ReadInt();

            PostInit();
        }

        public static PaiMaiSellConfig DeserializePaiMaiSellConfig(ByteBuf _buf)
        {
            return new PaiMaiSellConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 拍卖类型
        /// </summary>
        public int PaiMaiType;

        /// <summary>
        /// 章节ID
        /// </summary>
        public int ChapterId;

        /// <summary>
        /// 购买等级
        /// </summary>
        public int BuyLv;

        /// <summary>
        /// 道具ID
        /// </summary>
        public int ItemID;

        /// <summary>
        /// 价格
        /// </summary>
        public int[] Price;

        /// <summary>
        /// 价格上限
        /// </summary>
        public int PriceMax;

        /// <summary>
        /// 价格下限
        /// </summary>
        public int PriceMin;


        public const int __ID__ = 919211729;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "PaiMaiType:" + PaiMaiType + ","
            + "ChapterId:" + ChapterId + ","
            + "BuyLv:" + BuyLv + ","
            + "ItemID:" + ItemID + ","
            + "Price:" + Luban.StringUtil.CollectionToString(Price) + ","
            + "PriceMax:" + PriceMax + ","
            + "PriceMin:" + PriceMin + ","
            + "}";
        }

        partial void PostInit();
    }
}

