
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class PetConfigCategory : Singleton<PetConfigCategory>, IConfig
    {
        private readonly Dictionary<int, PetConfig> _dataMap;
        private readonly List<PetConfig> _dataList;

        public PetConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, PetConfig>();
            _dataList = new List<PetConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                PetConfig _v;
                _v = global::ET.PetConfig.DeserializePetConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, PetConfig> DataMap => _dataMap;
        public List<PetConfig> DataList => _dataList;
        public Dictionary<int, PetConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public PetConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public PetConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

