
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class PetFubenConfigCategory : Singleton<PetFubenConfigCategory>, IConfig
    {
        private readonly Dictionary<int, PetFubenConfig> _dataMap;
        private readonly List<PetFubenConfig> _dataList;

        public PetFubenConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, PetFubenConfig>();
            _dataList = new List<PetFubenConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                PetFubenConfig _v;
                _v = global::ET.PetFubenConfig.DeserializePetFubenConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, PetFubenConfig> DataMap => _dataMap;
        public List<PetFubenConfig> DataList => _dataList;
        public Dictionary<int, PetFubenConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public PetFubenConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public PetFubenConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

