
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PetMagicCardConfig : BeanBase
    {
        public PetMagicCardConfig()
        {
        }


        public PetMagicCardConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            GetWay = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); GetValue = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); GetValue[__index0] = __e0;}}
            NeedPoint = _buf.ReadInt();
            ActivePro = _buf.ReadDouble();
            Type = _buf.ReadInt();
            Cost = _buf.ReadInt();
            Icon = _buf.ReadInt();
            SkillId = _buf.ReadInt();
            IsOnly = _buf.ReadInt();

            PostInit();
        }

        public static PetMagicCardConfig DeserializePetMagicCardConfig(ByteBuf _buf)
        {
            return new PetMagicCardConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 获取方式
        /// </summary>
        public int GetWay;

        /// <summary>
        /// 获取参数
        /// </summary>
        public int[] GetValue;

        /// <summary>
        /// 激活点数
        /// </summary>
        public int NeedPoint;

        /// <summary>
        /// 激活概率
        /// </summary>
        public double ActivePro;

        /// <summary>
        /// 类型
        /// </summary>
        public int Type;

        /// <summary>
        /// 召唤消耗
        /// </summary>
        public int Cost;

        /// <summary>
        /// 图标显示
        /// </summary>
        public int Icon;

        /// <summary>
        /// 技能Id
        /// </summary>
        public int SkillId;

        /// <summary>
        /// 只出现一次
        /// </summary>
        public int IsOnly;


        public const int __ID__ = 1203892480;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "GetWay:" + GetWay + ","
            + "GetValue:" + Luban.StringUtil.CollectionToString(GetValue) + ","
            + "NeedPoint:" + NeedPoint + ","
            + "ActivePro:" + ActivePro + ","
            + "Type:" + Type + ","
            + "Cost:" + Cost + ","
            + "Icon:" + Icon + ","
            + "SkillId:" + SkillId + ","
            + "IsOnly:" + IsOnly + ","
            + "}";
        }

        partial void PostInit();
    }
}

