
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class PetTuJianConfigCategory : Singleton<PetTuJianConfigCategory>, IConfig
    {
        private readonly Dictionary<int, PetTuJianConfig> _dataMap;
        private readonly List<PetTuJianConfig> _dataList;

        public PetTuJianConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, PetTuJianConfig>();
            _dataList = new List<PetTuJianConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                PetTuJianConfig _v;
                _v = global::ET.PetTuJianConfig.DeserializePetTuJianConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, PetTuJianConfig> DataMap => _dataMap;
        public List<PetTuJianConfig> DataList => _dataList;
        public Dictionary<int, PetTuJianConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public PetTuJianConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public PetTuJianConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

