
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PetXiuLianConfig : BeanBase
    {
        public PetXiuLianConfig()
        {
        }


        public PetXiuLianConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Icon = _buf.ReadString();
            NextID = _buf.ReadInt();
            Lv = _buf.ReadInt();
            SuccessPro = _buf.ReadString();
            AddPro = _buf.ReadString();
            CostMoney = _buf.ReadInt();
            CostItem = _buf.ReadString();
            Des = _buf.ReadString();
            Des_EN = _buf.ReadString();

            PostInit();
        }

        public static PetXiuLianConfig DeserializePetXiuLianConfig(ByteBuf _buf)
        {
            return new PetXiuLianConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 图标显示
        /// </summary>
        public string Icon;

        /// <summary>
        /// 下一ID
        /// </summary>
        public int NextID;

        /// <summary>
        /// 等级
        /// </summary>
        public int Lv;

        /// <summary>
        /// 成功概率
        /// </summary>
        public string SuccessPro;

        /// <summary>
        /// 增加属性
        /// </summary>
        public string AddPro;

        /// <summary>
        /// 消耗金币
        /// </summary>
        public int CostMoney;

        /// <summary>
        /// 消耗道具
        /// </summary>
        public string CostItem;

        /// <summary>
        /// 描述
        /// </summary>
        public string Des;

        /// <summary>
        /// 描述2
        /// </summary>
        public string Des_EN;


        public const int __ID__ = 1624597073;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Icon:" + Icon + ","
            + "NextID:" + NextID + ","
            + "Lv:" + Lv + ","
            + "SuccessPro:" + SuccessPro + ","
            + "AddPro:" + AddPro + ","
            + "CostMoney:" + CostMoney + ","
            + "CostItem:" + CostItem + ","
            + "Des:" + Des + ","
            + "Des_EN:" + Des_EN + ","
            + "}";
        }

        partial void PostInit();
    }
}

