
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PublicQiangHuaConfig : BeanBase
    {
        public PublicQiangHuaConfig()
        {
        }


        public PublicQiangHuaConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            EquipSpaceName = _buf.ReadString();
            Icon = _buf.ReadString();
            ItemSubType = _buf.ReadInt();
            NextID = _buf.ReadInt();
            QiangHuaLv = _buf.ReadInt();
            UpLvLimit = _buf.ReadInt();
            SuccessPro = _buf.ReadDouble();
            CostGold = _buf.ReadInt();
            CostItem = _buf.ReadString();
            EquipPropreAdd = _buf.ReadString();
            AdditionPro = _buf.ReadDouble();

            PostInit();
        }

        public static PublicQiangHuaConfig DeserializePublicQiangHuaConfig(ByteBuf _buf)
        {
            return new PublicQiangHuaConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 装备名称
        /// </summary>
        public string EquipSpaceName;

        /// <summary>
        /// 图标
        /// </summary>
        public string Icon;

        /// <summary>
        /// 强化类型
        /// </summary>
        public int ItemSubType;

        /// <summary>
        /// 下一级强化
        /// </summary>
        public int NextID;

        /// <summary>
        /// 强化等级
        /// </summary>
        public int QiangHuaLv;

        /// <summary>
        /// 升级等级限制
        /// </summary>
        public int UpLvLimit;

        /// <summary>
        /// 成功概率
        /// </summary>
        public double SuccessPro;

        /// <summary>
        /// 消耗金币
        /// </summary>
        public int CostGold;

        /// <summary>
        /// 强化消耗
        /// </summary>
        public string CostItem;

        /// <summary>
        /// 强化属性
        /// </summary>
        public string EquipPropreAdd;

        /// <summary>
        /// 失败附加成功概率
        /// </summary>
        public double AdditionPro;


        public const int __ID__ = 397871517;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "EquipSpaceName:" + EquipSpaceName + ","
            + "Icon:" + Icon + ","
            + "ItemSubType:" + ItemSubType + ","
            + "NextID:" + NextID + ","
            + "QiangHuaLv:" + QiangHuaLv + ","
            + "UpLvLimit:" + UpLvLimit + ","
            + "SuccessPro:" + SuccessPro + ","
            + "CostGold:" + CostGold + ","
            + "CostItem:" + CostItem + ","
            + "EquipPropreAdd:" + EquipPropreAdd + ","
            + "AdditionPro:" + AdditionPro + ","
            + "}";
        }

        partial void PostInit();
    }
}

