
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class QuestionBankConfigCategory : Singleton<QuestionBankConfigCategory>, IConfig
    {
        private readonly Dictionary<int, QuestionBankConfig> _dataMap;
        private readonly List<QuestionBankConfig> _dataList;

        public QuestionBankConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, QuestionBankConfig>();
            _dataList = new List<QuestionBankConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                QuestionBankConfig _v;
                _v = global::ET.QuestionBankConfig.DeserializeQuestionBankConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, QuestionBankConfig> DataMap => _dataMap;
        public List<QuestionBankConfig> DataList => _dataList;
        public Dictionary<int, QuestionBankConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public QuestionBankConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public QuestionBankConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

