
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class RankRewardConfig : BeanBase
    {
        public RankRewardConfig()
        {
        }


        public RankRewardConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Type = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); NeedPoint = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); NeedPoint[__index0] = __e0;}}
            RewardItems = _buf.ReadString();

            PostInit();
        }

        public static RankRewardConfig DeserializeRankRewardConfig(ByteBuf _buf)
        {
            return new RankRewardConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 排名类型
        /// </summary>
        public int Type;

        /// <summary>
        /// 排行名次
        /// </summary>
        public int[] NeedPoint;

        /// <summary>
        /// 奖励
        /// </summary>
        public string RewardItems;


        public const int __ID__ = 1626956221;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Type:" + Type + ","
            + "NeedPoint:" + Luban.StringUtil.CollectionToString(NeedPoint) + ","
            + "RewardItems:" + RewardItems + ","
            + "}";
        }

        partial void PostInit();
    }
}

