
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class RobotConfigCategory : Singleton<RobotConfigCategory>, IConfig
    {
        private readonly Dictionary<int, RobotConfig> _dataMap;
        private readonly List<RobotConfig> _dataList;

        public RobotConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, RobotConfig>();
            _dataList = new List<RobotConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                RobotConfig _v;
                _v = global::ET.RobotConfig.DeserializeRobotConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, RobotConfig> DataMap => _dataMap;
        public List<RobotConfig> DataList => _dataList;
        public Dictionary<int, RobotConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public RobotConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public RobotConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

