
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SeasonLevelConfig : BeanBase
    {
        public SeasonLevelConfig()
        {
        }


        public SeasonLevelConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            UpExp = _buf.ReadInt();
            Reward = _buf.ReadString();
            PripertySet = _buf.ReadString();

            PostInit();
        }

        public static SeasonLevelConfig DeserializeSeasonLevelConfig(ByteBuf _buf)
        {
            return new SeasonLevelConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 升级经验
        /// </summary>
        public int UpExp;

        /// <summary>
        /// 奖励
        /// </summary>
        public string Reward;

        /// <summary>
        /// 赛季属性
        /// </summary>
        public string PripertySet;


        public const int __ID__ = 328153315;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UpExp:" + UpExp + ","
            + "Reward:" + Reward + ","
            + "PripertySet:" + PripertySet + ","
            + "}";
        }

        partial void PostInit();
    }
}

