
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SeasonJingHeConfig : BeanBase
    {
        public SeasonJingHeConfig()
        {
        }


        public SeasonJingHeConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Cost = _buf.ReadString();
            AddProperty = _buf.ReadString();

            PostInit();
        }

        public static SeasonJingHeConfig DeserializeSeasonJingHeConfig(ByteBuf _buf)
        {
            return new SeasonJingHeConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 开启消耗
        /// </summary>
        public string Cost;

        /// <summary>
        /// 额外属性
        /// </summary>
        public string AddProperty;


        public const int __ID__ = 1219148954;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Cost:" + Cost + ","
            + "AddProperty:" + AddProperty + ","
            + "}";
        }

        partial void PostInit();
    }
}

