
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SkillAugmentOptionsConfig : BeanBase
    {
        public SkillAugmentOptionsConfig()
        {
        }


        public SkillAugmentOptionsConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Id_Ref = null;
            {int __n0 = _buf.ReadSize(); SkillAugmentIds1 = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SkillAugmentIds1[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); SkillAugmentIds2 = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SkillAugmentIds2[__index0] = __e0;}}

            PostInit();
        }

        public static SkillAugmentOptionsConfig DeserializeSkillAugmentOptionsConfig(ByteBuf _buf)
        {
            return new SkillAugmentOptionsConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        public SkillConfig Id_Ref { get; private set; }

        /// <summary>
        /// 第1个技能增幅Ids
        /// </summary>
        public int[] SkillAugmentIds1;

        /// <summary>
        /// 第2个技能增幅Ids
        /// </summary>
        public int[] SkillAugmentIds2;


        public const int __ID__ = -1420871616;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            Id_Ref = SkillConfigCategory.Instance.GetOrDefault(Id);
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "SkillAugmentIds1:" + Luban.StringUtil.CollectionToString(SkillAugmentIds1) + ","
            + "SkillAugmentIds2:" + Luban.StringUtil.CollectionToString(SkillAugmentIds2) + ","
            + "}";
        }

        partial void PostInit();
    }
}

