
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class SkillAugmentConfigCategory : Singleton<SkillAugmentConfigCategory>, IConfig
    {
        private readonly Dictionary<int, SkillAugmentConfig> _dataMap;
        private readonly List<SkillAugmentConfig> _dataList;

        public SkillAugmentConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SkillAugmentConfig>();
            _dataList = new List<SkillAugmentConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SkillAugmentConfig _v;
                _v = global::ET.SkillAugmentConfig.DeserializeSkillAugmentConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SkillAugmentConfig> DataMap => _dataMap;
        public List<SkillAugmentConfig> DataList => _dataList;
        public Dictionary<int, SkillAugmentConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public SkillAugmentConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public SkillAugmentConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

