
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SkillBuffConfig : BeanBase
    {
        public SkillBuffConfig()
        {
        }


        public SkillBuffConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            BuffName = _buf.ReadString();
            BroadcastType = _buf.ReadInt();
            BuffLv = _buf.ReadInt();
            Transfer = _buf.ReadInt();
            BuffIconType = _buf.ReadString();
            BuffIcon = _buf.ReadString();
            BuffTime = _buf.ReadInt();
            BuffDelayTime = _buf.ReadInt();
            BuffLoopTime = _buf.ReadInt();
            TargetType = _buf.ReadInt();
            BuffScript = _buf.ReadString();
            BuffType = _buf.ReadInt();
            BuffBenefitType = _buf.ReadInt();
            buffParameterType = _buf.ReadInt();
            buffParameterValue = _buf.ReadDouble();
            buffParameterValue2 = _buf.ReadString();
            buffParameterValueType = _buf.ReadInt();
            buffParameterValueDef = _buf.ReadInt();
            BuffAddClass = _buf.ReadInt();
            BuffAddClassMax = _buf.ReadInt();
            BuffAddSync = _buf.ReadInt();
            WeiYiBuffID = _buf.ReadString();
            DamgeType = _buf.ReadInt();
            DamgePro = _buf.ReadDouble();
            DamgeValue = _buf.ReadInt();
            IfImmediatelyUse = _buf.ReadInt();
            IfShowIconTips = _buf.ReadInt();
            BuffEffectID = _buf.ReadInt();
            BuffDescribe = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); BuffTargetType = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); BuffTargetType[__index0] = __e0;}}
            Remove = _buf.ReadInt();
            MoveAction = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); AddSkill = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); AddSkill[__index0] = __e0;}}
            DeadNoRemove = _buf.ReadInt();
            BuffToSkill = _buf.ReadString();

            PostInit();
        }

        public static SkillBuffConfig DeserializeSkillBuffConfig(ByteBuf _buf)
        {
            return new SkillBuffConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 状态名称
        /// </summary>
        public string BuffName;

        /// <summary>
        /// 广播目标类型
        /// </summary>
        public int BroadcastType;

        /// <summary>
        /// Buff等级
        /// </summary>
        public int BuffLv;

        /// <summary>
        /// 切换场景保留
        /// </summary>
        public int Transfer;

        /// <summary>
        /// Buff图标类型
        /// </summary>
        public string BuffIconType;

        /// <summary>
        /// Buff图标
        /// </summary>
        public string BuffIcon;

        /// <summary>
        /// Buff存在时间
        /// </summary>
        public int BuffTime;

        /// <summary>
        /// Buff延迟生效时间
        /// </summary>
        public int BuffDelayTime;

        /// <summary>
        /// 循环触发时间
        /// </summary>
        public int BuffLoopTime;

        /// <summary>
        /// Buff目标类型
        /// </summary>
        public int TargetType;

        /// <summary>
        /// Buff脚本
        /// </summary>
        public string BuffScript;

        /// <summary>
        /// Buff类型
        /// </summary>
        public int BuffType;

        /// <summary>
        /// Buff增益减益
        /// </summary>
        public int BuffBenefitType;

        /// <summary>
        /// Buff参数操作类型
        /// </summary>
        public int buffParameterType;

        /// <summary>
        /// Buff参数操作值
        /// </summary>
        public double buffParameterValue;

        /// <summary>
        /// Buff参数操作值2
        /// </summary>
        public string buffParameterValue2;

        /// <summary>
        /// buff操作参数值类型
        /// </summary>
        public int buffParameterValueType;

        /// <summary>
        /// buff操作参数值类型定义
        /// </summary>
        public int buffParameterValueDef;

        /// <summary>
        /// Buff是否叠加
        /// </summary>
        public int BuffAddClass;

        /// <summary>
        /// Buff是叠加层数上限
        /// </summary>
        public int BuffAddClassMax;

        /// <summary>
        /// buff叠加后时间统一
        /// </summary>
        public int BuffAddSync;

        /// <summary>
        /// 唯一buffID
        /// </summary>
        public string WeiYiBuffID;

        /// <summary>
        /// 伤害类型
        /// </summary>
        public int DamgeType;

        /// <summary>
        /// 伤害系数
        /// </summary>
        public double DamgePro;

        /// <summary>
        /// 固定伤害值
        /// </summary>
        public int DamgeValue;

        /// <summary>
        /// 是否立即释放
        /// </summary>
        public int IfImmediatelyUse;

        /// <summary>
        /// 是否在主界面显示BuffIcon
        /// </summary>
        public int IfShowIconTips;

        /// <summary>
        /// buff特效
        /// </summary>
        public int BuffEffectID;

        /// <summary>
        /// Buff描述
        /// </summary>
        public string BuffDescribe;

        /// <summary>
        /// 附加目标类型
        /// </summary>
        public int[] BuffTargetType;

        /// <summary>
        /// 移除机制
        /// </summary>
        public int Remove;

        /// <summary>
        /// 移动触发
        /// </summary>
        public int MoveAction;

        /// <summary>
        /// 叠加层数触发技能
        /// </summary>
        public int[] AddSkill;

        /// <summary>
        /// 被击杀后是否移除机制
        /// </summary>
        public int DeadNoRemove;

        /// <summary>
        /// 触发技能
        /// </summary>
        public string BuffToSkill;


        public const int __ID__ = 458187398;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "BuffName:" + BuffName + ","
            + "BroadcastType:" + BroadcastType + ","
            + "BuffLv:" + BuffLv + ","
            + "Transfer:" + Transfer + ","
            + "BuffIconType:" + BuffIconType + ","
            + "BuffIcon:" + BuffIcon + ","
            + "BuffTime:" + BuffTime + ","
            + "BuffDelayTime:" + BuffDelayTime + ","
            + "BuffLoopTime:" + BuffLoopTime + ","
            + "TargetType:" + TargetType + ","
            + "BuffScript:" + BuffScript + ","
            + "BuffType:" + BuffType + ","
            + "BuffBenefitType:" + BuffBenefitType + ","
            + "buffParameterType:" + buffParameterType + ","
            + "buffParameterValue:" + buffParameterValue + ","
            + "buffParameterValue2:" + buffParameterValue2 + ","
            + "buffParameterValueType:" + buffParameterValueType + ","
            + "buffParameterValueDef:" + buffParameterValueDef + ","
            + "BuffAddClass:" + BuffAddClass + ","
            + "BuffAddClassMax:" + BuffAddClassMax + ","
            + "BuffAddSync:" + BuffAddSync + ","
            + "WeiYiBuffID:" + WeiYiBuffID + ","
            + "DamgeType:" + DamgeType + ","
            + "DamgePro:" + DamgePro + ","
            + "DamgeValue:" + DamgeValue + ","
            + "IfImmediatelyUse:" + IfImmediatelyUse + ","
            + "IfShowIconTips:" + IfShowIconTips + ","
            + "BuffEffectID:" + BuffEffectID + ","
            + "BuffDescribe:" + BuffDescribe + ","
            + "BuffTargetType:" + Luban.StringUtil.CollectionToString(BuffTargetType) + ","
            + "Remove:" + Remove + ","
            + "MoveAction:" + MoveAction + ","
            + "AddSkill:" + Luban.StringUtil.CollectionToString(AddSkill) + ","
            + "DeadNoRemove:" + DeadNoRemove + ","
            + "BuffToSkill:" + BuffToSkill + ","
            + "}";
        }

        partial void PostInit();
    }
}

