
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class SkillWeaponConfigCategory : Singleton<SkillWeaponConfigCategory>, IConfig
    {
        private readonly Dictionary<int, SkillWeaponConfig> _dataMap;
        private readonly List<SkillWeaponConfig> _dataList;

        public SkillWeaponConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SkillWeaponConfig>();
            _dataList = new List<SkillWeaponConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SkillWeaponConfig _v;
                _v = global::ET.SkillWeaponConfig.DeserializeSkillWeaponConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SkillWeaponConfig> DataMap => _dataMap;
        public List<SkillWeaponConfig> DataList => _dataList;
        public Dictionary<int, SkillWeaponConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public SkillWeaponConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public SkillWeaponConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

