
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class SpiritConfigCategory : Singleton<SpiritConfigCategory>, IConfig
    {
        private readonly Dictionary<int, SpiritConfig> _dataMap;
        private readonly List<SpiritConfig> _dataList;

        public SpiritConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SpiritConfig>();
            _dataList = new List<SpiritConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                SpiritConfig _v;
                _v = global::ET.SpiritConfig.DeserializeSpiritConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, SpiritConfig> DataMap => _dataMap;
        public List<SpiritConfig> DataList => _dataList;
        public Dictionary<int, SpiritConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public SpiritConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public SpiritConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

