
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SpiritConfig : BeanBase
    {
        public SpiritConfig()
        {
        }


        public SpiritConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ChapterID = _buf.ReadInt();
            Icon = _buf.ReadString();
            Type = _buf.ReadInt();
            Name = _buf.ReadString();
            ModelID = _buf.ReadString();
            Proprety = _buf.ReadString();
            SkillID = _buf.ReadString();
            MonsterID = _buf.ReadInt();
            Des = _buf.ReadString();

            PostInit();
        }

        public static SpiritConfig DeserializeSpiritConfig(ByteBuf _buf)
        {
            return new SpiritConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 章节ID
        /// </summary>
        public int ChapterID;

        /// <summary>
        /// 精灵Icon
        /// </summary>
        public string Icon;

        /// <summary>
        /// 精灵类型
        /// </summary>
        public int Type;

        /// <summary>
        /// 精灵名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 精灵模型
        /// </summary>
        public string ModelID;

        /// <summary>
        /// 精灵属性
        /// </summary>
        public string Proprety;

        /// <summary>
        /// 主动触发技能
        /// </summary>
        public string SkillID;

        /// <summary>
        /// 掉落怪物
        /// </summary>
        public int MonsterID;

        /// <summary>
        /// 精灵描述
        /// </summary>
        public string Des;


        public const int __ID__ = -409839949;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ChapterID:" + ChapterID + ","
            + "Icon:" + Icon + ","
            + "Type:" + Type + ","
            + "Name:" + Name + ","
            + "ModelID:" + ModelID + ","
            + "Proprety:" + Proprety + ","
            + "SkillID:" + SkillID + ","
            + "MonsterID:" + MonsterID + ","
            + "Des:" + Des + ","
            + "}";
        }

        partial void PostInit();
    }
}

