
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class StoreSellConfig : BeanBase
    {
        public StoreSellConfig()
        {
        }


        public StoreSellConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            NextID = _buf.ReadInt();
            ShowRoleLvMin = _buf.ReadInt();
            ShowRoleLvMax = _buf.ReadInt();
            SellItemID = _buf.ReadInt();
            SellItemNum = _buf.ReadInt();
            SellType = _buf.ReadInt();
            SellValue = _buf.ReadInt();

            PostInit();
        }

        public static StoreSellConfig DeserializeStoreSellConfig(ByteBuf _buf)
        {
            return new StoreSellConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 下一级id
        /// </summary>
        public int NextID;

        /// <summary>
        /// 需要玩家显示最低等级
        /// </summary>
        public int ShowRoleLvMin;

        /// <summary>
        /// 需要玩家显示最高等级
        /// </summary>
        public int ShowRoleLvMax;

        /// <summary>
        /// 出售道具
        /// </summary>
        public int SellItemID;

        /// <summary>
        /// 出售道具
        /// </summary>
        public int SellItemNum;

        /// <summary>
        /// 出售货币种类
        /// </summary>
        public int SellType;

        /// <summary>
        /// 出售价格
        /// </summary>
        public int SellValue;


        public const int __ID__ = 1616683221;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "NextID:" + NextID + ","
            + "ShowRoleLvMin:" + ShowRoleLvMin + ","
            + "ShowRoleLvMax:" + ShowRoleLvMax + ","
            + "SellItemID:" + SellItemID + ","
            + "SellItemNum:" + SellItemNum + ","
            + "SellType:" + SellType + ","
            + "SellValue:" + SellValue + ","
            + "}";
        }

        partial void PostInit();
    }
}

