
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class TakeCardConfigCategory : Singleton<TakeCardConfigCategory>, IConfig
    {
        private readonly Dictionary<int, TakeCardConfig> _dataMap;
        private readonly List<TakeCardConfig> _dataList;

        public TakeCardConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TakeCardConfig>();
            _dataList = new List<TakeCardConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TakeCardConfig _v;
                _v = global::ET.TakeCardConfig.DeserializeTakeCardConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TakeCardConfig> DataMap => _dataMap;
        public List<TakeCardConfig> DataList => _dataList;
        public Dictionary<int, TakeCardConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public TakeCardConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TakeCardConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

