
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TakeCardRewardConfig : BeanBase
    {
        public TakeCardRewardConfig()
        {
        }


        public TakeCardRewardConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            RoseLvLimit = _buf.ReadInt();
            RewardItems = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); RewardDiamond = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); RewardDiamond[__index0] = __e0;}}

            PostInit();
        }

        public static TakeCardRewardConfig DeserializeTakeCardRewardConfig(ByteBuf _buf)
        {
            return new TakeCardRewardConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 抽卡次数
        /// </summary>
        public int RoseLvLimit;

        /// <summary>
        /// 奖励道具
        /// </summary>
        public string RewardItems;

        /// <summary>
        /// 奖励钻石
        /// </summary>
        public int[] RewardDiamond;


        public const int __ID__ = 368497992;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "RoseLvLimit:" + RoseLvLimit + ","
            + "RewardItems:" + RewardItems + ","
            + "RewardDiamond:" + Luban.StringUtil.CollectionToString(RewardDiamond) + ","
            + "}";
        }

        partial void PostInit();
    }
}

