
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TaskConfig : BeanBase
    {
        public TaskConfig()
        {
        }


        public TaskConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            TaskName = _buf.ReadString();
            TaskLv = _buf.ReadInt();
            TaskIcon = _buf.ReadString();
            TaskMaxLv = _buf.ReadInt();
            TaskType = _buf.ReadInt();
            TaskSonType = _buf.ReadInt();
            TriggerType = _buf.ReadInt();
            TriggerValue = _buf.ReadInt();
            NextTask = _buf.ReadInt();
            TaskExp = _buf.ReadInt();
            TaskCoin = _buf.ReadInt();
            EveryTaskRewardNum = _buf.ReadInt();
            RewardItem = _buf.ReadString();
            GetNpcID = _buf.ReadInt();
            CompleteNpcID = _buf.ReadInt();
            TargetType = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); Target = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Target[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); TargetValue = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); TargetValue[__index0] = __e0;}}
            TargetPosition = _buf.ReadInt();
            TaskDes = _buf.ReadString();
            Development = _buf.ReadInt();
            Weight = _buf.ReadInt();

            PostInit();
        }

        public static TaskConfig DeserializeTaskConfig(ByteBuf _buf)
        {
            return new TaskConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 任务名称
        /// </summary>
        public string TaskName;

        /// <summary>
        /// 任务等级
        /// </summary>
        public int TaskLv;

        /// <summary>
        /// 任务图标
        /// </summary>
        public string TaskIcon;

        /// <summary>
        /// 最大接取等级
        /// </summary>
        public int TaskMaxLv;

        /// <summary>
        /// 任务类型
        /// </summary>
        public int TaskType;

        /// <summary>
        /// 任务子类
        /// </summary>
        public int TaskSonType;

        /// <summary>
        /// 触发类型
        /// </summary>
        public int TriggerType;

        /// <summary>
        /// 触发值
        /// </summary>
        public int TriggerValue;

        /// <summary>
        /// 下个任务
        /// </summary>
        public int NextTask;

        /// <summary>
        /// 任务经验
        /// </summary>
        public int TaskExp;

        /// <summary>
        /// 任务金币
        /// </summary>
        public int TaskCoin;

        /// <summary>
        /// 活跃度
        /// </summary>
        public int EveryTaskRewardNum;

        /// <summary>
        /// 奖励道具ID
        /// </summary>
        public string RewardItem;

        /// <summary>
        /// 接取任务的NPC
        /// </summary>
        public int GetNpcID;

        /// <summary>
        /// 交任务的Npc
        /// </summary>
        public int CompleteNpcID;

        /// <summary>
        /// 目标类型
        /// </summary>
        public int TargetType;

        /// <summary>
        /// 目标ID
        /// </summary>
        public int[] Target;

        /// <summary>
        /// 目标值
        /// </summary>
        public int[] TargetValue;

        /// <summary>
        /// 目标点
        /// </summary>
        public int TargetPosition;

        /// <summary>
        /// 任务描述
        /// </summary>
        public string TaskDes;

        /// <summary>
        /// 任务经验和金币是否跟随等级成长
        /// </summary>
        public int Development;

        /// <summary>
        /// 权重
        /// </summary>
        public int Weight;


        public const int __ID__ = -1794275001;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TaskName:" + TaskName + ","
            + "TaskLv:" + TaskLv + ","
            + "TaskIcon:" + TaskIcon + ","
            + "TaskMaxLv:" + TaskMaxLv + ","
            + "TaskType:" + TaskType + ","
            + "TaskSonType:" + TaskSonType + ","
            + "TriggerType:" + TriggerType + ","
            + "TriggerValue:" + TriggerValue + ","
            + "NextTask:" + NextTask + ","
            + "TaskExp:" + TaskExp + ","
            + "TaskCoin:" + TaskCoin + ","
            + "EveryTaskRewardNum:" + EveryTaskRewardNum + ","
            + "RewardItem:" + RewardItem + ","
            + "GetNpcID:" + GetNpcID + ","
            + "CompleteNpcID:" + CompleteNpcID + ","
            + "TargetType:" + TargetType + ","
            + "Target:" + Luban.StringUtil.CollectionToString(Target) + ","
            + "TargetValue:" + Luban.StringUtil.CollectionToString(TargetValue) + ","
            + "TargetPosition:" + TargetPosition + ","
            + "TaskDes:" + TaskDes + ","
            + "Development:" + Development + ","
            + "Weight:" + Weight + ","
            + "}";
        }

        partial void PostInit();
    }
}

