
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ZuoQiConfigCategory : Singleton<ZuoQiConfigCategory>, IConfig
    {
        private readonly Dictionary<int, ZuoQiConfig> _dataMap;
        private readonly List<ZuoQiConfig> _dataList;

        public ZuoQiConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ZuoQiConfig>();
            _dataList = new List<ZuoQiConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ZuoQiConfig _v;
                _v = global::ET.ZuoQiConfig.DeserializeZuoQiConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ZuoQiConfig> DataMap => _dataMap;
        public List<ZuoQiConfig> DataList => _dataList;
        public Dictionary<int, ZuoQiConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public ZuoQiConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public ZuoQiConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

