
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ZuoQiNengLiConfigCategory : Singleton<ZuoQiNengLiConfigCategory>, IConfig
    {
        private readonly Dictionary<int, ZuoQiNengLiConfig> _dataMap;
        private readonly List<ZuoQiNengLiConfig> _dataList;

        public ZuoQiNengLiConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ZuoQiNengLiConfig>();
            _dataList = new List<ZuoQiNengLiConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ZuoQiNengLiConfig _v;
                _v = global::ET.ZuoQiNengLiConfig.DeserializeZuoQiNengLiConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ZuoQiNengLiConfig> DataMap => _dataMap;
        public List<ZuoQiNengLiConfig> DataList => _dataList;
        public Dictionary<int, ZuoQiNengLiConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public ZuoQiNengLiConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public ZuoQiNengLiConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

