
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ZuoQiNengLiConfig : BeanBase
    {
        public ZuoQiNengLiConfig()
        {
        }


        public ZuoQiNengLiConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Icon = _buf.ReadString();
            NextID = _buf.ReadInt();
            Lv = _buf.ReadInt();
            Exp = _buf.ReadInt();
            UpCostItemID = _buf.ReadInt();
            UpCostZiJin = _buf.ReadInt();
            UpCostGold = _buf.ReadInt();
            UpAddExp = _buf.ReadInt();
            AddProperty = _buf.ReadString();

            PostInit();
        }

        public static ZuoQiNengLiConfig DeserializeZuoQiNengLiConfig(ByteBuf _buf)
        {
            return new ZuoQiNengLiConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 图标显示
        /// </summary>
        public string Icon;

        /// <summary>
        /// 下一级ID
        /// </summary>
        public int NextID;

        /// <summary>
        /// 等级
        /// </summary>
        public int Lv;

        /// <summary>
        /// 经验值
        /// </summary>
        public int Exp;

        /// <summary>
        /// 升级消耗
        /// </summary>
        public int UpCostItemID;

        /// <summary>
        /// 升级消耗
        /// </summary>
        public int UpCostZiJin;

        /// <summary>
        /// 升级消耗
        /// </summary>
        public int UpCostGold;

        /// <summary>
        /// 升级经验
        /// </summary>
        public int UpAddExp;

        /// <summary>
        /// 坐骑能力等级属性
        /// </summary>
        public string AddProperty;


        public const int __ID__ = 1808677051;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Icon:" + Icon + ","
            + "NextID:" + NextID + ","
            + "Lv:" + Lv + ","
            + "Exp:" + Exp + ","
            + "UpCostItemID:" + UpCostItemID + ","
            + "UpCostZiJin:" + UpCostZiJin + ","
            + "UpCostGold:" + UpCostGold + ","
            + "UpAddExp:" + UpAddExp + ","
            + "AddProperty:" + AddProperty + ","
            + "}";
        }

        partial void PostInit();
    }
}

