
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ZuoQiShowConfig : BeanBase
    {
        public ZuoQiShowConfig()
        {
        }


        public ZuoQiShowConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Quality = _buf.ReadInt();
            Icon = _buf.ReadString();
            ModelID = _buf.ReadString();
            TuoWeiEffectID = _buf.ReadString();
            Des = _buf.ReadString();
            AddPropertyDes = _buf.ReadString();
            AddProperty = _buf.ReadString();
            GetDes = _buf.ReadString();
            MoveBuffID = _buf.ReadInt();
            NameShowUp = _buf.ReadDouble();

            PostInit();
        }

        public static ZuoQiShowConfig DeserializeZuoQiShowConfig(ByteBuf _buf)
        {
            return new ZuoQiShowConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 品质
        /// </summary>
        public int Quality;

        /// <summary>
        /// 图标显示
        /// </summary>
        public string Icon;

        /// <summary>
        /// 模型ID
        /// </summary>
        public string ModelID;

        /// <summary>
        /// 拖尾特效名称
        /// </summary>
        public string TuoWeiEffectID;

        /// <summary>
        /// 描述
        /// </summary>
        public string Des;

        /// <summary>
        /// 属性描述
        /// </summary>
        public string AddPropertyDes;

        /// <summary>
        /// 额外属性
        /// </summary>
        public string AddProperty;

        /// <summary>
        /// 描述
        /// </summary>
        public string GetDes;

        /// <summary>
        /// 对应骑乘Buff
        /// </summary>
        public int MoveBuffID;

        /// <summary>
        /// 玩家名称显示上移
        /// </summary>
        public double NameShowUp;


        public const int __ID__ = 1195125611;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Quality:" + Quality + ","
            + "Icon:" + Icon + ","
            + "ModelID:" + ModelID + ","
            + "TuoWeiEffectID:" + TuoWeiEffectID + ","
            + "Des:" + Des + ","
            + "AddPropertyDes:" + AddPropertyDes + ","
            + "AddProperty:" + AddProperty + ","
            + "GetDes:" + GetDes + ","
            + "MoveBuffID:" + MoveBuffID + ","
            + "NameShowUp:" + NameShowUp + ","
            + "}";
        }

        partial void PostInit();
    }
}

