
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class BattleSummonConfigCategory : Singleton<BattleSummonConfigCategory>, IConfig
    {
        private readonly Dictionary<int, BattleSummonConfig> _dataMap;
        private readonly List<BattleSummonConfig> _dataList;

        public BattleSummonConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BattleSummonConfig>();
            _dataList = new List<BattleSummonConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BattleSummonConfig _v;
                _v = global::ET.BattleSummonConfig.DeserializeBattleSummonConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, BattleSummonConfig> DataMap => _dataMap;
        public List<BattleSummonConfig> DataList => _dataList;
        public Dictionary<int, BattleSummonConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public BattleSummonConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public BattleSummonConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

