
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CampLieShouConfig : BeanBase
    {
        public CampLieShouConfig()
        {
        }


        public CampLieShouConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            TaskName = _buf.ReadString();
            TargetType = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); Target = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Target[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); TargetValue = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); TargetValue[__index0] = __e0;}}

            PostInit();
        }

        public static CampLieShouConfig DeserializeCampLieShouConfig(ByteBuf _buf)
        {
            return new CampLieShouConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 任务名称
        /// </summary>
        public string TaskName;

        /// <summary>
        /// 目标类型
        /// </summary>
        public int TargetType;

        /// <summary>
        /// 目标ID
        /// </summary>
        public int[] Target;

        /// <summary>
        /// 目标值
        /// </summary>
        public int[] TargetValue;


        public const int __ID__ = 2101912996;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TaskName:" + TaskName + ","
            + "TargetType:" + TargetType + ","
            + "Target:" + Luban.StringUtil.CollectionToString(Target) + ","
            + "TargetValue:" + Luban.StringUtil.CollectionToString(TargetValue) + ","
            + "}";
        }

        partial void PostInit();
    }
}

