
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CampFuLiConfig : BeanBase
    {
        public CampFuLiConfig()
        {
        }


        public CampFuLiConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Postion = _buf.ReadString();
            Win_Reward = _buf.ReadInt();
            Fail_Reward = _buf.ReadInt();

            PostInit();
        }

        public static CampFuLiConfig DeserializeCampFuLiConfig(ByteBuf _buf)
        {
            return new CampFuLiConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 职位
        /// </summary>
        public string Postion;

        /// <summary>
        /// 胜利阵营币
        /// </summary>
        public int Win_Reward;

        /// <summary>
        /// 失败阵营币
        /// </summary>
        public int Fail_Reward;


        public const int __ID__ = 2024444559;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Postion:" + Postion + ","
            + "Win_Reward:" + Win_Reward + ","
            + "Fail_Reward:" + Fail_Reward + ","
            + "}";
        }

        partial void PostInit();
    }
}

