
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CampRewardConfig : BeanBase
    {
        public CampRewardConfig()
        {
        }


        public CampRewardConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); RankRange = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); RankRange[__index0] = __e0;}}
            Win_RewardList = _buf.ReadString();
            Fail_RewardList = _buf.ReadString();

            PostInit();
        }

        public static CampRewardConfig DeserializeCampRewardConfig(ByteBuf _buf)
        {
            return new CampRewardConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名次
        /// </summary>
        public int[] RankRange;

        /// <summary>
        /// 胜利奖励
        /// </summary>
        public string Win_RewardList;

        /// <summary>
        /// 失败奖励
        /// </summary>
        public string Fail_RewardList;


        public const int __ID__ = -266422126;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "RankRange:" + Luban.StringUtil.CollectionToString(RankRange) + ","
            + "Win_RewardList:" + Win_RewardList + ","
            + "Fail_RewardList:" + Fail_RewardList + ","
            + "}";
        }

        partial void PostInit();
    }
}

