
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class CampRewardConfigCategory : Singleton<CampRewardConfigCategory>, IConfig
    {
        private readonly Dictionary<int, CampRewardConfig> _dataMap;
        private readonly List<CampRewardConfig> _dataList;

        public CampRewardConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, CampRewardConfig>();
            _dataList = new List<CampRewardConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                CampRewardConfig _v;
                _v = global::ET.CampRewardConfig.DeserializeCampRewardConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, CampRewardConfig> DataMap => _dataMap;
        public List<CampRewardConfig> DataList => _dataList;
        public Dictionary<int, CampRewardConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public CampRewardConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public CampRewardConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

