
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class CellChapterConfig : BeanBase
    {
        public CellChapterConfig()
        {
        }


        public CellChapterConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ChapterName = _buf.ReadString();
            Name = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); RandomArea = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); RandomArea[__index0] = __e0;}}

            PostInit();
        }

        public static CellChapterConfig DeserializeCellChapterConfig(ByteBuf _buf)
        {
            return new CellChapterConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 章节名称
        /// </summary>
        public string ChapterName;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 章节关卡
        /// </summary>
        public int[] RandomArea;


        public const int __ID__ = 1449554829;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ChapterName:" + ChapterName + ","
            + "Name:" + Name + ","
            + "RandomArea:" + Luban.StringUtil.CollectionToString(RandomArea) + ","
            + "}";
        }

        partial void PostInit();
    }
}

