
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ChengJiuRewardConfig : BeanBase
    {
        public ChengJiuRewardConfig()
        {
        }


        public ChengJiuRewardConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            NeedPoint = _buf.ReadInt();
            RewardItems = _buf.ReadString();
            Icon = _buf.ReadInt();
            Desc = _buf.ReadString();

            PostInit();
        }

        public static ChengJiuRewardConfig DeserializeChengJiuRewardConfig(ByteBuf _buf)
        {
            return new ChengJiuRewardConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 需要成就点
        /// </summary>
        public int NeedPoint;

        /// <summary>
        /// 奖励
        /// </summary>
        public string RewardItems;

        /// <summary>
        /// 成就Icon
        /// </summary>
        public int Icon;

        /// <summary>
        /// 成就描述
        /// </summary>
        public string Desc;


        public const int __ID__ = 438421006;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "NeedPoint:" + NeedPoint + ","
            + "RewardItems:" + RewardItems + ","
            + "Icon:" + Icon + ","
            + "Desc:" + Desc + ","
            + "}";
        }

        partial void PostInit();
    }
}

