
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ChengJiuRewardConfigCategory : Singleton<ChengJiuRewardConfigCategory>, IConfig
    {
        private readonly Dictionary<int, ChengJiuRewardConfig> _dataMap;
        private readonly List<ChengJiuRewardConfig> _dataList;

        public ChengJiuRewardConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ChengJiuRewardConfig>();
            _dataList = new List<ChengJiuRewardConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ChengJiuRewardConfig _v;
                _v = global::ET.ChengJiuRewardConfig.DeserializeChengJiuRewardConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ChengJiuRewardConfig> DataMap => _dataMap;
        public List<ChengJiuRewardConfig> DataList => _dataList;
        public Dictionary<int, ChengJiuRewardConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public ChengJiuRewardConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public ChengJiuRewardConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

