
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class DungeonConfig : BeanBase
    {
        public DungeonConfig()
        {
        }


        public DungeonConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ChapterName = _buf.ReadString();
            Music = _buf.ReadString();
            MapType = _buf.ReadInt();
            EnterLv = _buf.ReadInt();
            BossIcon = _buf.ReadInt();
            ChapterDes = _buf.ReadString();
            MapID = _buf.ReadInt();
            LoadingRes = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); BornPosLeft = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); BornPosLeft[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); CameraPos = new double[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { double __e0;__e0 = _buf.ReadDouble(); CameraPos[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); TransmitPos = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); TransmitPos[__index0] = __e0;}}
            AutoPath = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); NpcList = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); NpcList[__index0] = __e0;}}
            MonsterPosition = _buf.ReadInt();
            ChapterId = _buf.ReadInt();

            PostInit();
        }

        public static DungeonConfig DeserializeDungeonConfig(ByteBuf _buf)
        {
            return new DungeonConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 章节名称
        /// </summary>
        public string ChapterName;

        /// <summary>
        /// 音乐
        /// </summary>
        public string Music;

        /// <summary>
        /// 个人副本类型
        /// </summary>
        public int MapType;

        /// <summary>
        /// 进入等级限制
        /// </summary>
        public int EnterLv;

        /// <summary>
        /// 章节BossIcon
        /// </summary>
        public int BossIcon;

        /// <summary>
        /// 章节文本描述
        /// </summary>
        public string ChapterDes;

        /// <summary>
        /// 地图ID
        /// </summary>
        public int MapID;

        /// <summary>
        /// loading图
        /// </summary>
        public string LoadingRes;

        /// <summary>
        /// 出生点
        /// </summary>
        public int[] BornPosLeft;

        /// <summary>
        /// 摄像机参数
        /// </summary>
        public double[] CameraPos;

        /// <summary>
        /// 传送点
        /// </summary>
        public int[] TransmitPos;

        /// <summary>
        /// 寻路
        /// </summary>
        public string AutoPath;

        /// <summary>
        /// NPC
        /// </summary>
        public int[] NpcList;

        /// <summary>
        /// 野怪
        /// </summary>
        public int MonsterPosition;

        /// <summary>
        /// 对应章节
        /// </summary>
        public int ChapterId;


        public const int __ID__ = -536623492;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ChapterName:" + ChapterName + ","
            + "Music:" + Music + ","
            + "MapType:" + MapType + ","
            + "EnterLv:" + EnterLv + ","
            + "BossIcon:" + BossIcon + ","
            + "ChapterDes:" + ChapterDes + ","
            + "MapID:" + MapID + ","
            + "LoadingRes:" + LoadingRes + ","
            + "BornPosLeft:" + Luban.StringUtil.CollectionToString(BornPosLeft) + ","
            + "CameraPos:" + Luban.StringUtil.CollectionToString(CameraPos) + ","
            + "TransmitPos:" + Luban.StringUtil.CollectionToString(TransmitPos) + ","
            + "AutoPath:" + AutoPath + ","
            + "NpcList:" + Luban.StringUtil.CollectionToString(NpcList) + ","
            + "MonsterPosition:" + MonsterPosition + ","
            + "ChapterId:" + ChapterId + ","
            + "}";
        }

        partial void PostInit();
    }
}

