
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class EffectConfig : BeanBase
    {
        public EffectConfig()
        {
        }


        public EffectConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            EffectType = _buf.ReadInt();
            IfFollowCollider = _buf.ReadInt();
            EffectName = _buf.ReadString();
            SkillEffectDelayTime = _buf.ReadDouble();
            SkillParent = _buf.ReadInt();
            SkillParentPosition = _buf.ReadString();
            HideTime = _buf.ReadInt();
            SkillEffectLiveTime = _buf.ReadInt();
            PlayType = _buf.ReadInt();
            Scale = _buf.ReadDouble();

            PostInit();
        }

        public static EffectConfig DeserializeEffectConfig(ByteBuf _buf)
        {
            return new EffectConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 特效类型
        /// </summary>
        public int EffectType;

        /// <summary>
        /// 特效是否跟随绑定
        /// </summary>
        public int IfFollowCollider;

        /// <summary>
        /// 特效名称
        /// </summary>
        public string EffectName;

        /// <summary>
        /// 技能效果延迟时间
        /// </summary>
        public double SkillEffectDelayTime;

        /// <summary>
        /// 绑定父级
        /// </summary>
        public int SkillParent;

        /// <summary>
        /// 绑定父级位置
        /// </summary>
        public string SkillParentPosition;

        /// <summary>
        /// 隐藏间隔时间
        /// </summary>
        public int HideTime;

        /// <summary>
        /// 技能特效存在时间[毫秒]
        /// </summary>
        public int SkillEffectLiveTime;

        /// <summary>
        /// 是否面向施法者播放特效
        /// </summary>
        public int PlayType;

        /// <summary>
        /// 缩放
        /// </summary>
        public double Scale;


        public const int __ID__ = -682668973;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "EffectType:" + EffectType + ","
            + "IfFollowCollider:" + IfFollowCollider + ","
            + "EffectName:" + EffectName + ","
            + "SkillEffectDelayTime:" + SkillEffectDelayTime + ","
            + "SkillParent:" + SkillParent + ","
            + "SkillParentPosition:" + SkillParentPosition + ","
            + "HideTime:" + HideTime + ","
            + "SkillEffectLiveTime:" + SkillEffectLiveTime + ","
            + "PlayType:" + PlayType + ","
            + "Scale:" + Scale + ","
            + "}";
        }

        partial void PostInit();
    }
}

