
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class EquipSuitConfigCategory : Singleton<EquipSuitConfigCategory>, IConfig
    {
        private readonly Dictionary<int, EquipSuitConfig> _dataMap;
        private readonly List<EquipSuitConfig> _dataList;

        public EquipSuitConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, EquipSuitConfig>();
            _dataList = new List<EquipSuitConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                EquipSuitConfig _v;
                _v = global::ET.EquipSuitConfig.DeserializeEquipSuitConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, EquipSuitConfig> DataMap => _dataMap;
        public List<EquipSuitConfig> DataList => _dataList;
        public Dictionary<int, EquipSuitConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public EquipSuitConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public EquipSuitConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

