
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class EquipMakeConfigCategory : Singleton<EquipMakeConfigCategory>, IConfig
    {
        private readonly Dictionary<int, EquipMakeConfig> _dataMap;
        private readonly List<EquipMakeConfig> _dataList;

        public EquipMakeConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, EquipMakeConfig>();
            _dataList = new List<EquipMakeConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                EquipMakeConfig _v;
                _v = global::ET.EquipMakeConfig.DeserializeEquipMakeConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, EquipMakeConfig> DataMap => _dataMap;
        public List<EquipMakeConfig> DataList => _dataList;
        public Dictionary<int, EquipMakeConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public EquipMakeConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public EquipMakeConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

