
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ExpConfigCategory : Singleton<ExpConfigCategory>, IConfig
    {
        private readonly Dictionary<int, ExpConfig> _dataMap;
        private readonly List<ExpConfig> _dataList;

        public ExpConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ExpConfig>();
            _dataList = new List<ExpConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ExpConfig _v;
                _v = global::ET.ExpConfig.DeserializeExpConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ExpConfig> DataMap => _dataMap;
        public List<ExpConfig> DataList => _dataList;
        public Dictionary<int, ExpConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public ExpConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public ExpConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

