
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class FashionConfigCategory : Singleton<FashionConfigCategory>, IConfig
    {
        private readonly Dictionary<int, FashionConfig> _dataMap;
        private readonly List<FashionConfig> _dataList;

        public FashionConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, FashionConfig>();
            _dataList = new List<FashionConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                FashionConfig _v;
                _v = global::ET.FashionConfig.DeserializeFashionConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, FashionConfig> DataMap => _dataMap;
        public List<FashionConfig> DataList => _dataList;
        public Dictionary<int, FashionConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public FashionConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public FashionConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

