
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class FuntionConfigCategory : Singleton<FuntionConfigCategory>, IConfig
    {
        private readonly Dictionary<int, FuntionConfig> _dataMap;
        private readonly List<FuntionConfig> _dataList;

        public FuntionConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, FuntionConfig>();
            _dataList = new List<FuntionConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                FuntionConfig _v;
                _v = global::ET.FuntionConfig.DeserializeFuntionConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, FuntionConfig> DataMap => _dataMap;
        public List<FuntionConfig> DataList => _dataList;
        public Dictionary<int, FuntionConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public FuntionConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public FuntionConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

