
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class HuoYueRewardConfigCategory : Singleton<HuoYueRewardConfigCategory>, IConfig
    {
        private readonly Dictionary<int, HuoYueRewardConfig> _dataMap;
        private readonly List<HuoYueRewardConfig> _dataList;

        public HuoYueRewardConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, HuoYueRewardConfig>();
            _dataList = new List<HuoYueRewardConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                HuoYueRewardConfig _v;
                _v = global::ET.HuoYueRewardConfig.DeserializeHuoYueRewardConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, HuoYueRewardConfig> DataMap => _dataMap;
        public List<HuoYueRewardConfig> DataList => _dataList;
        public Dictionary<int, HuoYueRewardConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public HuoYueRewardConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public HuoYueRewardConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

