
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class JiaYuanFarmConfigCategory : Singleton<JiaYuanFarmConfigCategory>, IConfig
    {
        private readonly Dictionary<int, JiaYuanFarmConfig> _dataMap;
        private readonly List<JiaYuanFarmConfig> _dataList;

        public JiaYuanFarmConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, JiaYuanFarmConfig>();
            _dataList = new List<JiaYuanFarmConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                JiaYuanFarmConfig _v;
                _v = global::ET.JiaYuanFarmConfig.DeserializeJiaYuanFarmConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, JiaYuanFarmConfig> DataMap => _dataMap;
        public List<JiaYuanFarmConfig> DataList => _dataList;
        public Dictionary<int, JiaYuanFarmConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public JiaYuanFarmConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public JiaYuanFarmConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

