
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class JiaYuanFarmConfig : BeanBase
    {
        public JiaYuanFarmConfig()
        {
        }


        public JiaYuanFarmConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Lv = _buf.ReadInt();
            ModelID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); UpTime = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); UpTime[__index0] = __e0;}}
            PeopleNum = _buf.ReadInt();
            BuyGold = _buf.ReadInt();
            SellGold = _buf.ReadInt();
            GetItemID = _buf.ReadInt();
            Speak = _buf.ReadString();
            Des = _buf.ReadString();
            GetItemTime = _buf.ReadInt();
            GetItemNum = _buf.ReadInt();

            PostInit();
        }

        public static JiaYuanFarmConfig DeserializeJiaYuanFarmConfig(ByteBuf _buf)
        {
            return new JiaYuanFarmConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 等级
        /// </summary>
        public int Lv;

        /// <summary>
        /// 模型ID
        /// </summary>
        public int ModelID;

        /// <summary>
        /// 成长时间
        /// </summary>
        public int[] UpTime;

        /// <summary>
        /// 人口数量
        /// </summary>
        public int PeopleNum;

        /// <summary>
        /// 购买价格
        /// </summary>
        public int BuyGold;

        /// <summary>
        /// 出售价格
        /// </summary>
        public int SellGold;

        /// <summary>
        /// 收获道具ID
        /// </summary>
        public int GetItemID;

        /// <summary>
        /// 描述
        /// </summary>
        public string Speak;

        /// <summary>
        /// 描述
        /// </summary>
        public string Des;

        /// <summary>
        /// 收货间隔时间
        /// </summary>
        public int GetItemTime;

        /// <summary>
        /// 收货次数上限
        /// </summary>
        public int GetItemNum;


        public const int __ID__ = -1986552893;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Lv:" + Lv + ","
            + "ModelID:" + ModelID + ","
            + "UpTime:" + Luban.StringUtil.CollectionToString(UpTime) + ","
            + "PeopleNum:" + PeopleNum + ","
            + "BuyGold:" + BuyGold + ","
            + "SellGold:" + SellGold + ","
            + "GetItemID:" + GetItemID + ","
            + "Speak:" + Speak + ","
            + "Des:" + Des + ","
            + "GetItemTime:" + GetItemTime + ","
            + "GetItemNum:" + GetItemNum + ","
            + "}";
        }

        partial void PostInit();
    }
}

