
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class JiaYuanConfigCategory : Singleton<JiaYuanConfigCategory>, IConfig
    {
        private readonly Dictionary<int, JiaYuanConfig> _dataMap;
        private readonly List<JiaYuanConfig> _dataList;

        public JiaYuanConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, JiaYuanConfig>();
            _dataList = new List<JiaYuanConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                JiaYuanConfig _v;
                _v = global::ET.JiaYuanConfig.DeserializeJiaYuanConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, JiaYuanConfig> DataMap => _dataMap;
        public List<JiaYuanConfig> DataList => _dataList;
        public Dictionary<int, JiaYuanConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public JiaYuanConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public JiaYuanConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

