
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class JingLingConfig : BeanBase
    {
        public JingLingConfig()
        {
        }


        public JingLingConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            GetWay = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); GetValue = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); GetValue[__index0] = __e0;}}
            NeedPoint = _buf.ReadInt();
            ActivePro = _buf.ReadDouble();
            JingLingType = _buf.ReadInt();
            Icon = _buf.ReadInt();
            Assets = _buf.ReadString();
            AddProperty = _buf.ReadString();
            AnimatorAsset = _buf.ReadString();
            AnimatorNumber = _buf.ReadInt();
            ValidityTime = _buf.ReadInt();
            Lv = _buf.ReadString();
            ProDes = _buf.ReadString();
            Des = _buf.ReadString();
            size = _buf.ReadDouble();
            MoveX = _buf.ReadDouble();
            MoveY = _buf.ReadDouble();
            GetDes = _buf.ReadString();
            FunctionType = _buf.ReadInt();
            FunctionValue = _buf.ReadString();
            AutoPick = _buf.ReadInt();
            ModelShowPosi = _buf.ReadString();

            PostInit();
        }

        public static JingLingConfig DeserializeJingLingConfig(ByteBuf _buf)
        {
            return new JingLingConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 获取方式
        /// </summary>
        public int GetWay;

        /// <summary>
        /// 获取参数
        /// </summary>
        public int[] GetValue;

        /// <summary>
        /// 激活点数
        /// </summary>
        public int NeedPoint;

        /// <summary>
        /// 激活概率
        /// </summary>
        public double ActivePro;

        /// <summary>
        /// 精灵类型
        /// </summary>
        public int JingLingType;

        /// <summary>
        /// 图标显示
        /// </summary>
        public int Icon;

        /// <summary>
        /// 模型
        /// </summary>
        public string Assets;

        /// <summary>
        /// 额外属性
        /// </summary>
        public string AddProperty;

        /// <summary>
        /// 序列帧动画
        /// </summary>
        public string AnimatorAsset;

        /// <summary>
        /// 序列帧动画数量
        /// </summary>
        public int AnimatorNumber;

        /// <summary>
        /// 有效期(秒)
        /// </summary>
        public int ValidityTime;

        /// <summary>
        /// 境界
        /// </summary>
        public string Lv;

        /// <summary>
        /// 属性描述
        /// </summary>
        public string ProDes;

        /// <summary>
        /// 额外属性描述
        /// </summary>
        public string Des;

        /// <summary>
        /// 缩放大小
        /// </summary>
        public double size;

        /// <summary>
        /// X偏移
        /// </summary>
        public double MoveX;

        /// <summary>
        /// Y便宜
        /// </summary>
        public double MoveY;

        /// <summary>
        /// 额外属性描述
        /// </summary>
        public string GetDes;

        /// <summary>
        /// 功能类型
        /// </summary>
        public int FunctionType;

        /// <summary>
        /// 功能参数
        /// </summary>
        public string FunctionValue;

        /// <summary>
        /// 自动拾取
        /// </summary>
        public int AutoPick;

        /// <summary>
        /// 怪物显示的位置
        /// </summary>
        public string ModelShowPosi;


        public const int __ID__ = 236558416;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "GetWay:" + GetWay + ","
            + "GetValue:" + Luban.StringUtil.CollectionToString(GetValue) + ","
            + "NeedPoint:" + NeedPoint + ","
            + "ActivePro:" + ActivePro + ","
            + "JingLingType:" + JingLingType + ","
            + "Icon:" + Icon + ","
            + "Assets:" + Assets + ","
            + "AddProperty:" + AddProperty + ","
            + "AnimatorAsset:" + AnimatorAsset + ","
            + "AnimatorNumber:" + AnimatorNumber + ","
            + "ValidityTime:" + ValidityTime + ","
            + "Lv:" + Lv + ","
            + "ProDes:" + ProDes + ","
            + "Des:" + Des + ","
            + "size:" + size + ","
            + "MoveX:" + MoveX + ","
            + "MoveY:" + MoveY + ","
            + "GetDes:" + GetDes + ","
            + "FunctionType:" + FunctionType + ","
            + "FunctionValue:" + FunctionValue + ","
            + "AutoPick:" + AutoPick + ","
            + "ModelShowPosi:" + ModelShowPosi + ","
            + "}";
        }

        partial void PostInit();
    }
}

