
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class LifeShieldConfigCategory : Singleton<LifeShieldConfigCategory>, IConfig
    {
        private readonly Dictionary<int, LifeShieldConfig> _dataMap;
        private readonly List<LifeShieldConfig> _dataList;

        public LifeShieldConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, LifeShieldConfig>();
            _dataList = new List<LifeShieldConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                LifeShieldConfig _v;
                _v = global::ET.LifeShieldConfig.DeserializeLifeShieldConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, LifeShieldConfig> DataMap => _dataMap;
        public List<LifeShieldConfig> DataList => _dataList;
        public Dictionary<int, LifeShieldConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public LifeShieldConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public LifeShieldConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

