
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MineBattleConfig : BeanBase
    {
        public MineBattleConfig()
        {
        }


        public MineBattleConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Type = _buf.ReadInt();
            Icon = _buf.ReadString();
            GoldOutPut = _buf.ReadInt();
            ChanChuLimit = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); PetDefendInit = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); PetDefendInit[__index0] = __e0;}}

            PostInit();
        }

        public static MineBattleConfig DeserializeMineBattleConfig(ByteBuf _buf)
        {
            return new MineBattleConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名字
        /// </summary>
        public string Name;

        /// <summary>
        /// 地图类型(未用)
        /// </summary>
        public int Type;

        /// <summary>
        /// 图标
        /// </summary>
        public string Icon;

        /// <summary>
        /// 金币产出/小时
        /// </summary>
        public int GoldOutPut;

        /// <summary>
        /// 上限
        /// </summary>
        public int ChanChuLimit;

        /// <summary>
        /// 默认守护
        /// </summary>
        public int[] PetDefendInit;


        public const int __ID__ = 1276325421;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Type:" + Type + ","
            + "Icon:" + Icon + ","
            + "GoldOutPut:" + GoldOutPut + ","
            + "ChanChuLimit:" + ChanChuLimit + ","
            + "PetDefendInit:" + Luban.StringUtil.CollectionToString(PetDefendInit) + ","
            + "}";
        }

        partial void PostInit();
    }
}

