
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class MonsterPositionConfigCategory : Singleton<MonsterPositionConfigCategory>, IConfig
    {
        private readonly Dictionary<int, MonsterPositionConfig> _dataMap;
        private readonly List<MonsterPositionConfig> _dataList;

        public MonsterPositionConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MonsterPositionConfig>();
            _dataList = new List<MonsterPositionConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                MonsterPositionConfig _v;
                _v = global::ET.MonsterPositionConfig.DeserializeMonsterPositionConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, MonsterPositionConfig> DataMap => _dataMap;
        public List<MonsterPositionConfig> DataList => _dataList;
        public Dictionary<int, MonsterPositionConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public MonsterPositionConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public MonsterPositionConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

