
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class OccupationTwoConfig : BeanBase
    {
        public OccupationTwoConfig()
        {
        }


        public OccupationTwoConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            OccupationName = _buf.ReadString();
            OccDes = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); SkillID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SkillID[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); ShowTalentSkill = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ShowTalentSkill[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); Capacitys = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Capacitys[__index0] = __e0;}}
            WeaponType = _buf.ReadInt();
            ArmorMastery = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); ShowPassiveSkill = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ShowPassiveSkill[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); JueXingSkill = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); JueXingSkill[__index0] = __e0;}}

            PostInit();
        }

        public static OccupationTwoConfig DeserializeOccupationTwoConfig(ByteBuf _buf)
        {
            return new OccupationTwoConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 职业名称
        /// </summary>
        public string OccupationName;

        /// <summary>
        /// 职业特点描述
        /// </summary>
        public string OccDes;

        /// <summary>
        /// 初始化技能ID
        /// </summary>
        public int[] SkillID;

        /// <summary>
        /// 转职显示技能
        /// </summary>
        public int[] ShowTalentSkill;

        /// <summary>
        /// 职业能力
        /// </summary>
        public int[] Capacitys;

        /// <summary>
        /// 武器类型
        /// </summary>
        public int WeaponType;

        /// <summary>
        /// 护甲专精
        /// </summary>
        public int ArmorMastery;

        /// <summary>
        /// 转职显示被动技能
        /// </summary>
        public int[] ShowPassiveSkill;

        /// <summary>
        /// 觉醒技能
        /// </summary>
        public int[] JueXingSkill;


        public const int __ID__ = -991032445;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "OccupationName:" + OccupationName + ","
            + "OccDes:" + OccDes + ","
            + "SkillID:" + Luban.StringUtil.CollectionToString(SkillID) + ","
            + "ShowTalentSkill:" + Luban.StringUtil.CollectionToString(ShowTalentSkill) + ","
            + "Capacitys:" + Luban.StringUtil.CollectionToString(Capacitys) + ","
            + "WeaponType:" + WeaponType + ","
            + "ArmorMastery:" + ArmorMastery + ","
            + "ShowPassiveSkill:" + Luban.StringUtil.CollectionToString(ShowPassiveSkill) + ","
            + "JueXingSkill:" + Luban.StringUtil.CollectionToString(JueXingSkill) + ","
            + "}";
        }

        partial void PostInit();
    }
}

