
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PetBarConfig : BeanBase
    {
        public PetBarConfig()
        {
        }


        public PetBarConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Level = _buf.ReadInt();
            CostItems = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); ActiveSkills = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ActiveSkills[__index0] = __e0;}}
            AddProperty = _buf.ReadString();

            PostInit();
        }

        public static PetBarConfig DeserializePetBarConfig(ByteBuf _buf)
        {
            return new PetBarConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 技能栏名字
        /// </summary>
        public string Name;

        /// <summary>
        /// 等级
        /// </summary>
        public int Level;

        /// <summary>
        /// 升级消耗
        /// </summary>
        public string CostItems;

        /// <summary>
        /// 激活技能
        /// </summary>
        public int[] ActiveSkills;

        /// <summary>
        /// 额外属性
        /// </summary>
        public string AddProperty;


        public const int __ID__ = 1948706550;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Level:" + Level + ","
            + "CostItems:" + CostItems + ","
            + "ActiveSkills:" + Luban.StringUtil.CollectionToString(ActiveSkills) + ","
            + "AddProperty:" + AddProperty + ","
            + "}";
        }

        partial void PostInit();
    }
}

