
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PetConfig : BeanBase
    {
        public PetConfig()
        {
        }


        public PetConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            PetName = _buf.ReadString();
            HeadIcon = _buf.ReadString();
            PetModel = _buf.ReadInt();
            PetBianYiID = _buf.ReadInt();
            ModelShowPosi = _buf.ReadString();
            PetType = _buf.ReadInt();
            PetLv = _buf.ReadInt();
            PetQuality = _buf.ReadInt();
            FightLv = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); InitStartNum = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); InitStartNum[__index0] = __e0;}}
            Base_PingFen = _buf.ReadString();
            PetRace = _buf.ReadInt();
            ZiZhi_Hp_Min = _buf.ReadInt();
            ZiZhi_Hp_Max = _buf.ReadInt();
            ZiZhi_Act_Min = _buf.ReadInt();
            ZiZhi_Act_Max = _buf.ReadInt();
            ZiZhi_MageAct_Min = _buf.ReadInt();
            ZiZhi_MageAct_Max = _buf.ReadInt();
            ZiZhi_Def_Min = _buf.ReadInt();
            ZiZhi_Def_Max = _buf.ReadInt();
            ZiZhi_Adf_Min = _buf.ReadInt();
            ZiZhi_Adf_Max = _buf.ReadInt();
            ZiZhi_ActSpeed_Min = _buf.ReadInt();
            ZiZhi_ActSpeed_Max = _buf.ReadInt();
            ZiZhi_ChengZhang_Min = _buf.ReadDouble();
            ZiZhi_ChengZhang_Max = _buf.ReadDouble();
            Base_Hp = _buf.ReadInt();
            Base_Act = _buf.ReadInt();
            Base_MageAct = _buf.ReadInt();
            Base_Def = _buf.ReadInt();
            Base_Adf = _buf.ReadInt();
            Base_Cri = _buf.ReadDouble();
            Base_Res = _buf.ReadInt();
            Base_Hit = _buf.ReadDouble();
            Base_Dodge = _buf.ReadDouble();
            Base_DefAdd = _buf.ReadInt();
            Base_AdfAdd = _buf.ReadInt();
            Base_DamgeAdd = _buf.ReadInt();
            Base_MoveSpeed = _buf.ReadInt();
            Base_ActSpeed = _buf.ReadDouble();
            ActDistance = _buf.ReadDouble();
            Lv_Hp = _buf.ReadDouble();
            Lv_Act = _buf.ReadDouble();
            Lv_MageAct = _buf.ReadDouble();
            Lv_Def = _buf.ReadDouble();
            Lv_Adf = _buf.ReadDouble();
            PatrolRange = _buf.ReadInt();
            ChaseRange = _buf.ReadInt();
            ActRunRange = _buf.ReadInt();
            Exp = _buf.ReadDouble();
            SelectSize = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); ReleaseReward = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ReleaseReward[__index0] = __e0;}}
            ZhuanZhuSkillID = _buf.ReadString();
            ActSkillID = _buf.ReadInt();
            BaseSkillID = _buf.ReadString();
            RandomSkillID = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); Skin = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Skin[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); SkinPro = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SkinPro[__index0] = __e0;}}
            AttackType = _buf.ReadInt();

            PostInit();
        }

        public static PetConfig DeserializePetConfig(ByteBuf _buf)
        {
            return new PetConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 宠物名称
        /// </summary>
        public string PetName;

        /// <summary>
        /// 头像Icon
        /// </summary>
        public string HeadIcon;

        /// <summary>
        /// 宠物Model
        /// </summary>
        public int PetModel;

        /// <summary>
        /// 洗炼变异
        /// </summary>
        public int PetBianYiID;

        /// <summary>
        /// 宠物显示的位置
        /// </summary>
        public string ModelShowPosi;

        /// <summary>
        /// 宠物类型
        /// </summary>
        public int PetType;

        /// <summary>
        /// 宠物等级
        /// </summary>
        public int PetLv;

        /// <summary>
        /// 宠物品质
        /// </summary>
        public int PetQuality;

        /// <summary>
        /// 出战等级
        /// </summary>
        public int FightLv;

        /// <summary>
        /// 默认星数
        /// </summary>
        public int[] InitStartNum;

        /// <summary>
        /// 基础评分
        /// </summary>
        public string Base_PingFen;

        /// <summary>
        /// 宠物种族
        /// </summary>
        public int PetRace;

        /// <summary>
        /// 血量资质
        /// </summary>
        public int ZiZhi_Hp_Min;

        /// <summary>
        /// 血量资质
        /// </summary>
        public int ZiZhi_Hp_Max;

        /// <summary>
        /// 攻击资质
        /// </summary>
        public int ZiZhi_Act_Min;

        /// <summary>
        /// 攻击资质
        /// </summary>
        public int ZiZhi_Act_Max;

        /// <summary>
        /// 攻击资质
        /// </summary>
        public int ZiZhi_MageAct_Min;

        /// <summary>
        /// 攻击资质
        /// </summary>
        public int ZiZhi_MageAct_Max;

        /// <summary>
        /// 物防资质
        /// </summary>
        public int ZiZhi_Def_Min;

        /// <summary>
        /// 物防资质
        /// </summary>
        public int ZiZhi_Def_Max;

        /// <summary>
        /// 法防资质
        /// </summary>
        public int ZiZhi_Adf_Min;

        /// <summary>
        /// 法防资质
        /// </summary>
        public int ZiZhi_Adf_Max;

        /// <summary>
        /// 攻速资质
        /// </summary>
        public int ZiZhi_ActSpeed_Min;

        /// <summary>
        /// 攻速资质
        /// </summary>
        public int ZiZhi_ActSpeed_Max;

        /// <summary>
        /// 成长资质
        /// </summary>
        public double ZiZhi_ChengZhang_Min;

        /// <summary>
        /// 成长资质
        /// </summary>
        public double ZiZhi_ChengZhang_Max;

        /// <summary>
        /// 血量
        /// </summary>
        public int Base_Hp;

        /// <summary>
        /// 攻击
        /// </summary>
        public int Base_Act;

        /// <summary>
        /// 魔法攻击
        /// </summary>
        public int Base_MageAct;

        /// <summary>
        /// 物防
        /// </summary>
        public int Base_Def;

        /// <summary>
        /// 魔防
        /// </summary>
        public int Base_Adf;

        /// <summary>
        /// 暴击
        /// </summary>
        public double Base_Cri;

        /// <summary>
        /// 抗暴
        /// </summary>
        public int Base_Res;

        /// <summary>
        /// 命中
        /// </summary>
        public double Base_Hit;

        /// <summary>
        /// 闪避
        /// </summary>
        public double Base_Dodge;

        /// <summary>
        /// 物理免伤
        /// </summary>
        public int Base_DefAdd;

        /// <summary>
        /// 魔法免伤
        /// </summary>
        public int Base_AdfAdd;

        /// <summary>
        /// 怪物免伤
        /// </summary>
        public int Base_DamgeAdd;

        /// <summary>
        /// 移动速度
        /// </summary>
        public int Base_MoveSpeed;

        /// <summary>
        /// 攻击速度
        /// </summary>
        public double Base_ActSpeed;

        /// <summary>
        /// 攻击距离
        /// </summary>
        public double ActDistance;

        /// <summary>
        /// 等级成长血量
        /// </summary>
        public double Lv_Hp;

        /// <summary>
        /// 等级成长攻击
        /// </summary>
        public double Lv_Act;

        /// <summary>
        /// 等级成长魔法攻击
        /// </summary>
        public double Lv_MageAct;

        /// <summary>
        /// 等级成长物防
        /// </summary>
        public double Lv_Def;

        /// <summary>
        /// 等级成长魔防
        /// </summary>
        public double Lv_Adf;

        /// <summary>
        /// 监视范围(未用)
        /// </summary>
        public int PatrolRange;

        /// <summary>
        /// 追击范围
        /// </summary>
        public int ChaseRange;

        /// <summary>
        /// 攻击范围(未用)
        /// </summary>
        public int ActRunRange;

        /// <summary>
        /// 抓捕狂暴概率
        /// </summary>
        public double Exp;

        /// <summary>
        /// 选中条大小
        /// </summary>
        public int SelectSize;

        /// <summary>
        /// 放生奖励
        /// </summary>
        public int[] ReleaseReward;

        /// <summary>
        /// 专注技能
        /// </summary>
        public string ZhuanZhuSkillID;

        /// <summary>
        /// 怪物普通攻击
        /// </summary>
        public int ActSkillID;

        /// <summary>
        /// 宠物必带技能ID
        /// </summary>
        public string BaseSkillID;

        /// <summary>
        /// 宠物随机技能ID
        /// </summary>
        public string RandomSkillID;

        /// <summary>
        /// 宠物皮肤
        /// </summary>
        public int[] Skin;

        /// <summary>
        /// 宠物皮肤激活概率
        /// </summary>
        public int[] SkinPro;

        /// <summary>
        /// 攻击方式
        /// </summary>
        public int AttackType;


        public const int __ID__ = -1036997343;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "PetName:" + PetName + ","
            + "HeadIcon:" + HeadIcon + ","
            + "PetModel:" + PetModel + ","
            + "PetBianYiID:" + PetBianYiID + ","
            + "ModelShowPosi:" + ModelShowPosi + ","
            + "PetType:" + PetType + ","
            + "PetLv:" + PetLv + ","
            + "PetQuality:" + PetQuality + ","
            + "FightLv:" + FightLv + ","
            + "InitStartNum:" + Luban.StringUtil.CollectionToString(InitStartNum) + ","
            + "Base_PingFen:" + Base_PingFen + ","
            + "PetRace:" + PetRace + ","
            + "ZiZhi_Hp_Min:" + ZiZhi_Hp_Min + ","
            + "ZiZhi_Hp_Max:" + ZiZhi_Hp_Max + ","
            + "ZiZhi_Act_Min:" + ZiZhi_Act_Min + ","
            + "ZiZhi_Act_Max:" + ZiZhi_Act_Max + ","
            + "ZiZhi_MageAct_Min:" + ZiZhi_MageAct_Min + ","
            + "ZiZhi_MageAct_Max:" + ZiZhi_MageAct_Max + ","
            + "ZiZhi_Def_Min:" + ZiZhi_Def_Min + ","
            + "ZiZhi_Def_Max:" + ZiZhi_Def_Max + ","
            + "ZiZhi_Adf_Min:" + ZiZhi_Adf_Min + ","
            + "ZiZhi_Adf_Max:" + ZiZhi_Adf_Max + ","
            + "ZiZhi_ActSpeed_Min:" + ZiZhi_ActSpeed_Min + ","
            + "ZiZhi_ActSpeed_Max:" + ZiZhi_ActSpeed_Max + ","
            + "ZiZhi_ChengZhang_Min:" + ZiZhi_ChengZhang_Min + ","
            + "ZiZhi_ChengZhang_Max:" + ZiZhi_ChengZhang_Max + ","
            + "Base_Hp:" + Base_Hp + ","
            + "Base_Act:" + Base_Act + ","
            + "Base_MageAct:" + Base_MageAct + ","
            + "Base_Def:" + Base_Def + ","
            + "Base_Adf:" + Base_Adf + ","
            + "Base_Cri:" + Base_Cri + ","
            + "Base_Res:" + Base_Res + ","
            + "Base_Hit:" + Base_Hit + ","
            + "Base_Dodge:" + Base_Dodge + ","
            + "Base_DefAdd:" + Base_DefAdd + ","
            + "Base_AdfAdd:" + Base_AdfAdd + ","
            + "Base_DamgeAdd:" + Base_DamgeAdd + ","
            + "Base_MoveSpeed:" + Base_MoveSpeed + ","
            + "Base_ActSpeed:" + Base_ActSpeed + ","
            + "ActDistance:" + ActDistance + ","
            + "Lv_Hp:" + Lv_Hp + ","
            + "Lv_Act:" + Lv_Act + ","
            + "Lv_MageAct:" + Lv_MageAct + ","
            + "Lv_Def:" + Lv_Def + ","
            + "Lv_Adf:" + Lv_Adf + ","
            + "PatrolRange:" + PatrolRange + ","
            + "ChaseRange:" + ChaseRange + ","
            + "ActRunRange:" + ActRunRange + ","
            + "Exp:" + Exp + ","
            + "SelectSize:" + SelectSize + ","
            + "ReleaseReward:" + Luban.StringUtil.CollectionToString(ReleaseReward) + ","
            + "ZhuanZhuSkillID:" + ZhuanZhuSkillID + ","
            + "ActSkillID:" + ActSkillID + ","
            + "BaseSkillID:" + BaseSkillID + ","
            + "RandomSkillID:" + RandomSkillID + ","
            + "Skin:" + Luban.StringUtil.CollectionToString(Skin) + ","
            + "SkinPro:" + Luban.StringUtil.CollectionToString(SkinPro) + ","
            + "AttackType:" + AttackType + ","
            + "}";
        }

        partial void PostInit();
    }
}

