
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class PetEggDuiHuanConfigCategory : Singleton<PetEggDuiHuanConfigCategory>, IConfig
    {
        private readonly Dictionary<int, PetEggDuiHuanConfig> _dataMap;
        private readonly List<PetEggDuiHuanConfig> _dataList;

        public PetEggDuiHuanConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, PetEggDuiHuanConfig>();
            _dataList = new List<PetEggDuiHuanConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                PetEggDuiHuanConfig _v;
                _v = global::ET.PetEggDuiHuanConfig.DeserializePetEggDuiHuanConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, PetEggDuiHuanConfig> DataMap => _dataMap;
        public List<PetEggDuiHuanConfig> DataList => _dataList;
        public Dictionary<int, PetEggDuiHuanConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public PetEggDuiHuanConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public PetEggDuiHuanConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

