
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PetEggDuiHuanConfig : BeanBase
    {
        public PetEggDuiHuanConfig()
        {
        }


        public PetEggDuiHuanConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            CostItems = _buf.ReadString();
            DropID = _buf.ReadInt();

            PostInit();
        }

        public static PetEggDuiHuanConfig DeserializePetEggDuiHuanConfig(ByteBuf _buf)
        {
            return new PetEggDuiHuanConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 消耗
        /// </summary>
        public string CostItems;

        /// <summary>
        /// 掉落ID
        /// </summary>
        public int DropID;


        public const int __ID__ = 741873934;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "CostItems:" + CostItems + ","
            + "DropID:" + DropID + ","
            + "}";
        }

        partial void PostInit();
    }
}

