
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class PetFubenRewardConfigCategory : Singleton<PetFubenRewardConfigCategory>, IConfig
    {
        private readonly Dictionary<int, PetFubenRewardConfig> _dataMap;
        private readonly List<PetFubenRewardConfig> _dataList;

        public PetFubenRewardConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, PetFubenRewardConfig>();
            _dataList = new List<PetFubenRewardConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                PetFubenRewardConfig _v;
                _v = global::ET.PetFubenRewardConfig.DeserializePetFubenRewardConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, PetFubenRewardConfig> DataMap => _dataMap;
        public List<PetFubenRewardConfig> DataList => _dataList;
        public Dictionary<int, PetFubenRewardConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public PetFubenRewardConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public PetFubenRewardConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

