
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PetMeleeFubenRewardConfig : BeanBase
    {
        public PetMeleeFubenRewardConfig()
        {
        }


        public PetMeleeFubenRewardConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            NeedStar = _buf.ReadInt();
            RewardItems = _buf.ReadString();
            Icon = _buf.ReadInt();
            Desc = _buf.ReadString();

            PostInit();
        }

        public static PetMeleeFubenRewardConfig DeserializePetMeleeFubenRewardConfig(ByteBuf _buf)
        {
            return new PetMeleeFubenRewardConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 需要副本星数
        /// </summary>
        public int NeedStar;

        /// <summary>
        /// 奖励
        /// </summary>
        public string RewardItems;

        /// <summary>
        /// Icon
        /// </summary>
        public int Icon;

        /// <summary>
        /// 描述
        /// </summary>
        public string Desc;


        public const int __ID__ = -1379670120;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "NeedStar:" + NeedStar + ","
            + "RewardItems:" + RewardItems + ","
            + "Icon:" + Icon + ","
            + "Desc:" + Desc + ","
            + "}";
        }

        partial void PostInit();
    }
}

