
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class PetSkinConfigCategory : Singleton<PetSkinConfigCategory>, IConfig
    {
        private readonly Dictionary<int, PetSkinConfig> _dataMap;
        private readonly List<PetSkinConfig> _dataList;

        public PetSkinConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, PetSkinConfig>();
            _dataList = new List<PetSkinConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                PetSkinConfig _v;
                _v = global::ET.PetSkinConfig.DeserializePetSkinConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, PetSkinConfig> DataMap => _dataMap;
        public List<PetSkinConfig> DataList => _dataList;
        public Dictionary<int, PetSkinConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public PetSkinConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public PetSkinConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

