
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PetTuJianConfig : BeanBase
    {
        public PetTuJianConfig()
        {
        }


        public PetTuJianConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            GetWay = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); GetValue = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); GetValue[__index0] = __e0;}}
            NeedPoint = _buf.ReadInt();
            ActivePro = _buf.ReadDouble();
            JingLingType = _buf.ReadInt();
            Cost = _buf.ReadInt();
            Icon = _buf.ReadInt();
            Assets = _buf.ReadString();
            AddProperty = _buf.ReadString();
            Lv = _buf.ReadString();
            ProDes = _buf.ReadString();
            Des = _buf.ReadString();

            PostInit();
        }

        public static PetTuJianConfig DeserializePetTuJianConfig(ByteBuf _buf)
        {
            return new PetTuJianConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 获取方式
        /// </summary>
        public int GetWay;

        /// <summary>
        /// 获取参数
        /// </summary>
        public int[] GetValue;

        /// <summary>
        /// 激活点数
        /// </summary>
        public int NeedPoint;

        /// <summary>
        /// 激活概率
        /// </summary>
        public double ActivePro;

        /// <summary>
        /// 精灵类型
        /// </summary>
        public int JingLingType;

        /// <summary>
        /// 召唤消耗
        /// </summary>
        public int Cost;

        /// <summary>
        /// 图标显示
        /// </summary>
        public int Icon;

        /// <summary>
        /// 模型
        /// </summary>
        public string Assets;

        /// <summary>
        /// 额外属性
        /// </summary>
        public string AddProperty;

        /// <summary>
        /// 境界
        /// </summary>
        public string Lv;

        /// <summary>
        /// 属性描述
        /// </summary>
        public string ProDes;

        /// <summary>
        /// 额外属性描述
        /// </summary>
        public string Des;


        public const int __ID__ = -730806258;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "GetWay:" + GetWay + ","
            + "GetValue:" + Luban.StringUtil.CollectionToString(GetValue) + ","
            + "NeedPoint:" + NeedPoint + ","
            + "ActivePro:" + ActivePro + ","
            + "JingLingType:" + JingLingType + ","
            + "Cost:" + Cost + ","
            + "Icon:" + Icon + ","
            + "Assets:" + Assets + ","
            + "AddProperty:" + AddProperty + ","
            + "Lv:" + Lv + ","
            + "ProDes:" + ProDes + ","
            + "Des:" + Des + ","
            + "}";
        }

        partial void PostInit();
    }
}

