
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class PetZhuangJiaConfig : BeanBase
    {
        public PetZhuangJiaConfig()
        {
        }


        public PetZhuangJiaConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            NextID = _buf.ReadInt();
            Lv = _buf.ReadInt();
            CostItem = _buf.ReadString();
            PropreAdd = _buf.ReadString();

            PostInit();
        }

        public static PetZhuangJiaConfig DeserializePetZhuangJiaConfig(ByteBuf _buf)
        {
            return new PetZhuangJiaConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 下一级强化
        /// </summary>
        public int NextID;

        /// <summary>
        /// 强化等级
        /// </summary>
        public int Lv;

        /// <summary>
        /// 消耗道具
        /// </summary>
        public string CostItem;

        /// <summary>
        /// 强化属性
        /// </summary>
        public string PropreAdd;


        public const int __ID__ = -84385358;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "NextID:" + NextID + ","
            + "Lv:" + Lv + ","
            + "CostItem:" + CostItem + ","
            + "PropreAdd:" + PropreAdd + ","
            + "}";
        }

        partial void PostInit();
    }
}

