
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SceneConfig : BeanBase
    {
        public SceneConfig()
        {
        }


        public SceneConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Icon = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); StallArea = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); StallArea[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); InitPos = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); InitPos[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); NpcList = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); NpcList[__index0] = __e0;}}
            MapType = _buf.ReadInt();
            MapID = _buf.ReadInt();
            LoadingRes = _buf.ReadString();
            ifShowMinMap = _buf.ReadInt();
            IfUseRes = _buf.ReadInt();
            IfPVP = _buf.ReadInt();
            IfUseSkillItem = _buf.ReadInt();
            IfInitPosi = _buf.ReadInt();
            Music = _buf.ReadString();
            CreateLv = _buf.ReadInt();
            EnterLv = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); TuiJianLv = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); TuiJianLv[__index0] = __e0;}}
            PlayerLimit = _buf.ReadInt();
            DayEnterNum = _buf.ReadInt();
            IfMount = _buf.ReadInt();
            BossId = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); CreateMonsterPosi = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); CreateMonsterPosi[__index0] = __e0;}}
            ChapterDes = _buf.ReadString();
            RewardShow = _buf.ReadString();
            RewardExp = _buf.ReadInt();
            RewardGold = _buf.ReadInt();
            BoxDropID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); CameraPos = new double[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { double __e0;__e0 = _buf.ReadDouble(); CameraPos[__index0] = __e0;}}

            PostInit();
        }

        public static SceneConfig DeserializeSceneConfig(ByteBuf _buf)
        {
            return new SceneConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 章节名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 图标显示
        /// </summary>
        public string Icon;

        /// <summary>
        /// 摆摊区域
        /// </summary>
        public int[] StallArea;

        /// <summary>
        /// 出生坐标点
        /// </summary>
        public int[] InitPos;

        /// <summary>
        /// NPC
        /// </summary>
        public int[] NpcList;

        /// <summary>
        /// 地图类型
        /// </summary>
        public int MapType;

        /// <summary>
        /// 地图ID
        /// </summary>
        public int MapID;

        /// <summary>
        /// loading图
        /// </summary>
        public string LoadingRes;

        /// <summary>
        /// 是否有小地图
        /// </summary>
        public int ifShowMinMap;

        /// <summary>
        /// 是否可以使用复活
        /// </summary>
        public int IfUseRes;

        /// <summary>
        /// 是否允许PVP
        /// </summary>
        public int IfPVP;

        /// <summary>
        /// 是否允许使用道具
        /// </summary>
        public int IfUseSkillItem;

        /// <summary>
        /// 返回主城是否在默认点
        /// </summary>
        public int IfInitPosi;

        /// <summary>
        /// 音乐
        /// </summary>
        public string Music;

        /// <summary>
        /// 创建等级限制
        /// </summary>
        public int CreateLv;

        /// <summary>
        /// 进入等级限制
        /// </summary>
        public int EnterLv;

        /// <summary>
        /// 推荐等级
        /// </summary>
        public int[] TuiJianLv;

        /// <summary>
        /// 进入人数限制
        /// </summary>
        public int PlayerLimit;

        /// <summary>
        /// 进入次数限制
        /// </summary>
        public int DayEnterNum;

        /// <summary>
        /// 是否可以上马
        /// </summary>
        public int IfMount;

        /// <summary>
        /// 章节BossId
        /// </summary>
        public int BossId;

        /// <summary>
        /// 怪物生成坐标点
        /// </summary>
        public int[] CreateMonsterPosi;

        /// <summary>
        /// 章节文本描述
        /// </summary>
        public string ChapterDes;

        /// <summary>
        /// 奖励展示
        /// </summary>
        public string RewardShow;

        /// <summary>
        ///  通关经验奖励
        /// </summary>
        public int RewardExp;

        /// <summary>
        /// 通关金币奖励
        /// </summary>
        public int RewardGold;

        /// <summary>
        /// 翻卡掉落ID
        /// </summary>
        public int BoxDropID;

        /// <summary>
        /// 摄像机参数
        /// </summary>
        public double[] CameraPos;


        public const int __ID__ = 935827150;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Icon:" + Icon + ","
            + "StallArea:" + Luban.StringUtil.CollectionToString(StallArea) + ","
            + "InitPos:" + Luban.StringUtil.CollectionToString(InitPos) + ","
            + "NpcList:" + Luban.StringUtil.CollectionToString(NpcList) + ","
            + "MapType:" + MapType + ","
            + "MapID:" + MapID + ","
            + "LoadingRes:" + LoadingRes + ","
            + "ifShowMinMap:" + ifShowMinMap + ","
            + "IfUseRes:" + IfUseRes + ","
            + "IfPVP:" + IfPVP + ","
            + "IfUseSkillItem:" + IfUseSkillItem + ","
            + "IfInitPosi:" + IfInitPosi + ","
            + "Music:" + Music + ","
            + "CreateLv:" + CreateLv + ","
            + "EnterLv:" + EnterLv + ","
            + "TuiJianLv:" + Luban.StringUtil.CollectionToString(TuiJianLv) + ","
            + "PlayerLimit:" + PlayerLimit + ","
            + "DayEnterNum:" + DayEnterNum + ","
            + "IfMount:" + IfMount + ","
            + "BossId:" + BossId + ","
            + "CreateMonsterPosi:" + Luban.StringUtil.CollectionToString(CreateMonsterPosi) + ","
            + "ChapterDes:" + ChapterDes + ","
            + "RewardShow:" + RewardShow + ","
            + "RewardExp:" + RewardExp + ","
            + "RewardGold:" + RewardGold + ","
            + "BoxDropID:" + BoxDropID + ","
            + "CameraPos:" + Luban.StringUtil.CollectionToString(CameraPos) + ","
            + "}";
        }

        partial void PostInit();
    }
}

