
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ShouJiConfigCategory : Singleton<ShouJiConfigCategory>, IConfig
    {
        private readonly Dictionary<int, ShouJiConfig> _dataMap;
        private readonly List<ShouJiConfig> _dataList;

        public ShouJiConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ShouJiConfig>();
            _dataList = new List<ShouJiConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ShouJiConfig _v;
                _v = global::ET.ShouJiConfig.DeserializeShouJiConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ShouJiConfig> DataMap => _dataMap;
        public List<ShouJiConfig> DataList => _dataList;
        public Dictionary<int, ShouJiConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public ShouJiConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public ShouJiConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

