
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ShouJiItemConfigCategory : Singleton<ShouJiItemConfigCategory>, IConfig
    {
        private readonly Dictionary<int, ShouJiItemConfig> _dataMap;
        private readonly List<ShouJiItemConfig> _dataList;

        public ShouJiItemConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ShouJiItemConfig>();
            _dataList = new List<ShouJiItemConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ShouJiItemConfig _v;
                _v = global::ET.ShouJiItemConfig.DeserializeShouJiItemConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ShouJiItemConfig> DataMap => _dataMap;
        public List<ShouJiItemConfig> DataList => _dataList;
        public Dictionary<int, ShouJiItemConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public ShouJiItemConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public ShouJiItemConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

