
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SkillConfig : BeanBase
    {
        public SkillConfig()
        {
        }


        public SkillConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            SkillName = _buf.ReadString();
            SkillLv = _buf.ReadInt();
            SkillIcon = _buf.ReadString();
            NextSkillID = _buf.ReadInt();
            WeaponType = _buf.ReadInt();
            LearnRoseLv = _buf.ReadInt();
            CostSPValue = _buf.ReadInt();
            CostGoldValue = _buf.ReadInt();
            OpenType = _buf.ReadInt();
            EquipSkill = _buf.ReadString();
            SkillType = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); PassiveSkillType = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); PassiveSkillType[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); PassiveSkillPro = new double[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { double __e0;__e0 = _buf.ReadDouble(); PassiveSkillPro[__index0] = __e0;}}
            PassiveSkillTriggerOnce = _buf.ReadInt();
            SkillTargetTypeNum = _buf.ReadInt();
            ComboSkillID = _buf.ReadInt();
            SkillActType = _buf.ReadInt();
            DamgeType = _buf.ReadInt();
            DamgeElementType = _buf.ReadInt();
            ActDamge = _buf.ReadDouble();
            MonsterActDamge = _buf.ReadDouble();
            DamgeValue = _buf.ReadInt();
            IfMustAct = _buf.ReadInt();
            SkillUseMP = _buf.ReadInt();
            SkillAddMP = _buf.ReadInt();
            IfPublicSkillCD = _buf.ReadInt();
            IfSkillCD = _buf.ReadInt();
            SkillCD = _buf.ReadDouble();
            DamgeRangeType = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); DamgeRange = new double[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { double __e0;__e0 = _buf.ReadDouble(); DamgeRange[__index0] = __e0;}}
            SkillTargetType = _buf.ReadInt();
            SkillZhishiType = _buf.ReadInt();
            SkillZhishiTargetType = _buf.ReadInt();
            SkillRangeSize = _buf.ReadDouble();
            SkillRangeZhiShiSize = _buf.ReadInt();
            SkillFrontSingTime = _buf.ReadDouble();
            SkillSingTime = _buf.ReadDouble();
            SkillRigidity = _buf.ReadDouble();
            SkillLiveTime = _buf.ReadInt();
            SkillDelayTime = _buf.ReadDouble();
            SkillMoveSpeed = _buf.ReadDouble();
            {int __n0 = _buf.ReadSize(); InitBuffID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); InitBuffID[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); BuffID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); BuffID[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); OnlyOnceBuffID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); OnlyOnceBuffID[__index0] = __e0;}}
            SkillAnimation = _buf.ReadString();
            SkillMusic = _buf.ReadString();
            SkillHitEffectID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); SkillEffectID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SkillEffectID[__index0] = __e0;}}
            GameObjectName = _buf.ReadString();
            GameObjectParameter = _buf.ReadString();
            ComObjParameter = _buf.ReadString();
            IsShow = _buf.ReadInt();
            SkillDescribe = _buf.ReadString();
            IfLookAtTatgetTime = _buf.ReadDouble();
            AddSkillID = _buf.ReadInt();
            PassiveSkillTriggerTime = _buf.ReadDouble();
            IfLookAtTarget = _buf.ReadInt();
            MonsterDelayTime = _buf.ReadDouble();
            HuChiID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); TriggerSelfSkillID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); TriggerSelfSkillID[__index0] = __e0;}}
            IfStopMove = _buf.ReadInt();
            DamgeChiXuTrigerBuff = _buf.ReadInt();
            DamgeChiXuInterval = _buf.ReadInt();
            DamgeChiXuPro = _buf.ReadDouble();
            DamgeChiXuValue = _buf.ReadInt();
            IfShowSkillZhiShi = _buf.ReadInt();
            EndSkillId = _buf.ReadInt();
            BuffToSkill = _buf.ReadString();
            SkillDamgeAddValue = _buf.ReadString();
            MaxAttackNumber = _buf.ReadInt();
            ShakeCameraType = _buf.ReadInt();
            ShakeStart = _buf.ReadDouble();
            ShakeDuration = _buf.ReadDouble();

            PostInit();
        }

        public static SkillConfig DeserializeSkillConfig(ByteBuf _buf)
        {
            return new SkillConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 技能名称
        /// </summary>
        public string SkillName;

        /// <summary>
        /// 技能等级
        /// </summary>
        public int SkillLv;

        /// <summary>
        /// 技能Icon
        /// </summary>
        public string SkillIcon;

        /// <summary>
        /// 下一级技能
        /// </summary>
        public int NextSkillID;

        /// <summary>
        /// 使用武器触发
        /// </summary>
        public int WeaponType;

        /// <summary>
        /// 学习技能等级
        /// </summary>
        public int LearnRoseLv;

        /// <summary>
        /// 升级消耗SP值
        /// </summary>
        public int CostSPValue;

        /// <summary>
        /// 升级消耗金币
        /// </summary>
        public int CostGoldValue;

        /// <summary>
        /// 被控制是否可以放技能
        /// </summary>
        public int OpenType;

        /// <summary>
        /// 装备升级前ID
        /// </summary>
        public string EquipSkill;

        /// <summary>
        /// 技能类型
        /// </summary>
        public int SkillType;

        /// <summary>
        /// 被动技能触发类型
        /// </summary>
        public int[] PassiveSkillType;

        /// <summary>
        /// 被动技能触发参数
        /// </summary>
        public double[] PassiveSkillPro;

        /// <summary>
        /// 被动技能触发一次
        /// </summary>
        public int PassiveSkillTriggerOnce;

        /// <summary>
        /// 施法目标
        /// </summary>
        public int SkillTargetTypeNum;

        /// <summary>
        /// 连招技能ID
        /// </summary>
        public int ComboSkillID;

        /// <summary>
        /// 技能攻击类型
        /// </summary>
        public int SkillActType;

        /// <summary>
        /// 伤害类型
        /// </summary>
        public int DamgeType;

        /// <summary>
        /// 伤害元素攻击
        /// </summary>
        public int DamgeElementType;

        /// <summary>
        /// 攻击系数
        /// </summary>
        public double ActDamge;

        /// <summary>
        /// 怪物攻击系数
        /// </summary>
        public double MonsterActDamge;

        /// <summary>
        /// 固定伤害值
        /// </summary>
        public int DamgeValue;

        /// <summary>
        /// 是否必中
        /// </summary>
        public int IfMustAct;

        /// <summary>
        /// 消耗魔法
        /// </summary>
        public int SkillUseMP;

        /// <summary>
        /// 增加魔法
        /// </summary>
        public int SkillAddMP;

        /// <summary>
        /// 是否触发公共CD
        /// </summary>
        public int IfPublicSkillCD;

        /// <summary>
        /// 是否触发冷却技能CD(废弃)
        /// </summary>
        public int IfSkillCD;

        /// <summary>
        /// 冷却CD
        /// </summary>
        public double SkillCD;

        /// <summary>
        /// 伤害范围类型
        /// </summary>
        public int DamgeRangeType;

        /// <summary>
        /// 伤害范围
        /// </summary>
        public double[] DamgeRange;

        /// <summary>
        /// 技能目标类型
        /// </summary>
        public int SkillTargetType;

        /// <summary>
        /// 释放区域类型
        /// </summary>
        public int SkillZhishiType;

        /// <summary>
        /// 释放区域目标点类型
        /// </summary>
        public int SkillZhishiTargetType;

        /// <summary>
        /// 释放区域大小
        /// </summary>
        public double SkillRangeSize;

        /// <summary>
        /// 技能指示器增加范围
        /// </summary>
        public int SkillRangeZhiShiSize;

        /// <summary>
        /// 施法前吟唱时间
        /// </summary>
        public double SkillFrontSingTime;

        /// <summary>
        /// 施法中吟唱时间
        /// </summary>
        public double SkillSingTime;

        /// <summary>
        /// 技能僵直
        /// </summary>
        public double SkillRigidity;

        /// <summary>
        /// 技能存在时间[毫秒]
        /// </summary>
        public int SkillLiveTime;

        /// <summary>
        /// 技能效果延迟时间
        /// </summary>
        public double SkillDelayTime;

        /// <summary>
        /// 技能移动速度
        /// </summary>
        public double SkillMoveSpeed;

        /// <summary>
        /// 初始化BUFFID
        /// </summary>
        public int[] InitBuffID;

        /// <summary>
        /// 释放BUFFID
        /// </summary>
        public int[] BuffID;

        /// <summary>
        /// 只释放一次buff
        /// </summary>
        public int[] OnlyOnceBuffID;

        /// <summary>
        /// 施法动作名称
        /// </summary>
        public string SkillAnimation;

        /// <summary>
        /// 技能音效
        /// </summary>
        public string SkillMusic;

        /// <summary>
        /// 技能特效ID
        /// </summary>
        public int SkillHitEffectID;

        /// <summary>
        /// 技能特效ID
        /// </summary>
        public int[] SkillEffectID;

        /// <summary>
        /// 脚本名称
        /// </summary>
        public string GameObjectName;

        /// <summary>
        /// 每个脚本对应参数
        /// </summary>
        public string GameObjectParameter;

        /// <summary>
        /// 所有脚本通用参数
        /// </summary>
        public string ComObjParameter;

        /// <summary>
        /// 是否显示
        /// </summary>
        public int IsShow;

        /// <summary>
        /// 技能描述
        /// </summary>
        public string SkillDescribe;

        /// <summary>
        /// 施法时面对目标时间
        /// </summary>
        public double IfLookAtTatgetTime;

        /// <summary>
        /// 触发技能时附带技能
        /// </summary>
        public int AddSkillID;

        /// <summary>
        /// 技能触发时间
        /// </summary>
        public double PassiveSkillTriggerTime;

        /// <summary>
        /// 施法时是否面对目标
        /// </summary>
        public int IfLookAtTarget;

        /// <summary>
        /// 怪物技能延迟
        /// </summary>
        public double MonsterDelayTime;

        /// <summary>
        /// 宠物互斥ID
        /// </summary>
        public int HuChiID;

        /// <summary>
        /// 触发自身拥有技能
        /// </summary>
        public int[] TriggerSelfSkillID;

        /// <summary>
        /// 释放技能是否打断移动
        /// </summary>
        public int IfStopMove;

        /// <summary>
        /// 技能持续伤害是否触发Buff
        /// </summary>
        public int DamgeChiXuTrigerBuff;

        /// <summary>
        /// 技能持续伤害间隔时间
        /// </summary>
        public int DamgeChiXuInterval;

        /// <summary>
        /// 技能持续伤害百分比
        /// </summary>
        public double DamgeChiXuPro;

        /// <summary>
        /// 技能持续伤害固定值
        /// </summary>
        public int DamgeChiXuValue;

        /// <summary>
        /// 是否显示技能指示器字段
        /// </summary>
        public int IfShowSkillZhiShi;

        /// <summary>
        /// 结束时技能
        /// </summary>
        public int EndSkillId;

        /// <summary>
        /// 触发技能
        /// </summary>
        public string BuffToSkill;

        /// <summary>
        /// 技能伤害增加
        /// </summary>
        public string SkillDamgeAddValue;

        /// <summary>
        /// 最大攻击数量
        /// </summary>
        public int MaxAttackNumber;

        /// <summary>
        /// 震屏类型
        /// </summary>
        public int ShakeCameraType;

        /// <summary>
        /// 震屏开始时间
        /// </summary>
        public double ShakeStart;

        /// <summary>
        /// 震持续时间
        /// </summary>
        public double ShakeDuration;


        public const int __ID__ = -844226349;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "SkillName:" + SkillName + ","
            + "SkillLv:" + SkillLv + ","
            + "SkillIcon:" + SkillIcon + ","
            + "NextSkillID:" + NextSkillID + ","
            + "WeaponType:" + WeaponType + ","
            + "LearnRoseLv:" + LearnRoseLv + ","
            + "CostSPValue:" + CostSPValue + ","
            + "CostGoldValue:" + CostGoldValue + ","
            + "OpenType:" + OpenType + ","
            + "EquipSkill:" + EquipSkill + ","
            + "SkillType:" + SkillType + ","
            + "PassiveSkillType:" + Luban.StringUtil.CollectionToString(PassiveSkillType) + ","
            + "PassiveSkillPro:" + Luban.StringUtil.CollectionToString(PassiveSkillPro) + ","
            + "PassiveSkillTriggerOnce:" + PassiveSkillTriggerOnce + ","
            + "SkillTargetTypeNum:" + SkillTargetTypeNum + ","
            + "ComboSkillID:" + ComboSkillID + ","
            + "SkillActType:" + SkillActType + ","
            + "DamgeType:" + DamgeType + ","
            + "DamgeElementType:" + DamgeElementType + ","
            + "ActDamge:" + ActDamge + ","
            + "MonsterActDamge:" + MonsterActDamge + ","
            + "DamgeValue:" + DamgeValue + ","
            + "IfMustAct:" + IfMustAct + ","
            + "SkillUseMP:" + SkillUseMP + ","
            + "SkillAddMP:" + SkillAddMP + ","
            + "IfPublicSkillCD:" + IfPublicSkillCD + ","
            + "IfSkillCD:" + IfSkillCD + ","
            + "SkillCD:" + SkillCD + ","
            + "DamgeRangeType:" + DamgeRangeType + ","
            + "DamgeRange:" + Luban.StringUtil.CollectionToString(DamgeRange) + ","
            + "SkillTargetType:" + SkillTargetType + ","
            + "SkillZhishiType:" + SkillZhishiType + ","
            + "SkillZhishiTargetType:" + SkillZhishiTargetType + ","
            + "SkillRangeSize:" + SkillRangeSize + ","
            + "SkillRangeZhiShiSize:" + SkillRangeZhiShiSize + ","
            + "SkillFrontSingTime:" + SkillFrontSingTime + ","
            + "SkillSingTime:" + SkillSingTime + ","
            + "SkillRigidity:" + SkillRigidity + ","
            + "SkillLiveTime:" + SkillLiveTime + ","
            + "SkillDelayTime:" + SkillDelayTime + ","
            + "SkillMoveSpeed:" + SkillMoveSpeed + ","
            + "InitBuffID:" + Luban.StringUtil.CollectionToString(InitBuffID) + ","
            + "BuffID:" + Luban.StringUtil.CollectionToString(BuffID) + ","
            + "OnlyOnceBuffID:" + Luban.StringUtil.CollectionToString(OnlyOnceBuffID) + ","
            + "SkillAnimation:" + SkillAnimation + ","
            + "SkillMusic:" + SkillMusic + ","
            + "SkillHitEffectID:" + SkillHitEffectID + ","
            + "SkillEffectID:" + Luban.StringUtil.CollectionToString(SkillEffectID) + ","
            + "GameObjectName:" + GameObjectName + ","
            + "GameObjectParameter:" + GameObjectParameter + ","
            + "ComObjParameter:" + ComObjParameter + ","
            + "IsShow:" + IsShow + ","
            + "SkillDescribe:" + SkillDescribe + ","
            + "IfLookAtTatgetTime:" + IfLookAtTatgetTime + ","
            + "AddSkillID:" + AddSkillID + ","
            + "PassiveSkillTriggerTime:" + PassiveSkillTriggerTime + ","
            + "IfLookAtTarget:" + IfLookAtTarget + ","
            + "MonsterDelayTime:" + MonsterDelayTime + ","
            + "HuChiID:" + HuChiID + ","
            + "TriggerSelfSkillID:" + Luban.StringUtil.CollectionToString(TriggerSelfSkillID) + ","
            + "IfStopMove:" + IfStopMove + ","
            + "DamgeChiXuTrigerBuff:" + DamgeChiXuTrigerBuff + ","
            + "DamgeChiXuInterval:" + DamgeChiXuInterval + ","
            + "DamgeChiXuPro:" + DamgeChiXuPro + ","
            + "DamgeChiXuValue:" + DamgeChiXuValue + ","
            + "IfShowSkillZhiShi:" + IfShowSkillZhiShi + ","
            + "EndSkillId:" + EndSkillId + ","
            + "BuffToSkill:" + BuffToSkill + ","
            + "SkillDamgeAddValue:" + SkillDamgeAddValue + ","
            + "MaxAttackNumber:" + MaxAttackNumber + ","
            + "ShakeCameraType:" + ShakeCameraType + ","
            + "ShakeStart:" + ShakeStart + ","
            + "ShakeDuration:" + ShakeDuration + ","
            + "}";
        }

        partial void PostInit();
    }
}

