
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class StoreSellConfigCategory : Singleton<StoreSellConfigCategory>, IConfig
    {
        private readonly Dictionary<int, StoreSellConfig> _dataMap;
        private readonly List<StoreSellConfig> _dataList;

        public StoreSellConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, StoreSellConfig>();
            _dataList = new List<StoreSellConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                StoreSellConfig _v;
                _v = global::ET.StoreSellConfig.DeserializeStoreSellConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, StoreSellConfig> DataMap => _dataMap;
        public List<StoreSellConfig> DataList => _dataList;
        public Dictionary<int, StoreSellConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public StoreSellConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public StoreSellConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

