
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TakeCardConfig : BeanBase
    {
        public TakeCardConfig()
        {
        }


        public TakeCardConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            RoseLvLimit = _buf.ReadInt();
            ZuanShiNum = _buf.ReadInt();
            ZuanShiNum_Ten = _buf.ReadInt();
            DropID = _buf.ReadInt();
            DropShow = _buf.ReadString();

            PostInit();
        }

        public static TakeCardConfig DeserializeTakeCardConfig(ByteBuf _buf)
        {
            return new TakeCardConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 抽卡等级
        /// </summary>
        public int RoseLvLimit;

        /// <summary>
        /// 抽卡消耗钻石
        /// </summary>
        public int ZuanShiNum;

        /// <summary>
        /// 抽卡消耗钻石
        /// </summary>
        public int ZuanShiNum_Ten;

        /// <summary>
        /// 掉落ID
        /// </summary>
        public int DropID;

        /// <summary>
        /// 掉落展示ID
        /// </summary>
        public string DropShow;


        public const int __ID__ = -202998151;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "RoseLvLimit:" + RoseLvLimit + ","
            + "ZuanShiNum:" + ZuanShiNum + ","
            + "ZuanShiNum_Ten:" + ZuanShiNum_Ten + ","
            + "DropID:" + DropID + ","
            + "DropShow:" + DropShow + ","
            + "}";
        }

        partial void PostInit();
    }
}

