
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class TakeCardRewardConfigCategory : Singleton<TakeCardRewardConfigCategory>, IConfig
    {
        private readonly Dictionary<int, TakeCardRewardConfig> _dataMap;
        private readonly List<TakeCardRewardConfig> _dataList;

        public TakeCardRewardConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TakeCardRewardConfig>();
            _dataList = new List<TakeCardRewardConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TakeCardRewardConfig _v;
                _v = global::ET.TakeCardRewardConfig.DeserializeTakeCardRewardConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TakeCardRewardConfig> DataMap => _dataMap;
        public List<TakeCardRewardConfig> DataList => _dataList;
        public Dictionary<int, TakeCardRewardConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public TakeCardRewardConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TakeCardRewardConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

