
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TalentConfig : BeanBase
    {
        public TalentConfig()
        {
        }


        public TalentConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Occ = _buf.ReadInt();
            TalentType = _buf.ReadInt();
            Position = _buf.ReadInt();
            Lv = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); PreId = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); PreId[__index0] = __e0;}}
            NeedUseNumber = _buf.ReadInt();
            LearnRoseLv = _buf.ReadInt();
            Icon = _buf.ReadInt();
            talentDes = _buf.ReadString();
            AddPropreListStr = _buf.ReadString();

            PostInit();
        }

        public static TalentConfig DeserializeTalentConfig(ByteBuf _buf)
        {
            return new TalentConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 天赋名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 职业
        /// </summary>
        public int Occ;

        /// <summary>
        /// 天赋类型
        /// </summary>
        public int TalentType;

        /// <summary>
        /// 天赋位置
        /// </summary>
        public int Position;

        /// <summary>
        /// 天赋等级
        /// </summary>
        public int Lv;

        /// <summary>
        /// 前置id
        /// </summary>
        public int[] PreId;

        /// <summary>
        /// 需要当前类型已使用天赋点
        /// </summary>
        public int NeedUseNumber;

        /// <summary>
        /// 学习等级
        /// </summary>
        public int LearnRoseLv;

        /// <summary>
        /// Icon
        /// </summary>
        public int Icon;

        /// <summary>
        /// 天赋描述
        /// </summary>
        public string talentDes;

        /// <summary>
        /// 附加
        /// </summary>
        public string AddPropreListStr;


        public const int __ID__ = -1834609810;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Occ:" + Occ + ","
            + "TalentType:" + TalentType + ","
            + "Position:" + Position + ","
            + "Lv:" + Lv + ","
            + "PreId:" + Luban.StringUtil.CollectionToString(PreId) + ","
            + "NeedUseNumber:" + NeedUseNumber + ","
            + "LearnRoseLv:" + LearnRoseLv + ","
            + "Icon:" + Icon + ","
            + "talentDes:" + talentDes + ","
            + "AddPropreListStr:" + AddPropreListStr + ","
            + "}";
        }

        partial void PostInit();
    }
}

