
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class TaskPositionConfigCategory : Singleton<TaskPositionConfigCategory>, IConfig
    {
        private readonly Dictionary<int, TaskPositionConfig> _dataMap;
        private readonly List<TaskPositionConfig> _dataList;

        public TaskPositionConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TaskPositionConfig>();
            _dataList = new List<TaskPositionConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TaskPositionConfig _v;
                _v = global::ET.TaskPositionConfig.DeserializeTaskPositionConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TaskPositionConfig> DataMap => _dataMap;
        public List<TaskPositionConfig> DataList => _dataList;
        public Dictionary<int, TaskPositionConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public TaskPositionConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TaskPositionConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

