
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TitleConfig : BeanBase
    {
        public TitleConfig()
        {
        }


        public TitleConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Icon = _buf.ReadInt();
            AddProperty = _buf.ReadString();
            AnimatorAsset = _buf.ReadString();
            AnimatorNumber = _buf.ReadInt();
            ValidityTime = _buf.ReadInt();
            Des = _buf.ReadString();
            size = _buf.ReadDouble();
            MoveX = _buf.ReadDouble();
            MoveY = _buf.ReadDouble();
            GetDes = _buf.ReadString();

            PostInit();
        }

        public static TitleConfig DeserializeTitleConfig(ByteBuf _buf)
        {
            return new TitleConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 图标显示
        /// </summary>
        public int Icon;

        /// <summary>
        /// 额外属性
        /// </summary>
        public string AddProperty;

        /// <summary>
        /// 序列帧动画
        /// </summary>
        public string AnimatorAsset;

        /// <summary>
        /// 序列帧动画数量
        /// </summary>
        public int AnimatorNumber;

        /// <summary>
        /// 有效期(秒)
        /// </summary>
        public int ValidityTime;

        /// <summary>
        /// 额外属性描述
        /// </summary>
        public string Des;

        /// <summary>
        /// 缩放大小
        /// </summary>
        public double size;

        /// <summary>
        /// X偏移
        /// </summary>
        public double MoveX;

        /// <summary>
        /// Y便宜
        /// </summary>
        public double MoveY;

        /// <summary>
        /// 额外属性描述
        /// </summary>
        public string GetDes;


        public const int __ID__ = 1722095514;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Icon:" + Icon + ","
            + "AddProperty:" + AddProperty + ","
            + "AnimatorAsset:" + AnimatorAsset + ","
            + "AnimatorNumber:" + AnimatorNumber + ","
            + "ValidityTime:" + ValidityTime + ","
            + "Des:" + Des + ","
            + "size:" + size + ","
            + "MoveX:" + MoveX + ","
            + "MoveY:" + MoveY + ","
            + "GetDes:" + GetDes + ","
            + "}";
        }

        partial void PostInit();
    }
}

