
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class UnionQiangHuaConfigCategory : Singleton<UnionQiangHuaConfigCategory>, IConfig
    {
        private readonly Dictionary<int, UnionQiangHuaConfig> _dataMap;
        private readonly List<UnionQiangHuaConfig> _dataList;

        public UnionQiangHuaConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, UnionQiangHuaConfig>();
            _dataList = new List<UnionQiangHuaConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                UnionQiangHuaConfig _v;
                _v = global::ET.UnionQiangHuaConfig.DeserializeUnionQiangHuaConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, UnionQiangHuaConfig> DataMap => _dataMap;
        public List<UnionQiangHuaConfig> DataList => _dataList;
        public Dictionary<int, UnionQiangHuaConfig> GetAll() => _dataMap;
        public bool Contain(int key) => _dataMap.ContainsKey(key);

        public UnionQiangHuaConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public UnionQiangHuaConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}

