
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    public partial struct vector4
    {

        public vector4(ByteBuf _buf)
        {
            x = _buf.ReadFloat();
            y = _buf.ReadFloat();
            z = _buf.ReadFloat();
            w = _buf.ReadFloat();

            PostInit();
        }

        public static vector4 Deserializevector4(ByteBuf _buf)
        {
            return new vector4(_buf);
        }

        public float x;

        public float y;

        public float z;

        public float w;



        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "x:" + x + ","
            + "y:" + y + ","
            + "z:" + z + ","
            + "w:" + w + ","
            + "}";
        }

        partial void PostInit();
    }
}

