
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    public partial struct vector3
    {

        public vector3(ByteBuf _buf)
        {
            x = _buf.ReadFloat();
            y = _buf.ReadFloat();
            z = _buf.ReadFloat();

            PostInit();
        }

        public static vector3 Deserializevector3(ByteBuf _buf)
        {
            return new vector3(_buf);
        }

        public float x;

        public float y;

        public float z;



        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "x:" + x + ","
            + "y:" + y + ","
            + "z:" + z + ","
            + "}";
        }

        partial void PostInit();
    }
}

