
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ZuoQiConfig : BeanBase
    {
        public ZuoQiConfig()
        {
        }


        public ZuoQiConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Icon = _buf.ReadInt();
            NextID = _buf.ReadInt();
            JieName = _buf.ReadString();
            Lv = _buf.ReadInt();
            UpNeedLv = _buf.ReadInt();
            UpZiZhiCostGold = _buf.ReadInt();
            UpCostZiJin = _buf.ReadInt();
            ZiZhiMax = _buf.ReadInt();
            AddProperty = _buf.ReadString();
            Des = _buf.ReadString();

            PostInit();
        }

        public static ZuoQiConfig DeserializeZuoQiConfig(ByteBuf _buf)
        {
            return new ZuoQiConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public string Name;

        /// <summary>
        /// 图标显示
        /// </summary>
        public int Icon;

        /// <summary>
        /// 下一级ID
        /// </summary>
        public int NextID;

        /// <summary>
        /// 阶段名称
        /// </summary>
        public string JieName;

        /// <summary>
        /// 品质
        /// </summary>
        public int Lv;

        /// <summary>
        /// 升级需要
        /// </summary>
        public int UpNeedLv;

        /// <summary>
        /// 消耗金币
        /// </summary>
        public int UpZiZhiCostGold;

        /// <summary>
        /// 升级消耗
        /// </summary>
        public int UpCostZiJin;

        /// <summary>
        /// 资质上限
        /// </summary>
        public int ZiZhiMax;

        /// <summary>
        /// 额外属性
        /// </summary>
        public string AddProperty;

        /// <summary>
        /// 额外属性描述
        /// </summary>
        public string Des;


        public const int __ID__ = 1358273550;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Icon:" + Icon + ","
            + "NextID:" + NextID + ","
            + "JieName:" + JieName + ","
            + "Lv:" + Lv + ","
            + "UpNeedLv:" + UpNeedLv + ","
            + "UpZiZhiCostGold:" + UpZiZhiCostGold + ","
            + "UpCostZiJin:" + UpCostZiJin + ","
            + "ZiZhiMax:" + ZiZhiMax + ","
            + "AddProperty:" + AddProperty + ","
            + "Des:" + Des + ","
            + "}";
        }

        partial void PostInit();
    }
}

