
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class StartProcessConfig : BeanBase
    {
        public StartProcessConfig()
        {
        }


        public StartProcessConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            MachineId = _buf.ReadInt();
            InnerPort = _buf.ReadInt();
            dll = _buf.ReadString();
            AppName = _buf.ReadString();
            Title = _buf.ReadString();

            PostInit();
        }

        public static StartProcessConfig DeserializeStartProcessConfig(ByteBuf _buf)
        {
            return new StartProcessConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public int Id;

        /// <summary>
        /// 所属机器
        /// </summary>
        public int MachineId;

        /// <summary>
        /// 内网端口
        /// </summary>
        public int InnerPort;

        /// <summary>
        /// dll
        /// </summary>
        public string dll;

        /// <summary>
        /// 程序名
        /// </summary>
        public string AppName;

        /// <summary>
        /// 进程名
        /// </summary>
        public string Title;


        public const int __ID__ = 2140444015;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MachineId:" + MachineId + ","
            + "InnerPort:" + InnerPort + ","
            + "dll:" + dll + ","
            + "AppName:" + AppName + ","
            + "Title:" + Title + ","
            + "}";
        }

        partial void PostInit();
    }
}

