using System.Collections.Generic;

namespace ET.Client
{
    public enum WindowID
    {
        WindowID_Invaild = 0,
        WindowID_MessageBox,
        WindowID_Lobby,    //房间界面
        WindowID_Login,     //登录界面
        WindowID_RedDot,   //红点测试界面
        WindowID_Helper,   //提示界面
    	WindowID_LSLobby,
		WindowID_LSLogin,
		WindowID_LSRoom,

        WindowID_MJLogin,     //登录界面(所有和demo有冲突的都加上MJ作为前缀)
    	WindowID_MJLobby,
		WindowID_CreateRole,
		WindowID_Main,
		WindowID_Role,
		WindowID_ItemTips,
		WindowID_HuoBiSet,
		WindowID_Chat,
		WindowID_Friend,
		WindowID_ItemSellTip,
		WindowID_EquipDuiBiTips,
		WindowID_PopupTip,
		WindowID_RoleBagSplit,
		WindowID_Task,
		WindowID_AppraisalSelect,
		WindowID_Pet,
		WindowID_SkillTips,
		WindowID_PetHeXinHeCheng,
		WindowID_PetHeXinSuit,
		WindowID_PetSelect,
		WindowID_PetHeChengExplain,
		WindowID_PetHeChengPreview,
		WindowID_PetChouKaGet,
		WindowID_ChengJiu,
		WindowID_Dungeon,
		WindowID_DungeonLevel,
		WindowID_Skill,
		WindowID_WatchMenu,
		WindowID_MapBig,
		WindowID_RoleZodiac,
		WindowID_Watch,
		WindowID_UnionRecords,
		WindowID_TaskGet,
		WindowID_Warehouse,
		WindowID_Mail,
		WindowID_RoleXiLian,
		WindowID_RoleXiLianTen,
		WindowID_RoleXiLianExplain,
		WindowID_RoleXiLianNumReward,
		WindowID_Store,
		WindowID_Mystery,
		WindowID_PetEgg,
		WindowID_CommonReward,
		WindowID_PetEggChouKaProbExplain,
		WindowID_RolePetBag,
		WindowID_PetEggLucklyExplain,
		WindowID_PetEggChouKaReward,
		WindowID_ChouKa,
		WindowID_ChouKaReward,
		WindowID_ChouKaProbExplain,
		WindowID_ChouKaWarehouse,
		WindowID_Rank,
		WindowID_PetFormation,
		WindowID_MakeLearn,
		WindowID_OccTwo,
		WindowID_OccTwoShow,
		WindowID_PaiMai,
		WindowID_WatchPaiMai,
		WindowID_PaiMaiBuyTip,
		WindowID_PaiMaiSellPrice,
		WindowID_WeiJingShop,
		WindowID_GemMake,
		WindowID_ShenQiMake,
		WindowID_ShouJi,
		WindowID_CountryTips,
		WindowID_ShouJiSelect,
		WindowID_Tower,
		WindowID_Trial,
		WindowID_TrialReward,
		WindowID_ZuoQi,
		WindowID_Protect,
		WindowID_Setting,
	}
}